### PR TITLE
Update developer.css

### PR DESCRIPTION
**Pull request by NaturalFractals**
Fixes Issue #6971.

Updated `div.review-entry pre` selector in developer.css from 

```
word-break: break-all;
```

to 

```
max-width: 650px;
word-wrap: break-word; 
```

### CODE REVIEW

**Comment by NaturalFractals** [comment]
It seems there are some test in Travis CI dealing with locale/language that my PR is failing. If someone could point me in the right direction to remedy this it would be greatly appreciated!

**Comment by wagnerand** [comment]
Thank you!

The test-failure seems unrelated, I restarted the job.

Could you please provide screenshots that show what the page looks like before and after your patch? Thank you!

**Comment by NaturalFractals** [comment]
Your welcome, thanks for your patience as this is my first PR to the project. 

Below are the screenshots from before and after. 

before

screen shot 2017-12-20 at 9 22 58 pm

**Comment by wagnerand** [comment]
The screenshots look fine to me, thank you.

You pushed a few unrelated changes, can you please rebase your patch onto master and remove any unrelated changes so we can merge this?

**Comment by NaturalFractals** [comment]
@wagnerand You can remove this PR. I made an error while rebasing and trying to restore the unchanged files. I'll have to work on learning git more throughly and come back to tackle some issues. Sorry for the inconvenience and thanks for your time!

**Pull request closed without merging**
