### PR TITLE
drop support for ES_HOSTS env variable now ELASTICSEARCH_LOCATION is used instead

### LINKED ISSUE #20778: Remove support for `ES_HOSTS` environement variable
`ES_HOSTS` will be replaced by `ELASTICSEARCH_LOCATION` in https://github.com/mozilla/addons-server/pull/20752. The will code still supports the old variable for backwards-compatibility, but once this has landed **and** SRE has modified the environnements to use the new variable we should remove that compatibility fallback.

See also https://mozilla-hub.atlassian.net/browse/SVCSE-1319

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-383)

### PR DESCRIPTION
**Pull request by eviljeff**
fixes #20778

### CODE REVIEW

**Comment by diox** [comment]
I thought Wei said this was only implemented on GCP side, so we couldn't do that yet ?

**Comment by eviljeff** [comment]
> I thought Wei said this was only implemented on GCP side, so we couldn't do that yet ?

I read his comment as "it's on dev now, and will be applied to stage and prod the next time they're deployed" (they've been deployed since) @bqbn can you confirm either way?

**Comment by bqbn** [comment]
> > I thought Wei said this was only implemented on GCP side, so we couldn't do that yet ?
> 
> I read his comment as "it's on dev now, and will be applied to stage and prod the next time they're deployed" (they've been deployed since) @bqbn can you confirm either way?

Could you remind me where I commented that? Sorry, I totally forgot where I commented that.

The last comment I remember saying was "And this will apply to GCP stage and prod environments later." in this ticket https://mozilla-hub.atlassian.net/jira/software/c/projects/SVCSE/boards/316

But in any case, the plan for going forward is that the new env variable `ELASTICSEARCH_LOCATION` will only be used in the GCP environment. AWS environments will keep using the old env variable `ES_HOSTS`. Once all environments are migrated to GCP, you can remove `ES_HOSTS` from code.

**Comment by eviljeff** [comment]
> > > I thought Wei said this was only implemented on GCP side, so we couldn't do that yet ?
> > 
> > 
> > I read his comment as "it's on dev now, and will be applied to stage and prod the next time they're deployed" (they've been deployed since) @bqbn can you confirm either way?
> 
> Could you remind me where I commented that? Sorry, I totally forgot where I commented that.
> 
> The last comment I remember saying was "And this will apply to GCP stage and prod environments later." in this ticket https://mozilla-hub.atlassian.net/jira/software/c/projects/SVCSE/boards/316

I guess I inserted a comma in my head between "this will apply to GCP" and "stage and prod environments later" when I read it!

> But in any case, the plan for going forward is that the new env variable `ELASTICSEARCH_LOCATION` will only be used in the GCP environment. AWS environments will keep using the old env variable `ES_HOSTS`. Once all environments are migrated to GCP, you can remove `ES_HOSTS` from code.

Okay, this it blocked on that happening then.

**Comment by eviljeff** [comment]
This is now unblocked, right?

**Comment by bqbn** [comment]
I think so, yes.

For added safety, once the change is merged, we should ask QA to verify searching is still working as usual.

**Review by diox — APPROVED** [review]

**Pull request merged**
