### PR TITLE
Fixes issue #3514 "Continue to download" button for experimental add-…

### PR DESCRIPTION
**Pull request by lavish205**
#3514 

@diox I've updated the patch as you have told, need to update test case as well. Can you please tell me more about creating a new test case as I've not work on this before.

### CODE REVIEW

**Comment by diox** [comment]
You need to add a new method to the test class with the assertions you want to test.

You already found the file to modify in your previous attempt, it's `src/olympia/addons/tests/test_buttons.py`. The class would be `TestButton`.

You want to set up data in the test method as I indicated in https://github.com/mozilla/addons-server/issues/3514#issuecomment-296685075, and verify the resulting `button_class`/`install_class`/`install_text` properties on the button are correct. Look at the other tests to understand how to do that (`test_show_contrib` and `test_experimental` in particular, since what you want is a mix of the 2)

**Comment by eviljeff** [comment]
@lavish205 will you be able to do the fixes diox mentioned?

**Comment by lavish205** [comment]
Yes, I'll re-generate PR by today.

**Comment by lavish205** [comment]
@diox I'm not sure whether this test case is right or not, can you please help me in fixing this?

**Comment by diox** [comment]
You have 3 things to fix:
- You're missing a newline at the end of the test method you added, causing [a flake8 failure](https://travis-ci.org/mozilla/addons-server/jobs/232906574).
- Your test is wrong. It's expecting `'caution'` but that's precisely what we are trying to remove.
- Your code has an issue when `button_class` is not present - because of the `try...except` clause, it will skip the removal of `'caution'`.

To fix that last issue, try something like:

```diff
diff --git a/src/olympia/addons/buttons.py b/src/olympia/addons/buttons.py
index b848d15..b94ed20 100644
--- a/src/olympia/addons/buttons.py
+++ b/src/olympia/addons/buttons.py
@@ -116,11 +116,10 @@ class InstallButton(object):
         self.button_class = list(self.__class__.button_class)
         self.install_class = list(self.__class__.install_class)
         if self.show_contrib:
-            try:
-                self.button_class.remove('download')
-                self.button_class.remove('caution')
-            except ValueError:
-                pass
-            self.button_class += ['contrib', 'go']
+            to_remove = ['download', 'caution']
+            self.button_class = (
+                filter(lambda v: v not in to_remove, self.button_class) +
+                ['contrib', 'go'])
             self.install_class.append('contrib')
 
         if self.size:
```

Run the tests yourself locally to try fixing the other 2 problems.

**Comment by EnTeQuAk** [comment]
@lavish205  did you have time to get to the changes @diox mentioned? Otherwise it'd be nice to not keep the pull request open for too long if no one is working on it at the moment.

**Comment by EnTeQuAk** [comment]
I'm closing this due to inactivity, if there's any update please feel free to re-open at anytime to get this landed.

**Pull request closed without merging**
