### PR TITLE
Add `call_ml_api` task to the validation chain

### PR DESCRIPTION
**Pull request by willdurand**
Fixes https://github.com/mozilla/addons-server/issues/13331

---

Because this task must be the [callback of the chord](https://docs.celeryproject.org/en/latest/userguide/canvas.html#chords), we have to add it to the chain all the time and therefore the switch has to live in the task itself. I think it is fine, though. I did a few tests and it should not impact the submission process.

### CODE REVIEW

**Comment by willdurand** [comment]
(also /cc @diox)

**Comment by diox** [comment]
So with that change we'd be chaining the result of a chord with another task. Need to double-check how safe it is, given the recent regressions we've seen with celery and complex workflows.

**Comment by willdurand** [comment]
> So with that change we'd be chaining the result of a chord with another task. Need to double-check how safe it is, given the recent regressions we've seen with celery and complex workflows.

Yes, I was surprised that it worked so well locally.

**Comment by willdurand** [comment]
I rebased this patch to avoid a migration conflict.

**Comment by diox** [comment]
When I fixed [the reindexation code to work with Celery > 4.1.1](https://github.com/mozilla/addons-server/issues/13049), one of the things I did was separate in a specific method the code that returns the tasks workflow to run, and add [a test that proves the workflow looks good](https://github.com/mozilla/addons-server/pull/13073/files#diff-ad36a728cb976284cc85b48045843640R177).

Since the workflow is getting quite complex here, I think it'd be good to also have that in this case.

**Comment by willdurand** [comment]
> When I fixed [the reindexation code to work with Celery > 4.1.1](https://github.com/mozilla/addons-server/issues/13049), one of the things I did was separate in a specific method the code that returns the tasks workflow to run, and add [a test that proves the workflow looks good](https://github.com/mozilla/addons-server/pull/13073/files#diff-ad36a728cb976284cc85b48045843640R177).
> 
> Since the workflow is getting quite complex here, I think it'd be good to also have that in this case. Something that would break loudly if there is a bad regression in celery, something we can't necessarily see in other unit tests that are ran in eager mode.

I like the idea but I am not sure to understand how the test case works.

We have test cases where we only mock the main `chain` so that we can have assertions on all the tasks in it, making sure we configure the chains/chords correctly.

I agree that an internal change in Celery would likely not break these tests, though but it is not clear to me how the linked test case covers that. Is it thanks to `assert isinstance(workflow, _chain)`?

**Comment by diox** [comment]
Mocking `chain` tells you what you give to celery, but that doesn't tell you how celery actually translates it later. Celery automatically "upgrades" a group chained to a task to a chord for instance, and also modifies the workflow in other circumstances, trying to fit what you gave as input into something workers can then use.

I don't remember exactly what in that test was revealing the breakage, but I think you should inspect everything: the returned object, the tasks in it, etc, much like that test does.

**Comment by willdurand** [comment]
Right, let me see how I can convert that into a test case.

**Pull request merged**
