### PR TITLE
Fix blank horizontal scroll on addons details page

### LINKED ISSUE #5965: [RTL] Blank horizontal scroll on addons details page
### Describe the problem and steps to reproduce it:
Navigate to https://addons.mozilla.org/ar/firefox/addon/privacy-badger17/?src=hp-btn-promo
After page load a horizontal scroll is observed.
Scroll left.

### What happened?
got a horizontal scroll on addons detail page, a blank space towards left of the page

### What did you expect to happen?
there should be no horizontal scroll.

screen shot 2017-07-20 at 6 23 49 pm

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

### PR DESCRIPTION
**Pull request by atiqueahmedziad**
Fixes #5965 

- This should stop the blank horizontal scroll in RTL view. 
- The star should work fine in RTL 

Please do a test before merging. I couldn't test it since AMO website in my local environment is not showing any add-ons.

### CODE REVIEW

**Comment by muffinresearch** [comment]
@atiqueahmedziad if you just add `overflow: hidden` and leave the transform I think you can avoid the additional images.

**Comment by EnTeQuAk** [comment]
> Please do a test before merging. I couldn't test it since AMO website in my local environment is not showing any add-ons.

If you run `make populate_data` inside your docker container then you should get some data.

**Comment by EnTeQuAk** [comment]
Hey @atiqueahmedziad, did you have time to look into this pull request recently?

**Comment by atiqueahmedziad** [comment]
Sorry for late response, @EnTeQuAk I have updated the commit.

**Pull request merged**
