### PR TITLE
Removed code from t-shirt.html

### PR DESCRIPTION
**Pull request by theaverageguy**
Fixes https://github.com/mozilla/addons-server/issues/1771

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
I think this only fixes the issue partially. There's still the view-code in https://github.com/mozilla/addons-server/blob/e66197c915d5b260645fd73fec04ab22b5db7a22/src/olympia/users/views.py#L263 that could be removed if it's unused and once that's gone the whole t-shirt.html should be obsolete too.

**Comment by yash14123** [comment]
I will submit another PR for that. :)

**Comment by muffinresearch** [comment]
@yash14123 can you just update this PR instead?

**Comment by andymckay** [comment]
Should we almost remove the column from the model? https://github.com/mozilla/addons-server/blob/master/src/olympia/users/models.py#L201-L202

**Comment by EnTeQuAk** [comment]
Do we have old data in there that we need for customer support, e.g "I didn't get my shirts!"?

**Comment by jvillalobos** [comment]
Since it was for a promo that was run years ago, I don't think there's anything in it we can use.

**Comment by muffinresearch** [comment]
@theaverageguy I'm going to close this for now - but feel free to re-open when you've got an update.

**Pull request closed without merging**
