### PR TITLE
Restore old translations that were lost due to whitespace changes.

### PR DESCRIPTION
**Pull request by EnTeQuAk**
Script being used to extract them:
https://gist.github.com/EnTeQuAk/6b5953b9fb2a02b51d0f

And ran `msgattrib --no-obsolete --width=200` over the .po files as `omg_new_l10n.sh` does.

refs #1782

r? @diox @ddurst

### CODE REVIEW

**Comment by ddurst** [comment]
The only things I can't speak to are:
a) whether the script output any significant errors when run, and
b) how read_po() handles multi-line msgids (meaning, if they're aggregated into one normalized string internally so that the call `original_msg = original_catalog.get(normalized_id)` would be guaranteed to return the correct result.

But if those two things are OK, then we should merge this and extract.

Not sure if @diox wants to look at this or punt to @washort.

**Comment by diox** [comment]
You may need to sync up with @mathjazz just in case ?

**Comment by ddurst** [comment]
(I spot-checked a few results, which lgtm. Fwiw.)

**Comment by ddurst** [comment]
ok, then let's do this thing

**Comment by ddurst** [comment]
(That means r+, but I can't merge. Help?)

**Comment by mstriemer** [comment]
I rebased this and hit a conflict [1]. I took the newer change (the one on the top).

[1] https://gist.github.com/mstriemer/04b9c73ce865f609de57#file-django-po-orig-L4500-L4507

**Pull request closed without merging**
