### PR TITLE
Raise reviews per page to 300

### PR DESCRIPTION
**Pull request by kewisch**

### CODE REVIEW

**Comment by kewisch** [comment]
Some discussion has come up on this on if the limit is ok from a performance perspective, and what the use case is so we should probably hold.

As for use case, part of this is personal preference that I would like to see them all on one page instead of having to go through the pages. For that matter, raising the _MAX limit alone would be sufficient to me.

I also have the suspicion that reviewers looking only at the end of the queue will be intuitively jumping to the last page. Putting more on one page may give them more incentive to check higher entries. I don't have any data to back this up though.

If you would like to save performance I could lower the default per_page value but keep the max at 600. I have been using the max 200 and it did not seem slow to me, and I would like to try higher values.

**Comment by diox** [comment]
I don't find it prudent to change both values at the same time. Especially with a default higher than the old max. The new max is also quite significantly larger than the previous one.

**Comment by EnTeQuAk** [comment]
r+ to 200/400 if that's something you really need

**Comment by EnTeQuAk** [comment]
@kewisch any updates on this?

**Comment by kewisch** [comment]
Sorry for the delay, patch with 200/400 is up

**Pull request merged**
