### PR TITLE
remove perf

### PR DESCRIPTION
**Pull request by andymckay**

### CODE REVIEW

**Comment by tofumatt** [comment]
Seems Travis can't install dependencies, though that was as clear as the error looked to me upon a quick glance.

**Comment by EnTeQuAk** [comment]
This branch doesn't just remove `olympia.perf` but adds coverage tracking, can we split those please?

**Comment by andymckay** [comment]
I give up on coveralls, cannot get py.test to pickup pytest-cov, works locally just fine, but theres always that fun difference that travis use tox which is completely different from our local environments see also issue #1464.

**Comment by EnTeQuAk** [comment]
How that the coverage stuff is not in the PR anymore, lgtm

r+

**Comment by andymckay** [comment]
Maybe, do developers want coveralls in?

**Comment by EnTeQuAk** [comment]
having an automatic coverage report is quite nice, it's more important for library-owners but if it works and the effort is reasonable, let's do it. Or at least try to integrate it at some point. I doubt it's important though.

**Comment by diox** [comment]
Do consider alternatives to coveralls though, like https://codecov.io/ ? I don't know which one is the best, I just had to fight with coveralls in the past so maybe there are decent alternatives we should explore.

**Pull request merged**
