### PR TITLE
Rename 'social-footer' to 'links-footer'

### PR DESCRIPTION
**Pull request by wagnerand**
See #2302

r?

### CODE REVIEW

**Comment by tofumatt** [comment]
While we're at it, can we just change this from an ID to a class? It really should be a class :smile: 

r+wc

**Comment by wagnerand** [comment]
Not sure why, but will do.

**Comment by tofumatt** [comment]
IDs are used to mark sections of the page for people; classes are used for computers to style things :-)

**Comment by wagnerand** [comment]
Done.

**Comment by wagnerand** [comment]
Thanks for clarifying.

**Pull request merged**
