### PR TITLE
use our old pjax to see if it fixes the js error

### LINKED ISSUE #5677: JS error in console while accessing any page from AMO-dev
Steps to reproduce:
1. Load any page in AMO-dev i.e. https://addons-dev.allizom.org/en-US/firefox/
2. Open the console and observe the messages 

Expected results:
No `js` error displayed in the console.

Actual results:
The `js` error "TypeError: (intermediate value)(...) is not a function" is displayed in the console.

Notes/Issues:
Verified on AMO-dev FF53(Win 7). Issue is only reproducing on -dev.
Screenshot fro this issue:
js

### PR DESCRIPTION
**Pull request by eviljeff**
Switches back #5666 to use the old jquery pjax file, to fix #5677

### CODE REVIEW

**Comment by eviljeff** [comment]
could you replicate the issue locally without the fix?

**Comment by diox** [comment]
Yep, exact same error.

**Comment by eviljeff** [comment]
#5677 is only reproducible when using the impala.js bundle.  When the non-minified files are used in a local dev environment the error doesn't occur.

**Pull request merged**
