### PR TITLE
drop {% if reviews %} from profile template

### LINKED ISSUE #5480: MaDonna's profile page is hanging
### Describe the problem and steps to reproduce it:
Go to https://addons.mozilla.org/en-US/firefox/user/MaDonna/
It takes a long time to load, if at all.

### What happened?
It seems to only affect her page and not others on AMO. Possible we've come upon an edge case with her in terms of size of profile page?

### What did you expect to happen?
I expected it to load like any other AMO page.

### Anything else we should know?
She recently began using HTML in her About Me field. Something to do with that?

### PR DESCRIPTION
**Pull request by eviljeff**
fixes #5480

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
r+


On Tue, May 30, 2017, at 07:11 PM, Andrew Williamson wrote:
> @eviljeff[1] requested your review on: mozilla/addons-server#5518[2]
> drop {% if reviews %} from profile template.> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[3], or mute the thread[4].> 

Links:

  1. https://github.com/eviljeff
  2. https://github.com/mozilla/addons-server/pull/5518
  3. https://github.com/mozilla/addons-server/pull/5518#event-1102187693

**Comment by MaDonnasPersonas** [comment]
Any idea when the bug will be fixed? My profile still will not come up.

**Comment by diox** [comment]
We deploy to production once a week, it should be up tomorrow (see the milestone field in [the issue](#5480))

**Comment by MaDonnasPersonas** [comment]
Thanks so much. Appreciate it.

**Pull request merged**
