### PR TITLE
Add rabbitmq services monitor

### PR DESCRIPTION
**Pull request by jasonthomas**
This adds a rabbitmq check to our app monitoring endpoint. r?

### CODE REVIEW

**Comment by andymckay** [comment]
Awesome, thanks for adding @jasonthomas 👍

**Comment by EnTeQuAk** [comment]
I would looooove some tests but it's an internal tool and we don't have any for the other monitoring tools either. We should though.

**Comment by diox** [comment]
We could steal the basic tests I wrote for zamboni some time ago: https://github.com/mozilla/zamboni/pull/2845

**Comment by jasonthomas** [comment]
I will work on adding tests.

**Comment by jasonthomas** [comment]
I stole most of the tests from mozilla/zamboni#2845 

r?

**Comment by EnTeQuAk** [comment]
Perfect, thanks for the update!

r+

**Pull request merged**
