### PR TITLE
Change delete version warning message

### PR DESCRIPTION
**Pull request by dnutiu**
Hello,

This PR solves: https://github.com/mozilla/addons-server/issues/13535

I couldn't manage to test my change locally, I need some help running the docker containers. `docker-compose up` works but I can't access olympia.test and accessing localhost:3000 gives me a page without CSS.

### CODE REVIEW

**Comment by dnutiu** [comment]
Managed to run it locally, attaching a screenshot:

image

**Comment by caitmuenster** [comment]
Hi @willdurand, adding this to your review queue. :)

**Comment by willdurand** [comment]
thanks

**Comment by caitmuenster** [comment]
Woohoo! Thanks for the patch, @dnutiu. 🎉Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition). 

I'd be happy to vouch for your account on mozillians.org. :) Is https://mozillians.org/u/dnutiu/ your profile?

**Comment by dnutiu** [comment]
Thanks Caitlin!
Yes, that's my profile. :)

**Comment by caitmuenster** [comment]
Excellent! Your profile has been vouched. ✨

Welcome onboard! I look forward to seeing you around. :)

**Comment by eviljeff** [comment]
@dnutiu if you comment in the original issue we can assign it to you (github limitation with assigning people)

**Comment by dnutiu** [comment]
@eviljeff Thanks, will do. Didn't know about this

**Pull request merged**
