### PR TITLE
I2525

### PR DESCRIPTION
**Pull request by tsl143**
Themes backgrounds are not correctly aligned in homepage carrousel #2525

### CODE REVIEW

**Comment by muffinresearch** [comment]
@tsl143 could you rebase your PR against master please? Looks like there's a lot of unrelated changes in this PR. When you're done you should have one commit which represents just the style changes.

If you need any help with that let us know and we can walk you through it.

**Comment by tsl143** [comment]
@muffinresearch I do not know how to rebase, can you point me to some source?
PS I used 

> git rebase origin/master

**Comment by EnTeQuAk** [comment]
https://help.github.com/articles/using-git-rebase/ and https://git-scm.com/book/en/v2/Git-Branching-Rebasing are pretty good resources regarding rebasing.

What you did is pretty much alright you just need to make sure you have all your changes from the remote repository fetched:

```bash
$ # updates origin/master
$ git fetch origin
$ # Reases current branch onto origin/master
$ git rebase origin/master
```

In your case especially your local branch has commits your local `master` doesn't that's why they're shown here.

**Comment by muffinresearch** [comment]
I've been talking to @tsl143 on irc and he's working on pushing up just the relevant commit.

**Comment by tofumatt** [comment]
Looks like https://github.com/mozilla/addons-server/pull/2567/commits/23517a21cc44c8778e084b8c754f97eadfad9e58 is the contents of the commit you want.

Learning git rebase can be tough.

You may want to try creating a new branch from recent master and trying a new PR rather than learning rebase for your first patch to AMO 😄 

You can do:

```
git checkout master
git pull origin master
git checkout -b carousel-patch-2525
```

Then make your patch, add and commit, and push that with a new PR.

Let me know if you need any help.

**Comment by tofumatt** [comment]
Oh shoot, sorry :-/

Thanks

**Comment by tsl143** [comment]
NEW PR https://github.com/mozilla/addons-server/pull/2580

**Pull request closed without merging**
