### PR TITLE
containers shield study page

### PR DESCRIPTION
**Pull request by groovecoder**
Still need to:

* [ ] get the final URL for the signed `.xpi` file to install

### CODE REVIEW

**Comment by muffinresearch** [comment]
@groovecoder do you have an expected release date in mind?

**Comment by groovecoder** [comment]
@muffinresearch ASAP? We're starting to convert our `@testpilot-containers` add-on into a "plain" AMO add-on for release with Fx 55 (Aug 8) or 56 (Sep 26).

And although we don't expect it, the data from this study could influence our strategy away from an AMO add-on and towards a core product feature release.

28 days before Aug 8 is July 11 (Tuesday).

28 days before Sep 26 is Aug 29.

**Comment by muffinresearch** [comment]
@groovecoder our next push is July 13th, which will be tagged on July 11th at 0900 PST. As long as changes have landed before the tag, they will go out on the 13th.

**Comment by EnTeQuAk** [comment]
This also uses number 13 for the shield study and clashes with https://github.com/mozilla/addons-server/pull/5876 and https://github.com/mozilla/addons-server/pull/5865 so that'll have to be resolved before merging.

**Comment by groovecoder** [comment]
Superseded by https://github.com/mozilla/addons-server/pull/5884

**Pull request closed without merging**
