### PR TITLE
Remove harsh borders from details (fix #1871)

### LINKED ISSUE #1871: Separators looks a bit severe on the details page
copy_plain_text_2____add-ons_for_firefox

Note there's one that's a less bright blue - maybe if they all went in that direction it would stand-out less?

### PR DESCRIPTION
**Pull request by tofumatt**
Remove the borders from the details page; there were tonnes of different kinds and I didn't think they were adding much. Feel free to tell me if I'm wrong ^_^

### Before

copy_plain_text_2____add-ons_for_firefox

### After

screen shot 2016-03-21 at 15 22 34

r? @muffinresearch @designakt

### CODE REVIEW

**Comment by muffinresearch** [comment]
I wonder what a lighter border colour would look like as opposed to removing them entirely? No border makes it feel a bit disconnected somehow.

**Comment by tofumatt** [comment]
New version with softer borders (but border between reviews and versions removed):

screen shot 2016-03-21 at 17 16 24

**Comment by muffinresearch** [comment]
@tofumatt - we'll need to get @pwalm's + @designakt's input on this one.

**Comment by tofumatt** [comment]
Sounds good, I’ll wait :-)

**Comment by pwalm** [comment]
Let's keep the softer borders, but make them even softer in grey: #EBEBEB should do it

**Comment by tofumatt** [comment]
Updated to the requested grey, thanks @pwalm.

screen shot 2016-03-22 at 19 24 22

r? @muffinresearch

**Comment by pwalm** [comment]
Oh yeah, that looks great 👍🏻

**Comment by tofumatt** [comment]
Yeah, the grey really suits the page, thanks!

**Comment by muffinresearch** [comment]
Looks nice! r+ 

wink

**Pull request merged**
