### PR TITLE
Fix IRC link to actually be a link (close #1917)

### LINKED ISSUE #1917: Make the IRC address (#amo) in the README a link
So users can click on it and open it in their IRC client of choice. It's nice!

### PR DESCRIPTION
**Pull request by tofumatt**
The text reads a bit nicer and the link is fixed.

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
r+

**Comment by tofumatt** [comment]
Grrr, this still doesn't display as a link on GitHub... I am bad at rst but
maybe it's the space in the link. I'll check and test the rst output in
another patch.
- tofumatt

**Comment by EnTeQuAk** [comment]
It might just be that GitHub doesn't interpret `irc://` as a web-protocol and doesn't replace it with a link.

**Comment by tofumatt** [comment]
I tried to preview it on GitHub a few ways and I think you're right. Darn, oh well. :-(

- tofumatt

**Pull request merged**
