### PR TITLE
Include disabled add-on when generating stats

### LINKED ISSUE #8975: Collect stats for disabled add-ons
#8947 enables admins to see stats for disabled add-ons. However, the information is currently not even collected/generated.

We need to collect stats for disabled add-ons, so we can show them.

@diox suggested to collect stats on all add-ons except add-ons that have `STATUS_DELETED` or `STATUS_NULL` for performance reasons.

### PR DESCRIPTION
**Pull request by wagnerand**
Fix #8975.

### CODE REVIEW

**Comment by wagnerand** [comment]
> This probably also needs some look from ops to check that we actually have the data we're downloading/requesting here. Do we have that?

Paging @bqbn for that.

**Comment by wagnerand** [comment]
> There are actually a few tests that test some very basic things from these stats commands in stats/tests/test_commands.py which we may be able to extend to test this.

@EnTeQuAk I am not that familiar with generating stats. Could you point me to one more tests and guide me how to extend those, please?

**Comment by bqbn** [comment]
> > This probably also needs some look from ops to check that we actually have the data we're downloading/requesting here. Do we have that?
>
> Paging @bqbn for that.

What data do you want us to check?

**Comment by wagnerand** [comment]
@bqbn We are expanding the number of add-ons we're collecting stats for in https://github.com/mozilla/addons-server/blob/1c553d4c9b8583e1a7d32fc15b9523187be7a9f9/scripts/crontab/crontab.tpl#L52-L53

which might lead to longer runtimes.

I am not sure sure which ones exactly, but at least some cronjobs in https://github.com/mozilla/addons-server/blob/1c553d4c9b8583e1a7d32fc15b9523187be7a9f9/scripts/crontab/crontab.tpl#L42-L48 depend on the ones above having finished.

**Comment by bqbn** [comment]
Yesterday's log shows the scripts took the following times to finish respectively,

* update_counts_from_file: 1'55''
* download_counts_from_file: 41''
* theme_update_counts_from_file: 24"
* update_theme_popularity_movers: no data, [the script](https://github.com/mozilla/addons-server/blob/master/src/olympia/stats/management/commands/update_theme_popularity_movers.py) doesn't have a INFO level log line. 

Note for the first 3 listed files, I used `'Processed a total of %s lines'` log line as an indication of the script finishing running.

**Comment by EnTeQuAk** [comment]
This is how you could test this:

```udiff
diff --git a/src/olympia/stats/fixtures/files/src/download_counts.hive b/src/olympia/stats/fixtures/files/src/download_counts.hive
index ee3cb52e5a..95ced25367 100644
--- a/src/olympia/stats/fixtures/files/src/download_counts.hive
+++ b/src/olympia/stats/fixtures/files/src/download_counts.hive
@@ -6,3 +6,4 @@
 2014-07-10     1        666    search
 2014-07-10     1        7661   search
 2014-07-10     1        a3615  search
+2014-07-10  1    disabled-addon search
diff --git a/src/olympia/stats/tests/test_commands.py b/src/olympia/stats/tests/test_commands.py
index 98eafd31d5..83079e8399 100644
--- a/src/olympia/stats/tests/test_commands.py
+++ b/src/olympia/stats/tests/test_commands.py
@@ -183,6 +183,23 @@ class TestADICommand(FixturesFolderMixin, TransactionTestCase):
         assert download_count.date == date(2014, 7, 10)
         assert download_count.sources == {u'search': 2, u'cb-dl-bob': 1}

+    def test_download_counts_from_file_includes_disabled_addons(self):
+        # The data already exists in the addon_3615 fixture
+        addon_factory(slug='disabled-addon', status=amo.STATUS_NULL)
+        management.call_command('download_counts_from_file', hive_folder,
+                                date=self.date, stats_source=self.stats_source)
+        assert DownloadCount.objects.all().count() == 3
+        download_count = DownloadCount.objects.get(addon_id=3615)
+        assert download_count.count == 3
+        assert download_count.date == date(2014, 7, 10)
+        assert download_count.sources == {u'search': 2, u'cb-dl-bob': 1}
+
+        download_count = DownloadCount.objects.get(
+            addon__slug='disabled-addon')
+        assert download_count.count == 1
+        assert download_count.date == date(2014, 7, 10)
+        assert download_count.sources == {u'search': 1}
+
     @mock.patch(
         'olympia.stats.management.commands.download_counts_from_file.'
         'close_old_connections')
```

**Comment by EnTeQuAk** [comment]
Given that this was a joined effort by @wagnerand and me someone else should give this a look.

**Comment by EnTeQuAk** [comment]
Nevermind, this isn't ready yet.

**Pull request merged**
