### PR TITLE
Add wcwidth as test dep

### PR DESCRIPTION
**Pull request by willdurand**
Fixes https://github.com/mozilla/addons-server/issues/14195, hopefully

### CODE REVIEW

**Comment by wagnerand** [comment]
What would be a good way to test this? Do you want to introduce a test-failure in a temporary commit to see if the error is still raised?

**Comment by willdurand** [comment]
> What would be a good way to test this? Do you want to introduce a test-failure in a temporary commit to see if the error is still raised?

I was hoping to get a failure.. I guess, yes, introducing a failure is the right thing to do now that everything works as intended...

**Comment by diox** [comment]
Note that it's an [explicit requirement](https://github.com/pytest-dev/pytest/blob/master/setup.py) from pytest so we should definitely include it.

**Comment by willdurand** [comment]
> Note that it's an [explicit requirement](https://github.com/pytest-dev/pytest/blob/master/setup.py) [](/pytest-dev/pytest/blob/HEAD@{2020-05-06T22:47:35Z}/setup.py)

Then I guess, no need to test it further.

**Pull request merged**
