### PR TITLE
remove moreinfo.php, an old redirect

### LINKED ISSUE #2307: Remove moreinfo.php
https://addons.mozilla.org/en-US/firefox/themes/moreinfo.php?id=123

Redirects you to here:

https://addons.mozilla.org/en-US/firefox/discovery/addon/nautipolis-for-firefox/

Based on:

https://github.com/mozilla/addons-server/blob/master/src/olympia/browse/views.py#L511-L517

It looks like this is because of the bug:

https://bugzilla.mozilla.org/show_bug.cgi?id=746656

I did some work in google analytics and found this is hardly ever called. But then again it could be my analytics lack of skills.  @jasonthomas could you confirm with a quick access log grep?

### PR DESCRIPTION
**Pull request by andymckay**
fixes #2307, assuming i'm correct that this gets very little traffic

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
Where did you get that info that this get's very little traffic?

Generally, removing anything with `.php` in the url path get's a huge r+ :smiley:

**Comment by andymckay** [comment]
I looked in google analytics to find pages that had a referrer of moreinfo.php. But I'm not 100% sure on my analytics skills so would like that second check from @jasonthomas on the access logs.

**Comment by jasonthomas** [comment]
Less than 600 requests a day to moreinfo.php, mostly from bots.

**Comment by andymckay** [comment]
There you go, my google analytics foo failed me.

**Comment by andymckay** [comment]
I say, lets remove, what do you reckon @muffinresearch

**Comment by andymckay** [comment]
And by the way I just googled moreinfo.php and found a bunch of old links from 2005/6 the majority of which don't actually work because they refer to long dead add-ons. Cool URIs don't change, but this one is probably not a cool URI.

**Comment by muffinresearch** [comment]
Yep sounds good. Let's embrace the impermanence!

**Pull request merged**
