### PR TITLE
Don't expose 'image' as binary boolean value.

### LINKED ISSUE #10685: Don't expose image binary type
In the reviewers browse api we're exposing the field `binary` which can be a boolean or string but really, should only be a boolean.

We are already exposing the mimetype so the client should be able to handle that properly.

### PR DESCRIPTION
**Pull request by EnTeQuAk**
Fixes #10685

### CODE REVIEW

**Comment by eviljeff** [comment]
Mmm, so I get
> In the reviewers browse api we're exposing the field `binary` which can be a boolean or string but really, should only be a boolean.

but I don't follow the logic where an image isn't `binary=True` - an image literally is a binary file, rather than a text file.

**Comment by eviljeff** [comment]
Does `binary` need to be replaced with `should_be_displayed_inline` (or something less wordy)?  Wouldn't that be a decision for the client anyway?  (so is this property necessary at all?)

**Comment by EnTeQuAk** [comment]
It would, you're right. I think we may want to rename this to `is_blocklisted_binary` or so, as this is there to avoid the client to do anything at all with .exe files and friends.

Does that sound more reasonable?

**Comment by EnTeQuAk** [comment]
> what is the request/need from the frontend exactly?

We don't want the frontend to touch / open executable files ideally. That's why that's in place but tbh, I don't know how useful it is given that add-ons have changed dramatically in the past.

cc @wagnerand maybe for some ideas

**Comment by EnTeQuAk** [comment]
This will be reworked

**Pull request closed without merging**
