### PR TITLE
Add coverage badge

### PR DESCRIPTION
**Pull request by muffinresearch**
Add back the coverage badge so we can see it and track it.

### CODE REVIEW

**Comment by diox** [comment]
Last I checked it was broken and didn't reflect reality, that's why I pulled it out. We've had some problems in the past finding a service that was a) reliable b) worked well with the way addons-server tests matrix is set up.

**Comment by muffinresearch** [comment]
Ah ok - I wondererd why it was missing. Most of our other services are using codecov rather than coveralls do you know if that would be any better in supporting the current configuration?

It doesn't have to be a super high priority, but would be good to know where coverage is at.

**Comment by diox** [comment]
We tried codecov back in the day (removed in https://github.com/mozilla/addons-server/issues/4538) and the main problem IIRC is it was super noisy for what was essentially rounding errors - like it'd tell us our coverage dropped to 92.576% from 92.577% just because a file was removed, things like that.

On top of that, a problem we've had with coverage services in the past is that we have lots of tests, and our tests are slow and clunky, so they are split between different jobs that run in parallel to be faster. Generating the coverage data sometimes took a significant amount of time per job, and it also has to be reconciled between different jobs, and that also had a significant perf cost sometimes.

Not sure if there has been some improvements that would fix those 2 pain points. We can certainly try to add it back - right now coverage report generation has been completely removed from the test suite.

**Comment by diox** [comment]
Screenshot_2020-05-28 Coveralls io - Test Coverage History and Statistics

None of these files or their coverage make sense. Not only are there only JavaScript files but they don't even match anything in our repos or our dependencies. That makes the coverage numbers totally bogus.

**Comment by eviljeff** [comment]
Closing this because fixing coverage is a prerequisite to adding the badge back.

**Pull request closed without merging**
