### PR TITLE
Remove smart_path and some other duplicate implementation of it.

### LINKED ISSUE #1068: Remove amo.utils:smart_path
It was introduced in 576151577f57ca053313196a4a007a1b9ba39046 it seems as a python 2.6 compat patch so it could be removed I think.

### PR DESCRIPTION
**Pull request by EnTeQuAk**
Fixes #1068

### CODE REVIEW

**Comment by muffinresearch** [comment]
Do these changes have coverage already?

**Comment by EnTeQuAk** [comment]
Hmm, they were introduced in 576151577f57ca053313196a4a007a1b9ba39046 as a pure python 2.6 compat fix. But good point, I'll add a test to make sure both places properly accept unicode filenames.

**Comment by EnTeQuAk** [comment]
Actually, there are tests for every one of the changes already: 

* https://github.com/mozilla/addons-server/blob/master/src/olympia/amo/tests/test_amo_utils.py#L177
* https://github.com/mozilla/addons-server/blob/master/src/olympia/files/tests/test_models.py#L659
* https://github.com/mozilla/addons-server/blob/master/src/olympia/files/tests/test_models.py#L986

So we're good to go on that side, r?

**Comment by muffinresearch** [comment]
Looks like the old behaviour was using `force_text` for python 2.7 and `force_bytes` for python 2.6 where `os.path.supports_unicode_filenames` is False. But this change uses `force_bytes` everywhere, is that right?

**Comment by EnTeQuAk** [comment]
Correct, the results should be almost identical. `os.path.supports_unicode_filenames` is a bit twisted too sometimes so I'm settling with the safest way to handle file names which is encode them to utf8 before handing them over to `os.path.*`

**Comment by muffinresearch** [comment]
r+

**Pull request merged**
