### PR TITLE
correctly show due_date for unlisted versions awaiting manual review

### PR DESCRIPTION
**Pull request by eviljeff**
follow-up for #19985 to fix "Unlisted Add-ons Pending Manual Approval" queue

### CODE REVIEW

**Comment by diox** [comment]
https://github.com/mozilla/addons-server/pull/20181 will probably make this irrelevant

**Comment by eviljeff** [comment]
> #20181 will probably make this irrelevant

🤷‍♂️ I guess review/merge if it's not going to land in the next milestone

**Comment by diox** [comment]
I'll evaluate tomorrow but I'll probably close this in favor of #20181 to avoid fixing conflicts for something that will go away fairly soon and isn't that important.

**Comment by diox** [comment]
Closed in favor of the merged queue (https://github.com/mozilla/addons-server/pull/20181)

**Pull request closed without merging**
