### PR TITLE
Bump elasticsearch version in docker to match other envs

### PR DESCRIPTION
**Pull request by diox**

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
Indeed, I still think that I got the version from Jason back then but maybe we updated in the meantime? 

r+

**Comment by diox** [comment]
@jasonthomas can you confirm which ES version we are using everywhere ?

**Comment by jasonthomas** [comment]
We are using 1.6.2 in prod right now.

**Comment by diox** [comment]
Perfect.

**Pull request merged**
