### PR TITLE
Fix issue #7783

### PR DESCRIPTION
**Pull request by deepanshu-jain1999**
Thanks for opening a Pull Request (PR), here's a few guidelines as to what we need in your PR before we review it.

Please delete anything that isn't relevant to your patch.

* [ ] This PR relates to an existing open issue and there are no existing
      PRs open for the same issue.
* [ ] Add `Fixes #ISSUENUM` at the top of your PR.
* [ ] Add a description of the the changes introduced in this PR.
* [ ] The change has been successfully run locally.
* [ ] Add tests to cover the changes added in this PR.
* [ ] Add before and after screenshots (Only for changes that impact the UI).

Once you have met the above requirements please replace this section with
a `Fixes #ISSUENUM` linking to the issue fixed by this PR along with an
explanation of the changes. Thanks for your contribution!

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
Can you please attach a screenshot of what you changed, preferably a before/after screenshot? That'll make it easier for us to verify your pull request and for our QA-team to understand the changes better.

**Comment by deepanshu-jain1999** [comment]
I think I do something wrong. I have change in the static/css/devhub/static-theme.less.css but I had to change in static/css/devhub/static-theme.less. So after change in proper file I will again create pull request
and one more things Please tell me there is some issue at the time of project setup locally with docker in command "make initialize_docker".

**Comment by EnTeQuAk** [comment]
> I think I do something wrong. I have change in the static/css/devhub/static-theme.less.css but I had to change in static/css/devhub/static-theme.less. So after change in proper file I will again create pull request

Please just update your currently used git branch, there's no need to open another new pull request. If you commit new changes to your branch and push them this pull request will show them. This has the advantage of showing a history of your changes which allows us to track your progress and better help you if you're stuck.

> and one more things Please tell me there is some issue at the time of project setup locally with docker in command "make initialize_docker".

Can you explain this a bit more? What issues are you running into?

**Comment by deepanshu-jain1999** [comment]
1.docker-compose pull
2.docker-compose up -d
step 1 and 2 are ok but when I perform "make initialize_docker" it gives this error :- 
Makefile-docker:70: recipe for target 'initialize_db' failed
make: *** [initialize_db] Error 1
Makefile-os:47: recipe for target 'initialize_docker' failed
make: *** [initialize_docker] Error 2

**Comment by deepanshu-jain1999** [comment]
Solved it.
But now I am getting this error when i am changing in file " static/css/devhub/static-theme.less " :-
Permission denied: u'/code/static/css/devhub/static-theme.less.css'

**Comment by deepanshu-jain1999** [comment]
Ok solved it.

**Comment by deepanshu-jain1999** [comment]
Before changes
before
After changes
new_change

**Comment by deepanshu-jain1999** [comment]
I think I will have to create new pull request because I deleted the old fork repository and create new fork repository. Is there any other solution with existing pull request?

**Comment by EnTeQuAk** [comment]
> I think I will have to create new pull request because I deleted the old fork repository and create new fork repository. Is there any other solution with existing pull request?

That's unfortunate then, I don't know if GitHub links them together nontheless but it does not seem so. So yeah, I'm going to close this PR for now and feel free to open a new one with all your new and shiny changes.

Thanks a lot for working on this!

**Pull request closed without merging**
