### PR TITLE
Created New Migration File Fixes#11216

### PR DESCRIPTION
**Pull request by Patil2099**
Removed ip_address column from abuse_reports table

Thanks for opening a Pull Request (PR), here's a few guidelines as to what we need in your PR before we review it.

Please delete anything that isn't relevant to your patch.

* [x] This PR relates to an existing open issue and there are no existing
      PRs open for the same issue.
* [x] Add `Fixes #ISSUENUM` at the top of your PR.
* [x] Add a description of the changes introduced in this PR.
* [x] The change has been successfully run locally.
* [x] Add tests to cover the changes added in this PR.
* [x] Add before and after screenshots (Only for changes that impact the UI).

Once you have met the above requirements please replace this section with
a `Fixes #ISSUENUM` linking to the issue fixed by this PR along with an
explanation of the changes. Thanks for your contribution!

### CODE REVIEW

**Comment by Patil2099** [comment]
> Please use backticks (`) instead of single quotes ('). No need to open a new pull request every time you make a correction, you can just push new commits to this branch.

When I replaced single quotes with backticks none of the tests passed. The code to remove the column was perfectly fine I don't know why it is failing integration test. Can you help me please @diox?

**Comment by diox** [comment]
The failures are intermittent/not related. It wasn't working before changing to backticks FWIW, it's just that the tests are covering migrations.

**Comment by caitmuenster** [comment]
Thanks for the patch, @Patil2099! 🎉 Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition). 

Would you be interested in creating an account on mozillians.org? I'd be happy to vouch for you!

**Comment by Patil2099** [comment]
Thank you so much for adding me to the Recognition Wiki. You are one of the most generous people I have seen as you are the head yet you are E-mailing everyone who contributes. If anyone deserves thanks, it's you and Mathieu Pillard. My username is written wrong in Recognition Wiki Page its Patil2099 not Patil2009. Can you Please get it fixed as it's my first contribution I want to take a screenshot with the correct name on it.
I want to contribute and give back to the community as much as I can. And I've always loved Mozilla so that's why I start from here and I will continue to contribute more to Mozilla I will give my best so that Mozilla grows to its maximum extent.
I just created my Mozillians.org
This is my Username-pankaj.patil2099
Thanks for giving me a chance.😀

________________________________

**Comment by caitmuenster** [comment]
Sorry about that, @Patil2099! I just updated the recognition wiki & vouched for your Mozillians profile. 

Welcome onboard! We look forward to seeing you around the project. ✨

**Comment by Patil2099** [comment]
Sure, you will see me working around here, a lot!

Thank you, again.
@caitmuenster

**Pull request merged**
