### PR TITLE
wip, do not merge

### LINKED ISSUE #3329: Create stats in populate_db
It looks like we don't create an stats when we populate the db, which makes it hard to test things like #3326. It would be nice if we did.

I noticed though that the addons_stats index is not created so we'd need to make sure that's created and then populate it.

### PR DESCRIPTION
**Pull request by andymckay**
* currently getting tripped up by:

```
23:35:05 z.es:ERROR Elasticsearch error: TransportError(404, u'IndexMissingException[[addons_stats] missing]') :/code/src/olympia/search/middleware.py:15
```

* although:

```
[root@7834839246cb code]# curl elasticsearch:9200/_cat/indices?v
health status index                       pri rep docs.count docs.deleted store.size pri.store.size 
green  open   addons-20160823233704         5   0        110            0    177.6kb        177.6kb 
green  open   addons-20160823233633         5   0        110            0    177.6kb        177.6kb 
green  open   addons_stats-20160823233633   5   0          0            0       720b           720b 
green  open   addons-20160823231400         5   0        110            0    190.4kb        190.4kb 
green  open   addons_stats-20160823231400   5   0          0            0       720b           720b 
````

* might just fix #3329

### CODE REVIEW

**Comment by andymckay** [comment]
Any advice on the index @diox?

**Comment by diox** [comment]
Weird. There is a second reindex call that you need to patch to add a `--with-stats` in that `Makefile` (the first one merely creates the empty indexes). Can you try adding it ?

Though the alias should already exists. Maybe the indexing part is failing ? Anything in the logs ?

**Comment by andymckay** [comment]
You are right, I was altering the wrong one, but I ran: `python manage.py reindex --force --noinput --with-stats` manually at the command line to see what was going on. Because `reindex` was taking an hour I killed it and checked the indices existed, which they do.

`index_stats` exits with no error I think that was the problem?

Calling `index_download_counts` explicitly seems to have worked:

```
[root@7834839246cb code]# curl elasticsearch:9200/_cat/indices?v
health status index                       pri rep docs.count docs.deleted store.size pri.store.size 
green  open   addons-20160823235943         5   0        110            0    177.6kb        177.6kb 
green  open   addons-20160823233704         5   0        110            0    177.6kb        177.6kb 
yellow open   addons_stats                  5   1         10            0     16.7kb         16.7kb 
green  open   addons-20160823233633         5   0        110            0    177.9kb        177.9kb 
green  open   addons_stats-20160823233633   5   0          0            0       720b           720b 
green  open   addons_stats-20160823235943   5   0          0            0       720b           720b 
green  open   addons-20160823231400         5   0        110            0    190.9kb        190.9kb 
green  open   addons_stats-20160823231400   5   0          0            0       720b           720b 
```
addons_stats is there and yellow

http://olympia.dev/en-US/firefox/addon/tibia-online-status/statistics/downloads-day-20160724-20160823.json

This is now failing with:

```nested: ElasticsearchException[Unable to find a field mapper for field [boost]]; }]```

I'll see if I can dig into that tomorrow.

**Comment by diox** [comment]
That's bad: `addons_stats` should not be in there, it should be an alias, not an index. That's probably why you've got the failure below, the indexes weren't set properly, it was just auto-created when you ran the `index_stats` or `index_downloads_counts` manually.

If `reindex` is failing it must be fixed, it's the only proper command to create the indices and aliases (and if you already have an indice instead of an alias, you must use `--wipe` to get rid of it, or manually delete it - otherwise it will lead to more reindexing failures)

**Comment by andymckay** [comment]
Haha. Lies!

**Pull request closed without merging**
