### PR TITLE
add the cdn to CSP connect-src

### LINKED ISSUE #9539: Theme wizard should preload latest version properties when uploading new version
STR:

1) Create a theme
2) In the Dev Hub, click on Upload New Version.
3) Click on Create a Theme button.

Expected:
The properties of the current theme version should be preloaded, so they are easy to edit. Currently, the wizard is in its default state.

This won't work very well if the previous version was uploaded as an XPI and included properties that the wizard doesn't support. It's an edge case, however, and maybe we can show a warning on the wizard page explaining that those properties will be reset (or kept?).

### PR DESCRIPTION
**Pull request by eviljeff**
fixes #9539

### CODE REVIEW

**Comment by eviljeff** [comment]
I'm not sure I entirely agree with the fail: https://travis-ci.org/mozilla/addons-server/jobs/442801505#L2894 
- if we add the prod cdn to `CSP_CONNECT_SRC` in `settings_base.py` then a) dev and stage get it included as well (probably harmless, but unnecessary) and b) it doesn't actually help test the prod csp locally because we don't use a separate domain to serve the content.

**Comment by eviljeff** [comment]
@muffinresearch https://github.com/mozilla/addons-server/blob/master/src/olympia/amo/tests/test_csp_headers.py#L117 is apparently your early handiwork.  Should it be removed now?

**Comment by muffinresearch** [comment]
> @muffinresearch https://github.com/mozilla/addons-server/blob/master/src/olympia/amo/tests/test_csp_headers.py#L117 is apparently your early handiwork. Should it be removed now?

Possibly, but you'd need to refactor *al*l the CSP tests to be based on production's config because all the tests are based on the base_settings and that's why production overrides are explicitly prevented by that test.

**Comment by muffinresearch** [comment]
> dev and stage get it included as well (probably harmless, but unnecessary) and 

Isn't that only true if you append and don't override?

**Comment by eviljeff** [comment]
> Isn't that only true if you append and don't override?

All the CSP settings in dev and stage confs are written with appends, but yeah, they could be changed to just override.

**Pull request merged**
