### PR TITLE
Override Download button underline

### PR DESCRIPTION
**Pull request by gamebusterz**
Removed the underline from the Download button #2247

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
Thanks a lot for the patch @gamebusterz! This looks good so far, could you maybe add before / after screenshots to simplify the work of our QA to ensure it looks the way it's supposed to?

**Comment by gamebusterz** [comment]
@EnTeQuAk I am facing some problem while doing that. I have olympia.dev up and running, and when I go to Other Applications  > Android and search for 'Comics.com Search' , I get no matching results. Also, another thing I noticed was that the url of the page where the bug was pointed out was 'allizom` and searching on `http://olympia.dev/en-US/android` I found no matching results to 'Comics.com Search'. Is there something I'm missing ?

**Comment by EnTeQuAk** [comment]
Sorry @gamebusterz for the late reply but holidays and new years eve came in between.

You will have to setup an add-on on your local machine or create a bunch of it by running `make initialize_docker`:  https://addons-server.readthedocs.io/en/latest/topics/install/docker.html#setting-up-the-containers

Otherwise, if you can apply your changes on the live-page by hooking into the developer tools and make a screenshot of that it'll be fine too. It's a rather small change.

**Comment by gamebusterz** [comment]
Before  
before  

After
after

**Comment by EnTeQuAk** [comment]
Perfect, thanks a lot for adding the screenshots!

**Comment by caitmuenster** [comment]
Thanks, @gamebusterz! Your contribution has been added to our [Recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition#January_2017). 

Welcome onboard! We're happy to have you on the team.

**Comment by gamebusterz** [comment]
Thank you @caitmuenster , @EnTeQuAk and @eviljeff for being so supportive and welcoming. Would love to keep making my contributions bigger and more significant. Thank you :)

**Pull request merged**
