### PR TITLE
Allow URLs in developer replies to ratings

### PR DESCRIPTION
**Pull request by diox**
Fixes https://github.com/mozilla/addons/issues/15069

### CODE REVIEW

**Comment by KevinMind** [comment]
Can you add some testing steps?

**Review by KevinMind — APPROVED** [review]
Looks good. FWIW I could add `www.google.com` but not `https://www.google.com` Probably difficult to get lower level that protocol checking but wanted to shout.

**Comment by KevinMind** [comment]
I was able to review with `www.google.com` but not `https://www.google.com`

Screenshot 2024-10-16 at 17 36 07

I could reply even with https...

Screenshot 2024-10-16 at 17 39 06

**Comment by diox** [comment]
Yeah we're not trying to detect things that may look like an URL - we used to, when we were transforming them into links automatically, but we don't anymore so really the check is just to add an extra layer to keep our ratings as clean as possible.

when we were doing that detection it was very prone to errors. There are some many TLDs these days that it's too messy.

**Pull request merged**
