### PR TITLE
Update - Updates Link

### PR DESCRIPTION
**Pull request by NegiAkash890**
* [x] This PR relates to an existing open issue and there are no existing
      PRs open for the same issue.
* [x] The change has been successfully run locally.

Updates were made at `olympia • src\olympia\devhub\templates\devhub\includes\source_form_field.html`
This fixes a section of #16753.

### CODE REVIEW

**Comment by eviljeff** [comment]
In the issue some of the extensionworkshop links had trailing slashes in the wrong place (or were missing) - please update.  Also, see my comment https://github.com/mozilla/addons-server/issues/16753#issuecomment-801293403 about using the setting.

**Comment by NegiAkash890** [comment]
> see my comment [#16791 (comment)](https://github.com/mozilla/addons-server/pull/16791#issuecomment-804787987) the URLs were updated in the issue

Hi @eviljeff, I referred to your comment `#16791` which leads to issue #16753 where you mentioned replacing instances of 
` https://extensionworkshop.com` with `settings.EXTENSION_WORKSHOP_URL` in the links. So, the changes that I made were asked and by `@caitmuenster` in issue #16753 for targeting links to extension workshop instead of developer Mozilla pages. Please correct me if I am missing something  and I am having difficulty in understanding the changes you are asking for.

**Comment by eviljeff** [comment]
> 
> 
> > see my comment [#16791 (comment)](https://github.com/mozilla/addons-server/pull/16791#issuecomment-804787987) the URLs were updated in the issue
> 
> Hi @eviljeff, I referred to your comment `#16791` which leads to issue #16753 where you mentioned replacing instances of
> ` https://extensionworkshop.com` with `settings.EXTENSION_WORKSHOP_URL` in the links. So, the changes that I made were asked and by `@caitmuenster` in issue #16753 for targeting links to extension workshop instead of developer Mozilla pages. Please correct me if I am missing something and I am having difficulty in understanding the changes you are asking for.

I meant "In the issue some of the extensionworkshop links had trailing slashes in the wrong place (or were missing) - please update." - the changes are subtle, but the filepaths _must_ end in `/`, with the url parameters after the `/`, or the website does a redirect and loses the UTM parameters we're trying to capture.

**Comment by caitmuenster** [comment]
Hey @NegiAkash890! Just wanted to check in on this -- this is really close to being finished; would you be able to make those last changes @eviljeff requested? Thanks for your contribution to this issue!

**Comment by eviljeff** [comment]
closing this for now as it's been 3 weeks.  Please open a new pull request when changes are ready.

**Pull request closed without merging**
