### PR TITLE
Increase default caching duration for services.a.m.o. API requests

### LINKED ISSUE #21628: Increase cache duration for services.a.m.o. API requests
Currently, all `GET` non-authenticated API requests default to being cached by the CDN for 180 seconds (with some specific endpoints having a custom higher value). The value was chosen arbitrarily to keep data fresh while still providing enough caching to reduce infrastructure costs.

We'd like to increase that cache duration for API requests on `services.addons.mozilla.org` domain (and `services.addons-dev.allizom.org`, `services.addons-dev.allizom.org`), which serves requests for Firefox. That domain receives a lot of traffic but the freshness of the data for those requests doesn't seem as important.

The main impact would be that information that Firefox pulls from the API to show in about:addons (notably number of ratings, average score) would be slightly less up to date.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-634)

### PR DESCRIPTION
**Pull request by diox**
Fixes #21628

### CODE REVIEW

**Review by KevinMind — APPROVED** [review]
LGTM. 🚢 

I didn't test, as I assume it would be somewhat difficult? I suppose you could curl locally and modify the server name? Did you try doing this?

Nit: It would be nice if the PR could include some information about what a reviewer should be looking for, how to test, or that it should/can not be tested etc.

**Comment by diox** [comment]
It is annoying to test locally, yeah: we don't have a different host set up locally for services, everything just uses the same host. I did test it by manually setting `uwsgi_param   SERVER_NAME           olympia.test;` in the `@olympia` location of https://github.com/mozilla/addons-server/blob/master/docker/nginx/addons.conf ; since `settings.SERVICES_DOMAIN` locally is `olympia.test`, that forces all requests to be considered as "services" requests using that snippet of code I use.

**Comment by diox** [comment]
I stole that snippet from existing code but looking at how we define `SERVER_NAME` in dev/stage/prod I am not 100% sure it'll work, as we also have some internal server names to consider sometimes... I'll double-check.

**Comment by diox** [comment]
I pushed https://github.com/mozilla/addons-server/pull/21656 which sadly confirms what I suspected: at the moment, `SERVER_NAME` is not reliable for this.

We'll have to ask SRE to inject some environment variable to reliably detect that the container is a services one.

**Comment by diox** [comment]
https://mozilla-hub.atlassian.net/browse/SVCSE-1676 would fix that.

**Comment by KevinMind** [comment]
Just out of curiosity, have you inspected the headers we actually get from firefox to see if there is some unique value that could be relied on?

Even bolder question, could we ask them to send such a header?

x-cache-ttl or something like that? Could let them determine how fresh they want the data.

I didn't suggest it at first as your solution seemed very simple, but it doesn't seem so anymore. Just a though. I don't have a strong opinion on this.

**Comment by diox** [comment]
Firefox doesn't send any particular headers that would help distinguish that from any other request made to AMO, besides the `Host` header. We could use `request.get_host()`, but I'm not sure we wouldn't run into the same issue.

I would prefer not depending on an extra header, cause then it would also make things more complex as it would need to enter the cache key. We could add a magic query string key (since the full query string is always part of the cache key) but that seems fragile, and we'd still need to ask Firefox to use it, wait for that to ride the trains etc.

Ultimately waiting for SRE to fix `SERVER_NAME` is valuable anyway, if only for consistency (on other domains, like the main a.m.o. one, it's already correct).

**Comment by diox** [comment]
Wei unblocked this on dev:

```
% curl -s https://addons-dev.allizom.org/api/v5/services/client_info | jq .SERVER_NAME
"addons-dev.allizom.org"

% curl -s https://services.addons-dev.allizom.org/api/v5/services/client_info | jq .SERVER_NAME
"services.addons-dev.allizom.org"
```

**Pull request merged**
