### PR TITLE
Speed up LanguageTools API by cutting out current_version from response

### PR DESCRIPTION
**Pull request by eviljeff**
part of #6850 - though possibly not the whole "fix"

### CODE REVIEW

**Comment by diox** [comment]
Have you asked frontend people if that was ok with them ?

**Comment by diox** [comment]
Docs need to be updated

**Comment by eviljeff** [comment]
mmm, #yolo?

**Comment by eviljeff** [comment]
@kumar303 @tofumatt you okay with this to drastically reduce the amount of data returned in the API (and the associated multiple-joins needed to get that data)?

**Comment by tofumatt** [comment]
I'll look at this... I think we might need it in the response to render the language tools page, but I'm checking now.

**Comment by eviljeff** [comment]
docs https://github.com/mozilla/addons-server/pull/7403/commits/bb59d7419959b133ed573bc02bc4f51187ad27c8

**Pull request merged**
