### PR TITLE
Fixed deprecated warning issue due to FixedOffset

### PR DESCRIPTION
**Pull request by ManishAradwad**
Fixes: #13690 

Changed `FixedOffset(commit.commit_time_offset)` to `datetime.timezone`

* [x] This PR relates to an existing open issue and there are no existing
      PRs open for the same issue.
* [x] Add `Fixes #ISSUENUM` at the top of your PR.
* [x] Add a description of the changes introduced in this PR.

### CODE REVIEW

**Comment by ManishAradwad** [comment]
How can I run the tests locally?

**Comment by eviljeff** [comment]
> How can I run the tests locally?

https://addons-server.readthedocs.io/en/latest/topics/install/docker.html#running-common-commands

**Comment by ManishAradwad** [comment]
@diox The build was passing when I made the changes on my fork: [link to build](https://travis-ci.com/github/ManishAradwad/addons-server/jobs/320496081#L4407), but it's failing here. Its failing the `test_commands.py` tests. Can you plz guide me on this?
Screenshot from 2020-04-17 22-01-23

**Comment by diox** [comment]
This is likely due to https://github.com/mozilla/addons-server/issues/13999 which has been failing intermittently for a couple of weeks, and can be ignored. I've restarted the build just in case.

**Pull request merged**
