### PR TITLE
Darken footer colour in restyle (close #1826)

### LINKED ISSUE #1826: Change redesigned footer text from blue to black
I find the contrast of the blue footer text in the redesign, especially next to the blue links in it, to be quite low. I think we should go to a darker colour.

### PR DESCRIPTION
**Pull request by tofumatt**
@pwalm / @designakt, what do you think of the darker colour here?

### Original
screenshot 2016-03-03 07 59 36

### Dark
screenshot 2016-03-03 07 59 28

### CODE REVIEW

**Comment by wagnerand** [comment]
Somehow, I can't see a difference.

**Comment by tofumatt** [comment]
The "Except where otherwise noted [...]" text is blue in the first screenshot, black in the second one.

**Comment by wagnerand** [comment]
Ah, thanks. The blue-on-blue in the "get to know add-ons" bar was distracting me.

**Comment by muffinresearch** [comment]
Spinning this up and trying it in situ I think #333 is too dark (imho). #333 is in use for headings. The contrast difference draws the eye to the footer a little bit too much. Using the secondary color #666 which is already in use in the page for sub headings looks a little bit less dramatic. What do you think? 

add-ons_for_firefox_and____security_bug_reports

**Comment by tofumatt** [comment]
I like the `#666` actually, good call.

**Comment by pwalm** [comment]
Seconded on the #666, nice balance.

**Comment by muffinresearch** [comment]
r+ :shipit:

**Pull request merged**
