### PR TITLE
Remove old inline version/file upload flow

### LINKED ISSUE #4076: remove and cleanup step-version-upload waffle
part of #3465
When step-version-upload waffle is live on prod we can remove the old inline new file/version upload methods and templates.

### PR DESCRIPTION
**Pull request by eviljeff**
Remove all the lines!  

This will fix #4076 but should only be merged after the waffle has been enabled on prod and QA/Product have confirmed everything is okay.

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
I'm guessing getting that approval is only possible in January hu?

**Comment by eviljeff** [comment]
Yeah a decision was made during the ww to wait until January.

**Comment by EnTeQuAk** [comment]
This now needs a rebase with master since there are conflicts.

**Comment by eviljeff** [comment]
Rebased.  Though given how much code is changed it will likely need another before merge.

**Pull request merged**
