### PR TITLE
Hard-codes the en-US locale in all links to MDN

### LINKED ISSUE #5897: Hard-code locale in links to MDN
Follow-up on https://github.com/mozilla/addons-server/pull/5890#issuecomment-314840612

Since there is no locale fall-back on MDN, we want to make sure all users see up to date docs, or even any docs at all, in case the MDN page does not exist in the user's locale.

We should hard-code the `en-US` locale in all links to MDN.

### PR DESCRIPTION
**Pull request by apoorvaeternity**
Fixes #5897

### CODE REVIEW

**Comment by diox** [comment]
Let's not merge until the discussion in the issue has been resolved.

**Comment by apoorvaeternity** [comment]
@wagnerand I have made changes in just the templates. Do I have to make this change in other files as well like views, tests, .po and .mo files?

**Comment by EnTeQuAk** [comment]
> @wagnerand I have made changes in just the templates. Do I have to make this change in other files as well like views, tests, .po and .mo files?

No, this looks great so far. .po files get extracted on a regular basis and there don't seem to be any tests failing so 👍

**Comment by wagnerand** [comment]
@apoorvaeternity Thank you!

I see a couple of more instances:
```
src/olympia/amo/templates/amo/developer_agreement.html:57
src/olympia/amo/templates/amo/developer_agreement.html:87
src/olympia/amo/templates/amo/developer_agreement.html:116
src/olympia/devhub/templates/devhub/new-landing/components/overview.html:5
src/olympia/devhub/templates/devhub/search.html:1
src/olympia/devhub/views.py:69:MDN_BASE
static/js/common/upload-addon.js:459
```

**Pull request merged**
