### PR TITLE
Create Advanced Admins groups, require Admin:Advanced permission to delete collections

### LINKED ISSUE #7249: Create `Admin:Advanced` permission for Advanced Admins
Part of #7176.

Create an `Admin:Advanced` permission, which will be used to gate Advanced Admin tools (per the [PRD](https://docs.google.com/document/d/1ts_1IB3hXcTvEX0gclN55NsBVs7r1duBOM9zQaqSyhE/edit)). ~~Assign this permission to the `System Administrators` groups, which will be used to determine who are Full Admins.~~

### PR DESCRIPTION
**Pull request by diox**
Fix #7249

### CODE REVIEW

**Comment by eviljeff** [comment]
What's the reasoning behind this change?  (the issue is about adding the permission mainly).  I don't see why you can change a collection with `COLLECTIONS_EDIT` but now need `ADMIN_ADVANCED` to delete it.  And that these permissions are different than the API permission needed for editing Mozilla collections (`ADMIN_CURATION`).

Scott is going to need 3 separate permissions to be able to do something like 1) create a collection and assign it to Mozilla 2) add addons to that collection 3) delete it again at the end of the month or whatever.

My "technical debt" senses are tingling 😟

**Comment by diox** [comment]
I was trying to follow [the PRD](https://docs.google.com/document/d/1ts_1IB3hXcTvEX0gclN55NsBVs7r1duBOM9zQaqSyhE/edit#heading=h.i2x8n5tlf38q) while staying close to what we already have for other admin tools. In the PRD, `Collections:Edit` doesn't even exist and both edit and delete are only available for `Admin:Advanced` users. We already have `Users:Edit` for user admin with deletion reserved to `Admin:Advanced`, so it made sense to me to follow that.

We certainly do **not** want to give Scott `Admin:Advanced`, it would defeat the purpose. Does he really need to delete mozilla collections ? Having this kind of power kinda scares me, since those collections are used on the homepage.

**Comment by eviljeff** [comment]
That scenario I mentioned is exactly what he was trying to do a few days ago (except the delete part for now, until the period he's intended to have the collection up for is over).  I don't think the PRD took into account the features we were dropping for collections and how that would affect how the django admin pages would be used, and by who.  The new permission structure for Collections we really only dreamed up a few weeks ago.

IMO, just `ADMIN_CURATION` should be enough for someone to make _any_ changes regarding Mozilla collections (including edit and delete).   A single permission for a single role.  

Lets see what @jvillalobos thinks though.

**Comment by eviljeff** [comment]
I had a thought.  The (official) workaround could be that Scott would have to transfer ownership of the collection back to himself before it could be deleted via the frontend.

**Comment by diox** [comment]
`Admin:Curation` lets you edit editorial content - so you get access to replacement add-ons and editing mozilla collections.
`Collections:Edit` is an older permission meant for admins, letting you edit *any* collection on the site.

**Pull request merged**
