### PR TITLE
Drop deprecated index_name property from our ES mapping

### PR DESCRIPTION
**Pull request by diox**
This is necessary to switch to ES 2.x. Fortunately, while the old mapping is active both variants are accepted, so the new code should be backwards-compatible with the old mapping while we reindex.

Supports #2850 but I expect to have more modifications to make before we can upgrade...

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
r+

**Comment by diox** [comment]
Not going to merge this yet because  tests passed even though there was an issue with a `facets` query, so I want to investigate more.

**Comment by EnTeQuAk** [comment]
oh, alright. r- then :laughing:

**Comment by diox** [comment]
#2887 deals with this and more.

**Pull request closed without merging**
