### PR TITLE
Refresh site balloon style (fix #2140)

### LINKED ISSUE #2140: refresh site welcome message
First time AMO users will see this message. We should refresh its design to work with the new design.
New yours will also be people redirected to AMO from disco pane.
screen shot 2016-03-29 at 17 12 05

@pwalm how do you think we should do that?

### PR DESCRIPTION
**Pull request by tofumatt**
New site balloons in action, styled as per UX's instructions:

apr 04 2016 17 58

The GIF messes with the colours a bit, so here's a screenshot too:

screenshot 2016-04-04 18 01 24

### CODE REVIEW

**Comment by tofumatt** [comment]
@pwalm These look okay, yes?

**Comment by EnTeQuAk** [comment]
Code wise, r+ - let's see what UX says :)

**Comment by tofumatt** [comment]
Or @designakt, approval from either of you will do :wink:

**Comment by pwalm** [comment]
Approved! Sorry guys, was travelling today.

**Comment by tofumatt** [comment]
No worries, thanks! :-)

**Pull request merged**
