### PR TITLE
Add annotations to indicate forms that dont need CSRF tokens

### PR DESCRIPTION
**Pull request by psiinon**
For more details see [BUG 1328560](https://bugzilla.mozilla.org/show_bug.cgi?id=1328560)
Note that this isnt the full set of forms that dont appear to have anti CSRF tokens - see the above bug for a list of the ones I wasnt sure about.
I've not included any test for these changes as they will be tested for via the baseline scan as per an irc chat with @muffinresearch 
First PR on this repo, hope I havnt done anything too bad ;)

### CODE REVIEW

**Comment by diox** [comment]
I'd argue that some of these do appear to be needing CSRF protection... OTOH, anything using `method=get` is probably fine by definition.

**Comment by psiinon** [comment]
@diox whats the best way to progress this?
I can go through the files again and add `{{ csrf() }}` to any forms that look like they need them - is that all thats needed or are related code changes required?

**Comment by diox** [comment]
More investigation would be required to understand why these forms allow POSTs without csrf and fix them - just adding the csrf token to the forum would silence the warnings, but we wouldn't know if some forms are vulnerable or not...

**Comment by psiinon** [comment]
As per discussion on irc I'll investigate and see if I can usefully abuse any of them.

**Comment by psiinon** [comment]
I've removed the 'collection_favorite.html' change as that's not such a clear cut case. However I did have a good play with the UI for both of the POST forms and wasnt able to abuse them in any way - a "X-CSRFToken" header is being added and if thats removed it results in an error.

**Comment by psiinon** [comment]
I have no idea why the Travis build is now failing - it passed before and all I did was remove one of the changes :/ Could it be a glitch?
Also, what do I need to do in order for this PR to be deemed acceptable to merge? :)

**Comment by diox** [comment]
It's an intermittent failure, I've restarted the job. I'll review the PR shortly.

**Comment by psiinon** [comment]
Thanks :)

**Pull request merged**
