### PR TITLE
Fix makefile command for creating data.

### LINKED ISSUE #10999: Make initialize_docker fails
### Describe the problem and steps to reproduce it:
I followed guide that is install docs. When I executing command `Make initialize_docker`, It occurred Error.

### What happened?
```
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/code/src/olympia/landfill/management/commands/generate_default_addons_for_frontend.py", line 77, in handle
    serializer = GenerateAddonsSerializer()
  File "/code/src/olympia/landfill/serializers.py", line 45, in __init__
    self.fxa_email = os.environ['UITEST_FXA_EMAIL']
  File "/usr/local/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'UITEST_FXA_EMAIL'
Makefile-docker:97: recipe for target 'populate_data' failed
make: *** [populate_data] Error 1
Makefile-os:57: recipe for target 'initialize_docker' failed
make: *** [initialize_docker] Error 2

```

### What did you expect to happen?
Success make and run server.

### Anything else we should know?
Additionally, I searched keyword **UITEST_FXA_EMAIL**. I found issue that #10888. So I return commit(`git checkout 7f7c8dd`) before this issue. I succeeded `Make initialize_docker` and I can access http://olympia.test.

### PR DESCRIPTION
**Pull request by jrbenny35**
Fixes #10999

### CODE REVIEW

**Comment by jrbenny35** [comment]
@kumar303 mind trying this out?

**Comment by junngo** [comment]
I succeed in executing command(`Make initialize_docker`) through this PR :)

**Comment by jrbenny35** [comment]
> I succeed in executing command(Make initialize_docker) through this PR :)

Then it shall me merged!

**Comment by kumar303** [comment]
Thanks for the fix!

**Pull request merged**
