### PR TITLE
Update kombu to 3.0.30 to avoid running into celery/kombu#545

### PR DESCRIPTION
**Pull request by EnTeQuAk**
This is required for Python 2.7.11 compatibility.

### CODE REVIEW

**Comment by diox** [comment]
No love for 3.0.33 ? Would require to bump `amqp` too but that's probably a good thing.

**Comment by EnTeQuAk** [comment]
3.0.30 looks better :smile: but good point actually, didn't want to bump too far but let me update the whole stack around kombu while we're at it.

**Comment by diox** [comment]
celery 3.1.20 and billiard 3.3.0.22 look like good candidates as well if you are going down that path.

**Comment by diox** [comment]
(Travis failures are because pyrepo hasn't been updated yet)

**Comment by EnTeQuAk** [comment]
Updated the full-stack, ready for re-review

**Comment by diox** [comment]
r+ this looks good. I'd like jason's view on this before merging though, since we're not in a super stable situation with celery to begin with.

**Comment by EnTeQuAk** [comment]
@jasonthomas mind taking a quick look at this?

**Comment by jasonthomas** [comment]
I went through the change log for each and didn't see anything unusual. r+

**Comment by EnTeQuAk** [comment]
Thanks for the reviews!

**Pull request merged**
