### PR TITLE
Fixes Issue Number #2179 Dangling tabs in My Submission Page 

### PR DESCRIPTION
**Pull request by LordGameleo**
Fixes Issue Number #2179 Dangling tabs in My Submission Page by modifying /static/css/devhub/dashboard.less

[https://github.com/mozilla/addons-server/issues/2179](url)

Before:
pr_tab_1
______________________________________________________________________________________
After:
pr_tab_2

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
Personally, I think "My Add-ons" and "My Themes" should have less of a margin towards the "Sort by" :thinking:

**Comment by kumar303** [comment]
I like the solution proposed in issue https://github.com/mozilla/addons-server/issues/2179 's description: render a tab for the selected item but not the others. Did you try it? The example was https://images.duckduckgo.com/iu/?u=http%3A%2F%2F4.bp.blogspot.com%2F-UQZC6q3pNKo%2FUiZ7ZyFVWTI%2FAAAAAAAAFLY%2FP34Yjwyv2aA%2Fs1600%2Fajaxcssstyletabcontainer.gif&f=1

**Comment by LordGameleo** [comment]
@EnTeQuAk check this once. 
pr_tab_less
And about different languages, it won't be an issue now as we are using them as links rather than tabs.

**Comment by LordGameleo** [comment]
Or?
pr_tab_less2

**Comment by LordGameleo** [comment]
@EnTeQuAk do I need to worry about the check failed? I didn't touch any other file except the dashboard.less

**Comment by LordGameleo** [comment]
@EnTeQuAk .... just to remind of this PR.

**Comment by EnTeQuAk** [comment]
Hmm, looking at this more closely, I still feel like "My Add-ons" and "My Themes" should have less margin to the links below it.

Also…

screenshot from 2018-09-24 07-50-21

Maybe that's because of bold vs non-bold but it seems the font-sizes are different when selected, that looks quite weird to me.

Do you have the time to look at that?

**Comment by LordGameleo** [comment]
@EnTeQuAk  I will surely look into it.

**Comment by LordGameleo** [comment]
@EnTeQuAk  The following screenshot is when I removed the bold from active link.

font_check

**Comment by LordGameleo** [comment]
@EnTeQuAk check this version...

final_font_size

**Comment by EnTeQuAk** [comment]
That's much more reasonable, nice! Can you also reduce the margin between "My Add-ons / My Themes" and the links below ("Sort by ..." etc) a bit? 

The version in https://user-images.githubusercontent.com/40512667/45252432-b12e1b80-b373-11e8-91c5-662ba5ac69af.png looked good from the margin point of view.

**Comment by LordGameleo** [comment]
@EnTeQuAk  check if this satisfies the requirement
final_to_show

**Comment by pwalm** [comment]
To make it clearer, let’s make the selected/current view text #0C0C0D instead of orange. Leave the links blue. The floating text part doesn’t bother me too much, it’s more important to know what page you’re on.

**Comment by LordGameleo** [comment]
@pwalm should I change the text color to one you specified?

**Comment by EnTeQuAk** [comment]
@LordGameleo only for the active link, yes.

**Comment by LordGameleo** [comment]
@EnTeQuAk @pwalm  check this one
change_active_color

**Comment by pwalm** [comment]
@LordGameleo Yes, sort should have the same style applied as well.

**Comment by EnTeQuAk** [comment]
I looked into changing the "Sort by"colours as well, it's certainly doable but the colour will also change for other listing pages. But from what I can tell all these pages are served by addons-frontend now anyway so it should be safe to change it as well.

@LordGameleo do you have the time to look at this as well?

**Comment by LordGameleo** [comment]
@EnTeQuAk I will do it in sometime. I am having exams right now. I will do it after that. I hope this is fine by you.

**Comment by EnTeQuAk** [comment]
Sure thing. I'm going to close this pull request for the time being then but feel very free to re-open at any time!

Looking forward to seeing more of you.

**Comment by LordGameleo** [comment]
@EnTeQuAk @pwalm  when I was doing this I hit an unexpected error. I changed the dashboard.less file and saved it. But when I refreshed the page this came up.
screenshot from 2018-10-15 17-37-26
I can't figure it out. Let me know if you can help.

**Comment by LordGameleo** [comment]
It is fixed now. It looks like this now is it fine now? @pwalm @EnTeQuAk 

screenshot from 2018-10-15 22-11-30

**Pull request closed without merging**
