### PR TITLE
Correct DistributionChoiceForm choice labels

### LINKED ISSUE #3828: Correct label translation workaround from #3827
We had to implement a workaround in https://github.com/mozilla/addons-server/pull/3827/ so that we could fix random language hopping without breaking already translated strings.

Let's fix this, make it all one big string and let translators do their thing for before the next tag to make the code clean again.

### PR DESCRIPTION
**Pull request by EnTeQuAk**
Fixes #3828 

Sorry for this huge PR but the change needed a new extraction and compilation for the tests to work again. I also updated the German translation which is used in the tests, all others still have to be translated.

### CODE REVIEW

**Comment by eviljeff** [comment]
you've taken out the mark_safe - does the html still show up correctly on the page?

**Comment by eviljeff** [comment]
Also, https://github.com/mozilla/addons-server/commit/95de533a02f55a708d23e047242be008dee44355 tried to do this but it didn't work on prod, leading to the current implementation.  What are you doing differently?

**Comment by EnTeQuAk** [comment]
I re-added `mark_safe_lazy`, sorry, I forgot to push that commit.
> Also, 95de533 tried to do this but it didn't work on prod, leading to the current implementation. What are you doing differently?

The major difference here is that I'm now marking the whole string as translatable. The problem with 95de533 was that you substituted the translatable-strings into a non-translatable string which resulted in a non-translatable string. Now that the whole label is translatable the laziness is kept and translators gain more freedom for translations.

**Comment by eviljeff** [comment]
Any chance it can be done like https://github.com/eviljeff/olympia/commit/5d3fbd14038047b32c69bdfaf81d0d2c16b9751a#diff-21fa9ae78bf8e9d0f4785f2a6bc5c305R854 ?

**Comment by EnTeQuAk** [comment]
Not sure I follow what you mean.

Sure, it can be done like that but we'd loose freedom for translators. And I don't see the reasoning behind that if-statement when we can just put the lazy-translatable-string into the label itself

**Comment by eviljeff** [comment]
r+

**Comment by EnTeQuAk** [comment]
I agree but that's not easy to fix and imho requires more thinking and experimenting which is out of scope of this bug imho.

Besides all the possible dangers I'm not a huge fan of those tag substitutions and would argue that they give more context onto how the string or text is meant to be displayed and what it's all about. Maybe let's open another issue to have a more thorough discussion about it.

**Pull request merged**
