### PR TITLE
Fix unbroken strings

### LINKED ISSUE #8166: Unbroken strings in add-on name are causing layout issues on DevHub landing page
Split up from #6698 

STR:
1. Log in to Developer Hub - https://addons-dev.allizom.org/en-US/developers/
2. Submit a new add-on with a long unbroken name
3. After submission, go back to DevHub landing page

Actual result:
The addon name is not wrapped causing layout issues on the DevHub landing page

Expected result:
Unbroken add-on names should be wrapped on DevHub landing page

Notes
Reproduced on all AMO servers with FF59, Win10x64

image

### PR DESCRIPTION
**Pull request by iamkhush**
Fixes #8166 
* [X] This PR relates to an existing open issue and there are no existing
      PRs open for the same issue.
* [X] Add `Fixes #ISSUENUM` at the top of your PR.
* [X] Add a description of the the changes introduced in this PR.
* [X] The change has been successfully run locally.
* [X] Add before and after screenshots (Only for changes that impact the UI).

screenshot-2018-6-11 developer hub add-ons for firefox

Arabic locale `ar`
screenshot from 2018-06-15 12-02-55

### CODE REVIEW

**Comment by iamkhush** [comment]
Travis seems to fail due to some weird error. :confused:

**Comment by EnTeQuAk** [comment]
Thanks a lot for the update!

> Travis seems to fail due to some weird error. confused

That can luckily be ignored. The error will go away if you [rebase](https://help.github.com/articles/about-git-rebase/) your pull request with master since a fix for that error already landed.

One side-note, can you also post a screenshot that this works correctly for RTL languages e.g if you replace `en-US` in the URL by `ar` which will then switch to RTL mode.

Thanks a lot!

**Comment by iamkhush** [comment]
@EnTeQuAk Added screenshot for Arabic locale and rebased.

**Comment by EnTeQuAk** [comment]
Looks awesome! Thanks a lot for attaching the screenshot. I ran the tests locally, travis doesn't like us recently it seems.

Thanks a lot for your contribution!

**Pull request merged**
