### PR TITLE
Add new gotcha with elasticsearch and vm.max_map_count

### LINKED ISSUE #7123: ConnectionError during make initialize_docker (elasticsearch containter fails to start)
### Describe the problem and steps to reproduce it:

Set up a clean dev environment on a fresh OS:
1. Clone the repo
2. Install docker-compose
3. docker-compose up -d (elasticsearch starts, but soon fails)
4. Run `make initialize_docker` 

### What happened?

The script throws a ConnectionError when trying to connect to elasticsearch during `python manage.py reindex`

### What did you expect to happen?

The script should finish successfully.

### PR DESCRIPTION
**Pull request by mac-chaffee**
Fixes #7123

Ran into this issue when setting up my dev environment. Seems to be a common issue since the default max_map_count is too low: https://stackoverflow.com/a/11685165/4496684

### CODE REVIEW

**Comment by caitmuenster** [comment]
Thanks so much, @mac-chaffee! Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition#December_2017). 

Would you be interested in creating a profile on [mozillians.org](https://mozillians.org/)? I'd be happy to vouch for you. 

Welcome onboard! \o/

**Comment by mac-chaffee** [comment]
Sure, here's the link: https://mozillians.org/en-US/u/mac-chaffee/

**Comment by mac-chaffee** [comment]
I probably should have added @caitmuenster to my message. Here's my mozillians link: https://mozillians.org/en-US/u/mac-chaffee/

**Comment by caitmuenster** [comment]
Thank you! You're vouched. :)

**Pull request merged**
