### PR TITLE
always render preview svg in ltr to have symbols and url render correctly

### PR DESCRIPTION
**Pull request by eviljeff**
fixes mozilla/addons#649

### CODE REVIEW

**Comment by diox** [comment]
That's kinda cheating, but better than completely broken I guess

**Comment by eviljeff** [comment]
It's cheating but also realistic - that is what preview we'll generate and show to users (we don't generate a rtl variant as well as a ltr one).

**Comment by diox** [comment]
We probably should...

**Comment by eviljeff** [comment]
previously the direction from UX and @jvillalobos was to create a single l10n-neutral preview.  I don't know whether we want to go down the route of creating multiple preview .pngs (and if LTR/RTL would be the first variant anyway)

**Comment by jvillalobos** [comment]
Having an RTL variant is an interesting idea, but we would first need to look into how much RTL traffic we get to see if it's worth the complexity. We would also need to investigate whether static themes look the same on RTL versions of Firefox (particularly the background images), which could make the wizard and previews more complex.

I think it's worth filing a followup issue, but not a blocker.

**Pull request merged**
