### PR TITLE
Limit CORS on internal API and allow cookies

### LINKED ISSUE #2519: Update CORS for internal API endpoints
We need to update the CORS settings for the internal API endpoints. They should only be allowed from their matching addons-admin server, so https://addons-dev.allizom.org allows http://addons-admin.dev.mozaws.net (and http://localhost:3000 but only on dev).

Supports #2385.

### PR DESCRIPTION
**Pull request by mstriemer**
Fixes #2519.

### CODE REVIEW

**Comment by mstriemer** [comment]
This actually needs to support the internal search view, will update.

**Comment by mstriemer** [comment]
It seems like this should actually be a middleware instead. Unless there's something I'm missing it looks like [corsheaders]() only supports one configuration. So I guess I'll need to write a very similar middleware or update that to support multiple configurations (this sounds like more work than I was expecting). Perhaps there's something in django-rest-framework that I can hook into instead?

Any ideas @EnTeQuAk?

**Comment by EnTeQuAk** [comment]
hmm, there is nothing specific to django-rest-framework and you're right `corsheaders` only supports one configuration and not based on the origin.

Given the way `corsheaders` is written you'd essentially rewrite the whole thing to, say, support a separate config based on `HTTP_ORIGIN` or based on different endpoints.

The best way still would probably be to write a custom django-rest-framework renderer that patches in our custom headers… something like

```python
from rest_framework.renderers import JSONRenderer
from corsheaders.middleware import ACCESS_CONTROL_ALLOW_HEADERS

class InternalJSONRenderer(JSONRenderer):
    def render(self, data, accepted_media_type=None, renderer_context=None):
        render_context = render_context or {}
        response = render_context.get('response', None)
        if not response:
            return super(InternalJSONRenderer, self).render(data, accepted_media_type, renderer_context)

        response[ACCESS_CONTROL_ALLOW_HEADERS] = '....'
        return super(InternalJSONRenderer, self).render(data, accepted_media_type, renderer_context)
```

And then still make sure that `corsheaders` is disabled for our internal endpoints. I don't like duplicating this kind of work but forking `corsheaders` is even more work but maybe worth it. I'm undecided here.

**Comment by diox** [comment]
Alternate approach based on @EnTeQuAk idea, but without using a custom renderer:
- Build a mixin with a custom `finalize_response()` method or `default_response_headers` property that sets the CORS headers we need for the internal API
- Use that in the internal API views
- Disable `corsheaders` for `/api/v3/internal/` 

Although I don't know if either approach would still work with preflight stuff, or if we need to

**Comment by mstriemer** [comment]
@EnTeQuAk @diox I added some settings to this and updated django-cors-headers at https://github.com/mstriemer/django-cors-headers/pull/1. I thought I'd give updating django-cors-headers a try as to avoid two different CORS implementations.

Let me know how it looks, I'm open to changing things.

**Comment by EnTeQuAk** [comment]
I added some comments on the pr for `django-cors-headers` and I think I like the implementation.

lgtm

**Pull request merged**
