### PR TITLE
Implement Internal Search API (fix #1914)

### LINKED ISSUE #1914: Build admins-only internal search API
Tracker: #1744 

Once the base search API, serializer fields and authentication/permissions are in place, we can build the internal search API that will be limited to admins. It will have a specific URL prefix, probably `/api/v3/internal/`, to distinguish it from the rest.

This will require making a view inheriting from the regular `AddonSearchView` with some things tweaked - in particular, the filter backends will be different in order not to limit it to public add-ons, and obviously the permissions will be more restrictive.

Changes to the ES index and the indexation code will need to be made: Deleted add-ons (and maybe incomplete as well ?) need to be added to the ES index, and ignored in most of the queries we make. Currently they are completely removed from the index when deleted.

### PR DESCRIPTION
**Pull request by diox**

### CODE REVIEW

**Comment by eviljeff** [comment]
empty /internal/models.py file?

**Comment by diox** [comment]
Yeah, old habit that is probably no longer necessary with the new app loading mechanism in django. It used to be required for django to consider the app as a django app.

**Comment by andymckay** [comment]
Internal is the new admin :cake:

**Comment by diox** [comment]
I almost put the code in `zadmin`... Then I looked at what was already in that app and NOPE.

**Comment by andymckay** [comment]
:+1:

**Comment by EnTeQuAk** [comment]
I really dislike `internal` as an app name but I don't have any better suggestions yet :confused:

**Comment by tofumatt** [comment]
internal-search is at least better. This isn’t DOS, we can have long, two-word folder names 😉

**Comment by EnTeQuAk** [comment]
`internal_search` wouldn't be that bad imho :)

**Comment by diox** [comment]
It's not just search though. Ultimately this will allow modifications like the current tool does.

**Comment by tofumatt** [comment]
`internal_tools`?

If that doesn't work then I'll stop bikeshedding.

**Comment by diox** [comment]
`internal_tools` works for me. I don't mind the bikeshedding, I didn't like `internal` either.

**Pull request merged**
