### PR TITLE
Update Python Version

### PR DESCRIPTION
**Pull request by philipcristiano**
Work in progress: This updates the Python version by moving to the Docker Python images. `Dockerfile` and `Dockerfile.deploy` were updated with the changes. This includes a shebang change to fix `[[` used in `sh`. 

I've run tests and see a similar number of failures between my updated image and the image pulled for compose. 

Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1390789

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
If you want to test this, running the unittests for some time via `make test` should give you a good idea. CircleCI + some manual testing should do the rest.

**Comment by philipcristiano** [comment]
@EnTeQuAk It may be worth looking at other images. I think we try to stick with the "official" Docker images where possible. It looks like the revsys images are currently at `2.7.13`, so behind by about 3 months on most up to date 2.7 release. 

I'll give a shot at running tests locally, thanks!

**Comment by philipcristiano** [comment]
@EnTeQuAk can you test this out? I don't think I have a full local setup and see about 20% failures with my changes or with the pulled image.

**Comment by philipcristiano** [comment]
cc @bqbn

**Comment by EnTeQuAk** [comment]
> @EnTeQuAk can you test this out? I don't think I have a full local setup and see about 20% failures with my changes or with the pulled image.

I'll give it a go and get back to you shortly

**Comment by EnTeQuAk** [comment]
Just merged this, I tested add-on validation, ran tests, uploaded an image and it all seemed fine.

Let's get this tested on -dev

**Comment by bqbn** [comment]
Pushing to -dev is failing, and the error looks like this:

```
Jan 27 01:53:08 ip-172-31-51-77 systemd[1]: Started Daemon for addons.
Jan 27 01:53:09 ip-172-31-51-77 docker[29333]: container_linux.go:247: starting container process caused "exec: \"/usr/sbin/uwsgi\": stat /usr/sbin/uwsgi: no such file or directory"
Jan 27 01:53:09 ip-172-31-51-77 docker[29333]: /usr/bin/docker-current: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/usr/sbin/uwsgi\\\": stat /usr/sbin/uwsgi: no such file
Jan 27 01:53:09 ip-172-31-51-77 systemd[1]: docker-addons.service: main process exited, code=exited, status=127/n/a
Jan 27 01:53:09 ip-172-31-51-77 docker[29435]: Error response from daemon: No such container: addons
Jan 27 01:53:09 ip-172-31-51-77 docker[29441]: Error response from daemon: No such container: addons
Jan 27 01:53:09 ip-172-31-51-77 systemd[1]: Unit docker-addons.service entered failed state.
Jan 27 01:53:09 ip-172-31-51-77 systemd[1]: docker-addons.service failed.
```

It may be related to 
* https://github.com/mozilla/addons-server/pull/7363/files#diff-9d8e13c2dac78d2e51e7ad1eebff3f95L34
* https://github.com/mozilla/addons-server/pull/7363/files#diff-9d8e13c2dac78d2e51e7ad1eebff3f95L35

Although I wonder why it worked on the local environment, unless uwsgi is not used in that environment?

**Comment by EnTeQuAk** [comment]
Yeah, uwsgi isn't used in the local environment unfortunately.

**Pull request merged**
