### PR TITLE
Replace our implementation of @cached_property by django's

### LINKED ISSUE #3140: Replace amo.cached_property by django's
We have our own `cached_property` implementation in https://github.com/mozilla/addons-server/blob/master/src/olympia/amo/__init__.py#L36 but [django already has one that seem to be providing equivalent functionality](https://docs.djangoproject.com/en/dev/ref/utils/#django.utils.functional.cached_property) (except it's always writable to override the computed value, but that's a good thing)

We should remove our implementation and use django's. Bonus points, in the future we'll get nice fixes like this one: https://github.com/django/django/commit/271bfe65d986f5ecbaeb7a70a3092356c0a9e222

### PR DESCRIPTION
**Pull request by diox**
Fix #3140, maybe it works out of the box ?

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
We didn't have any tests that need to be removed?

r+ once CircleCi and Travis agree

**Comment by diox** [comment]
Lots of failure, that may not be so straightforward after all. I'll take a look later.

**Comment by eviljeff** [comment]
I took a quick look - django's implementation apparently chokes if you try to `del` a cached attribute that's not been accessed yet.  I trivially did https://travis-ci.org/eviljeff/olympia/builds/157705501 and it fixes most of the failures.  
However...
* assuming the above is true, that's super lame.
* there has to be way to genuinely check the attribute exists without creating it - I put the `raise` in the `else` to prove to myself that it's never false.
* there are still some failures in the user tests which could indicate the cached_property isn't working in the first place
* the change I did in test_views.py should be unnecessary - I remember I _needed_ to delete `supported_platforms` to make the tests work.

**Comment by diox** [comment]
In python 2 (*), when you call `hasattr()` behind the scenes it does a `getattr()` and throws away the result. For this reason, instead of checking if the attribute exists, one should just use it and catch the exception that will be raised if it doesn't. 

(*) That particular gotcha is fixed in python 3.

**Comment by EnTeQuAk** [comment]
This still looks like a lot of work, should we maybe close the PR meanwhile working on it?

**Comment by diox** [comment]
Yeah.

**Pull request closed without merging**
