### PR TITLE
Improve editor queues column width

### LINKED ISSUE #2290: Too small column width
On the queues pages column for add-on name is too narrow, and the column for icon Version Notes / Notes for Reviewer is too wide.

### PR DESCRIPTION
**Pull request by wagnerand**
Fixes #2290

r? @eviljeff

### CODE REVIEW

**Comment by eviljeff** [comment]
i can haz screenshot plz

**Comment by wagnerand** [comment]
editor_tools____add-ons_for_firefox

**Comment by wagnerand** [comment]
Oh, that gradient needs to go!

**Comment by eviljeff** [comment]
ha, as long as this doesn't negatively affect the other queues then,
r+

**Comment by wagnerand** [comment]
Thanks! I tested with the other queues and everything looked ok.

**Pull request merged**
