### PR TITLE
describe.html: Prevent checking of checkbox by clicking on tooltip

### PR DESCRIPTION
**Pull request by meetmangukiya**
Fixes https://github.com/mozilla/addons-server/issues/3761

### CODE REVIEW

**Comment by tofumatt** [comment]
Can you please provide before/after screenshots so QA can verify the changes? Thanks! 😄

**Comment by muffinresearch** [comment]
Running this locally it looks good - there's no visual differences and the behaviour is now consistent with the other checkbox.

**Comment by muffinresearch** [comment]
Thanks @meetmangukiya /cc @atsay

**Comment by caitmuenster** [comment]
Thanks @meetmangukiya! We've added your contribution to the Add-on Contributor Recognition page at https://wiki.mozilla.org/Add-ons/Contribute/Recognition#November_2016. 

Welcome to the project! We're happy to have you on board.

**Pull request merged**
