### PR TITLE
Make translation fields compatible with 1.8 migrations.

### PR DESCRIPTION
**Pull request by EnTeQuAk**

### CODE REVIEW

**Comment by diox** [comment]
That does fix the issue I was having, but is there a way to write a test for this ?

**Comment by EnTeQuAk** [comment]
yeah, there are some ways. I didn't have the time to do that yesterday, I found a few nice reference tests in the django test suite and I'll update the PR in a bit with proper tests.

**Comment by EnTeQuAk** [comment]
Sorry for the wait, @diox I added a few tests inspired by how django does it. They fail properly if the actual patch is removed.

**Comment by diox** [comment]
r+

**Pull request merged**
