### PR TITLE
Don't fall back to storage for platform/appversion

### LINKED ISSUE #3104: Android searches are defaulting to version 45
Do a search from https://addons.mozilla.org/en-US/android/ and the resulting URL will be something like https://addons.mozilla.org/en-US/android/search/?q=&appver=45.0&platform=all (this is a blank search)
Note that this is specifying version 45 and says so on the side panel.

The current released version though is 47.

### PR DESCRIPTION
**Pull request by tofumatt**
Fixes #3104

### CODE REVIEW

**Comment by tofumatt** [comment]
I don't even know why we were even using storage... so I submitted a patch that just ditches it.

**Comment by tofumatt** [comment]
r? to whoever gets here first, this should be a simple fix 😄

**Comment by diox** [comment]
This was definitely done on purpose, but I don't see why... It was changed 2 years ago to use `localStorage` on the client-side instead of the session on the server side: 8ea319994780bcf87f849601b02bb5ceba5335bd

**Comment by diox** [comment]
r+ let's try it.

**Pull request merged**
