### PR TITLE
temporarily reduce SESSION_COOKIE_AGE

### LINKED ISSUE #18688: reduce cookie (and so session) expiry time on addons-dev
We have a 30 day session expiry time which is a problem for testing any feature that relies on testing session expiry - waiting 30 days between steps is not practical(!).  Lets reduce it to a very short time (few minutes) just for addons-dev.

### PR DESCRIPTION
**Pull request by eviljeff**
fixes #18688

### CODE REVIEW

**Comment by ioanarusiczki** [comment]
@eviljeff I tried on -dev and -stage -> login and just wait , then I went to an addon detail page but I still see a detail page being displayed (and I should see the Login Expired page instead) 

The Login Expired page is displayed with the scenario from https://github.com/mozilla/addons-frontend/issues/11014#issuecomment-1021205383 when there are 2 tabs, from one the user logs out and then goes to a detail page from the other tab.

**Comment by eviljeff** [comment]
> this pull request is still open

yes.  It's not been merged.  If 5 minutes seems like a good time for you then we can go ahead with it.

**Review by diox — APPROVED** [review]
r+ if 5 minutes is ok for QA

**Comment by ioanarusiczki** [comment]
@eviljeff let's merge then

**Comment by ioanarusiczki** [comment]
@eviljeff first test with a win! it worked now on -dev

**Pull request merged**
