### PR TITLE
Updated abuse_reports.html

### LINKED ISSUE #11775: Double entry for the Abuse Reports section on the /reviewers/abuse-reports/ page
**STR**

1. Log in to AMO stage with a reviewer account
2. Open to the Auto-approval queue and select an add-on to review
3. Click on Abuse reports to view all the reports for the selected add-on - see https://reviewers.addons.allizom.org/en-US/reviewers/abuse-reports/botblockerlocale

**Actual result:**
There are two entries for the Abuse reports section

**Expected result:**
Abuse reports section appears only once

**Notes:**
- reproduced on -dev and stage with Fx67, WIn10x64

double abuse

### PR DESCRIPTION
**Pull request by Patil2099**
Double entry for the Abuse Reports section on the /reviewers/abuse-reports/ page  Fixed 
Fixes  #11775

### CODE REVIEW

**Comment by eviljeff** [comment]
You can delete everything other than `Double entry for the Abuse Reports section on the /reviewers/abuse-reports/ page Fixed
Fixes #11775` from the pull request description

**Comment by eviljeff** [comment]
Can you include a screenshot of what the abuse reports page looks like now?

**Comment by Patil2099** [comment]
I didn't run it locally @eviljeff

**Comment by Patil2099** [comment]
@eviljeff  I don't know how to reach that view but I can assure that abuse reports table would show up only once as I studied the code. Help me 
Thanks!

**Comment by eviljeff** [comment]
it would show up under a url like `http://olympia.dev/reviewers/abuse-reports/<addon-slug>` locally - though you'd also need to add some abuse reports to see it working.  You should be able to use the API to submit a report (or maybe the admin)

This was why we didn't fix it ourselves in 2 minutes - the coding is an easy fix but checking it actually works by running it locally and creating the necessary data is a hassle.

**Comment by Patil2099** [comment]
@eviljeff As soon as I run the changes locally I will post the Screenshot. 
Thanks for the help 😀

**Comment by EnTeQuAk** [comment]
> @eviljeff As soon as I run the changes locally I will post the Screenshot.
Thanks for the help grinning

Did you have the time to do that yet?

**Comment by Patil2099** [comment]
I tried to do so but I failed and opened a issue because I was getting errors. They said they are working on it. It might take some time. What should I do ? Suggest @eviljeff

On Aug 5, 2019 2:12 PM, Christopher Grebs <notifications@github.com> wrote:

@eviljeff<https://github.com/eviljeff> As soon as I run the changes locally I will post the Screenshot.
Thanks for the help grinning

Did you have the time to do that yet?

**Comment by eviljeff** [comment]
#12015 is fixed now

**Pull request closed without merging**
