### PR TITLE
Reviews number in the required add-ons section is hard to read #2606

### PR DESCRIPTION
**Pull request by merike**
I looked into it as part of Hactoberfest but never got to sending a pull request. So giving it a go now :)

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
Thanks a lot for the pull request @merike 

Would it be possible to attach some before / after screenshots to make sure QA can test and verify this more easily once merged?

**Comment by merike** [comment]
Could you link me some documentation on what's the easiest way to make changes to the database set up in docker container? Docker is new to me and initial data didn't seem to contain any addons with dependencies? Or I could make screenshots of staging site with the change made in browser dev tools only? That'd be easiest for me.

**Comment by EnTeQuAk** [comment]
> Or I could make screenshots of staging site with the change made in browser dev tools only? That'd be easiest for me.

Given the small change, that'll be totally fine. Just to make sure we have some image that shows how it's supposed to be looking.

**Comment by merike** [comment]
Before on the left, after the change on the right:
amo_link

**Comment by EnTeQuAk** [comment]
Awesome, thanks a lot!

**Comment by caitmuenster** [comment]
Thanks so much, merike, and welcome onboard! Your contribution has been noted on the [recongition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition#November_2016). Happy hacking!

**Pull request merged**
