### PR TITLE
disable auto-approval when setting needs human review in a content review

### PR DESCRIPTION
**Pull request by eviljeff**
Fixes: mozilla/addons#14889

### Description

Pretty simple change as per the title.  The PR adds an extra sentence for content reviews for the set needs human review action; and sets a reviewer flag for content reviews.  (content reviews are only for listed versions)

### Testing

- open any review page for an add-on in the content review queue
- choose "set needs human review" action, choose a version, and submit with a comment
- navigate to the admin for that add-on (link in the right hand column) and scroll down to the add-on reviewer flags section to see `Auto approval disabled until next approval` set to yes

(screenshots below)
### Checklist

- [x] Add `#ISSUENUM` at the top of your PR to an existing open issue in the mozilla/addons repository.
- [x] Successfully verified the change locally.
- [x] The change is covered by automated tests, or otherwise indicated why doing so is unnecessary/impossible.

### CODE REVIEW

**Comment by eviljeff** [comment]
Screenshot 2024-07-04 172927
Screenshot 2024-07-04 172852

**Comment by KevinMind** [comment]
I was not able to verify this.

1) there is a separate flag for listed/unlisted versions, which do I expect to be set to "yes" or both?
2) Do I need to do this for a listed or unlisted version?


https://github.com/mozilla/addons-server/assets/19595165/9002eab3-76a9-4a33-b5b8-7c864bc31dbc

**Comment by eviljeff** [comment]
@KevinMind there's a detail I should have highlighted in the description - specifically it's the **content review queue** - not the normal manual review queue (the url bar doesn't show the content review page).  In the issue Abhi clarified it's just listed versions.

**Comment by KevinMind** [comment]
How do I get an addon on the "content review queue"?

**Comment by eviljeff** [comment]
> @eviljeff How do I get an addon on the "content review queue"?

There's normally a bunch in the content queue already locally, as a result of landfill creating extensions for the homepage.

**Review by KevinMind — APPROVED** [review]
Verified!

Screenshot 2024-07-09 at 18 13 24

**Pull request merged**
