### PR TITLE
Port services to use django cursors, remove ancient sqlalchemy

### PR DESCRIPTION
**Pull request by EnTeQuAk**
We might need benchmarks to verify things are working as expected.

### CODE REVIEW

**Comment by andymckay** [comment]
👍 but please make sure to get extra QA on this and co-ordinate configs with @jasonthomas 

This service gets the most traffic of almost anything at Mozilla and needs to stay up and fast. But don't let that stop you improving it! 😄

**Comment by EnTeQuAk** [comment]
haha, I won't :laughing:

The configs should not need any updates and we can test that on dev as soon as it lands. But having second looks at it is never bad, mind an additional r? @jasonthomas

**Comment by EnTeQuAk** [comment]
Need to figure out and fix those weird failures first…

**Comment by diox** [comment]
I once tried to do this in Marketplace:
- https://github.com/mozilla/zamboni/commit/72fe88ed4b5e9ac4112d3d287280e0acfab2d362
- https://github.com/mozilla/zamboni/commit/f76c11a8c5fc87663b79e257ed0aa8bd3e4c8ba2

Unfortunately, it caused issues on dev and stage (IIRC the connection was closed without the process knowing, causing lots of errors after a while) and was reverted in https://github.com/mozilla/zamboni/commit/3da44ce92e1397c48ef6d23dcfa7ce7f194641eb

**Comment by EnTeQuAk** [comment]
hmm, imho django does a good job at reconnecting but I might just do a bit more testing and let it run maybe for a few more hours once travis is green. Thanks for the hints!

**Comment by EnTeQuAk** [comment]
Closing for now as I continue to work on it and test it more thoroughly

**Pull request closed without merging**
