### PR TITLE
Integrate codecov for coverage reports

### PR DESCRIPTION
**Pull request by EnTeQuAk**
Experimental, let's see if that works.

Example reports: https://codecov.io/gh/mozilla/addons-server

### CODE REVIEW

**Comment by andymckay** [comment]
Oh well done, I wasn't quite sure how much this would slow travis down.

**Comment by EnTeQuAk** [comment]
Needs a bit more tinkering, somehow coverage reports won't get created.

**Comment by EnTeQuAk** [comment]
@muffinresearch  could you add the webhook to the addons-server repository please? https://codecov.io/gh/mozilla/addons-server/settings

**Comment by muffinresearch** [comment]
> @muffinresearch could you add the webhook to the addons-server repository please? https://codecov.io/gh/mozilla/addons-server/settings (-> "Create New Webbook")

Done.

**Comment by EnTeQuAk** [comment]
@diox r?

**Comment by diox** [comment]
This does seem to slow down the build a little bit, between 20 and 30 seconds for each job that runs tests (i.e. not `flake8`). I guess that's fine though, but we should monitor it closely.

**Comment by diox** [comment]
r+ let's try it

**Comment by EnTeQuAk** [comment]
yeah, will monitor if it's slowing us down too much. But I guess we'll get some good insights from coverage reports too so it's not all that bad.

**Pull request merged**
