### PR TITLE
Django 1.7

### PR DESCRIPTION
**Pull request by EnTeQuAk**
This is a new re-done/rebased version of the old django 1.7 branch with all the fixes applied on a clean master.

This is a tracking pull request, further notes are in https://github.com/mozilla/olympia/issues/905 so this is mostly for me to have a better overview over what I'm doing and in the end after some git-cleanups for everyone to review.

Notes:

* `messages.po` -> `django.po`
* `javascript.po` -> `djangojs.po`

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
@flodolo / @mathjazz mind taking a look at this? This branch will change all locale domains from `messages` -> `django` and `javascript` to `djangojs` as probably did a few other mozilla apps. Is there anything that needs to be done to update stuff?

**Comment by mathjazz** [comment]
Thanks for the heads up, @EnTeQuAk!

I need to change something in Pontoon in order to preserve attributions, so please ping me on IRC (mathjazz in #l10n or #pontoon) before you merge.

Also, this is the renamed olympia repository, right? I see yesterday's commits from Pontoon, so GitHub must be handling that gracefully (because Pontoon is still configured to use olympia).

**Comment by EnTeQuAk** [comment]
Awesome, thanks!

Yeah, github installs redirects for repository renames.

**Comment by EnTeQuAk** [comment]
eh, mat yeah ignore the piston part - that was from before you removed it and maybe I messed up with the merge. I'll remove it

**Comment by diox** [comment]
For this particular part it's my fault, I didn't remove the requirement. I guess you can change your commit to drop it entirely.

**Comment by diox** [comment]
One test failure (intermittent?) and new conflicts, but looks good overall. Good job!

r+wc+travis+wait till tag :)

**Comment by EnTeQuAk** [comment]
@diox I rewrote redis configuration a bit in https://github.com/EnTeQuAk/olympia/commit/66056ffecc20674a29658834e39b86e3ae8d16bb, it was kinda messy so it's now using the URI again but translating it to a `redisutils` compatible dict.

**Pull request merged**
