### PR TITLE
Update devhub landing page logo

### LINKED ISSUE #4531: no Firefox logo on DevHub landing page
When going to https://addons.mozilla.org/developers/ I was briefly puzzled about what browser that pages belongs to as there is no Firefox logo on the page but a Chrome and Opera logo.

I expected to also see a Firefox Logo to reassure me that this page is for developing for Firefox.

Maybe something like this might help:
screen-shot-2017-01-30-at-19 06_2
(or maybe that is too obvious.)

### PR DESCRIPTION
**Pull request by wagnerand**
Fix #4531.

### CODE REVIEW

**Comment by wagnerand** [comment]
Before:

before

After:

after

**Comment by diox** [comment]
Please run that svg through a tool like https://jakearchibald.github.io/svgomg/ to optimize it, it could be much smaller

**Comment by wagnerand** [comment]
Meh, I just used the file that @designakt provided ¯\_(ツ)_/¯

**Comment by designakt** [comment]
Looks great. Thanks for updating this.

**Pull request merged**
