### PR TITLE
Fixed issue 2351

### LINKED ISSUE #2351: Modals can be broken
Steps to reproduce:
1. Sign in to AMO-stage https://addons.allizom.org/en-US/firefox
2. Go to any add-on details page https://addons.allizom.org/en-US/firefox/addon/tab-notifier/
3. Click the "Report Abuse" link
4. Increase the text field width

Expected results:
There are no display or layout issues.

Actual results:
There are some layout ugly issues.

Notes/Issues:
The issue is also reproducing in "Write a review" window (also the section from themes details), contribution window, etc.
Verified on FF45(Win 7). Issue is reproduced on AMO-stage, dev and prod.
Screenshot for this issue:

### PR DESCRIPTION
**Pull request by harikishen**
Fixes #2351

I have modified the code to fix this [issue](https://github.com/mozilla/addons-server/issues/2351) with modals being broken because of resizable <textarea> tags.

### CODE REVIEW

**Comment by wagnerand** [comment]
Thank you for this PR. Can you please remove the jetpack file and use a descriptive commit message? Thank you!

**Comment by harikishen** [comment]
Could suggest an example for the commit message....???

**Comment by harikishen** [comment]
@wagnerand I have done the changes you asked for in this [commit](https://github.com/mozilla/addons-server/pull/5397/commits/3a9f100abd1874ee120498f4624a36cbbb94e03d).

**Comment by wagnerand** [comment]
Can you please use a commit message that describes the change you made? You can find examples on https://github.com/mozilla/addons-server/commits/master

Also, please remove the jetpack file from your commit.

**Comment by harikishen** [comment]
@wagnerand I have done as you said. The jetpack file there now is the one from the original repository. Not pushed by me.

**Comment by wagnerand** [comment]
Looks good, thank you. Does this prevent horizontal resize for all textboxes or just the ones mentioned in #2351?

**Comment by harikishen** [comment]
All textboxes as the issue affected various modals and the pages like this https://addons.mozilla.org/en-US/firefox/addon/enhancer-for-youtube/abuse/

**Comment by wagnerand** [comment]
But it doesn't affect textboxes that are not part of a modal dialog, and we might want to be able to resize them?

**Comment by harikishen** [comment]
but the original issue pointed pages like [this](https://addons.mozilla.org/en-US/firefox/addon/enhancer-for-youtube/abuse/)

**Comment by harikishen** [comment]
see this
screen shot 2017-05-15 at 4 20 19 pm

**Comment by harikishen** [comment]
i just checked it affects all types mentioned in issue #2351

**Comment by harikishen** [comment]
doesn't affect some others

**Comment by harikishen** [comment]
Hope it's enough

**Comment by wagnerand** [comment]
Adding @muffinresearch who suggested this patch. I guess you didn't mean for it to be that broad?

**Comment by harikishen** [comment]
is there anything i should do for the time being ?

**Comment by harikishen** [comment]
@wagnerand any changes required ?

**Comment by wagnerand** [comment]
My opinion is that the resizing restrictions should only apply to textboxes in modal dialogs. @muffinresearch wdyt?

**Comment by harikishen** [comment]
hmm...currently i have modified the file https://github.com/mozilla/addons-server/blob/master/static/css/impala/forms.less . Just let me know if I have to change that. @muffinresearch @wagnerand

**Comment by muffinresearch** [comment]
> My opinion is that the resizing restrictions should only apply to textboxes in modal dialogs. @muffinresearch wdyt?

I think globally applying this to only allow vertical resizing should be ok. I don't think we have a use-case for horizontal textarea resizing. Let's try it.

**Comment by harikishen** [comment]
great

**Comment by caitmuenster** [comment]
Awesome! Congrats on landing your first patch, @harikishen! Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition#May_2017) and your Mozillians profile has been vouched. 

Welcome onboard! 🎉

**Pull request merged**
