### PR TITLE
Remove sdk based addons notifications code

### LINKED ISSUE #10567: Remove SDK notifications Code
See also: mozilla/addons#884 and mozilla/addons-frontend#7525

For QA: this issue is about deleting the "SDK" notifications in the `src/olympia/users/notifications.py` There are 2 SDK notifications to remove.

### PR DESCRIPTION
**Pull request by championshuttler**
Fixes #10567

### CODE REVIEW

**Comment by eviljeff** [comment]
You've got syntax errors too - if you look at the Travis tests you'll see most of them are errored.

You should really set up Travis on your github fork and/or run the tests locally. (And ideally test manually locally too for any significant change)

**Comment by championshuttler** [comment]
Hi @EnTeQuAk, can you help me here , I am getting stuck here 
https://travis-ci.org/mozilla/addons-server/jobs/487802153#L2396

**Comment by eviljeff** [comment]
> I am getting stuck here https://travis-ci.org/mozilla/addons-server/jobs/487802153#L2396

@championshuttler it means the form isn't saving and redirecting (302) because there's an error (so it's a normal page response, 200).  You're going to have to debug it locally by using `ipdb` or `print`-ing the `response.content` or `response.context` to see what the error is.

**Comment by EnTeQuAk** [comment]
@championshuttler do you have the time to look at the changes suggested by @eviljeff?

**Comment by championshuttler** [comment]
@EnTeQuAk I tried to do it but unable to debug the error and how to solve it, can you give me some hint , it would be great. Thanks!!

**Comment by eviljeff** [comment]
@championshuttler the test fail was because the test was trying to set notifications with ids 4 and 6, and you just removed notification id=6.  

There's no 100% way to debug those kind of problems - personally I added `print(r.context['form'].errors)` in the test just before the failing line to see what errors were in the form.

I went ahead and added a commit that fixed the test for you.

**Pull request merged**
