### PR TITLE
Added padding under some notification banners (maybe)

### LINKED ISSUE #2440: No padding under some notification banners
**Steps to reproduce:**
1. Open account settings page: https://addons.allizom.org/en-US/firefox/users/edit
2. Perform some changes and click the "Update Account"  button.

**Expected results:**
The banner is displayed with no layout or display issues.

**Actual results:**
There is no padding under the notification banner.

**Notes/Issues:**
Verified in FF45(Win7)
Issue can be reproduced in amo-dev and amo-stage.
Screenshot for this issue:
nopaddingbanner01

The issue is also reproducing for the Errors found banner:
nopaddingbanner02

Also reproducing in the submit a new theme page:
nopaddingbanner03

### PR DESCRIPTION
**Pull request by SaminRK**
fixes #2440

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
Tanks for the pull request! Two minor things, can you add screenshots of how it's supposed to be looking now, after your patch? Either by setting addons-server up on your local machine or simply make screenshots from your browser after applying it there in the dev-tools (since it's a relatively simple patch). That'll help verifying QA that things are looking the way they're supposed to look.

Also, not needed but helpful, if you add "fixes #2440" to your git commit message it'll close the respective github-issue automatically once the pull request get's merged.

**Comment by muffinresearch** [comment]
> Also, not needed but helpful, if you add "fixes #2440" to your git commit message it'll close the respective github-issue automatically once the pull request get's merged.

Putting `Fixes #NUM` in the PR description is ideal, since that both provides a link for the reviewer and also associates the PR with the issue.

**Comment by EnTeQuAk** [comment]
@SaminRK hey, did you have a chance to update the pull request with the noted changes?

**Comment by SaminRK** [comment]
image

**Comment by SaminRK** [comment]
image

**Comment by EnTeQuAk** [comment]
Nice, thanks for the update! I'm going to merge this, we are going to tag very soon so it'll be deployed on Thursday.

**Comment by SaminRK** [comment]
Thank you very much for helping me out.

**Comment by caitmuenster** [comment]
Thanks so much, @SaminRK, and welcome onboard! Your contribution has been added to our [Recognition Wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition#January_2017).

**Comment by SaminRK** [comment]
So, in order to solve the problem do I need to use Javascript or an it be done by using  only CSS?

**Pull request merged**
