### PR TITLE
Refresh login box

### LINKED ISSUE #2094: Login email box looks like it has incomplete styling.
See https://addons-dev.allizom.org/en-US/firefox/users/login?to=%2Fen-US%2Ffirefox%2F

user_login____add-ons_for_firefox

### PR DESCRIPTION
**Pull request by muffinresearch**
This is me winging it so it needs UX sign-off

Fixes #2094

user_login____add-ons_for_firefox

### CODE REVIEW

**Comment by pwalm** [comment]
Love it, signed off 👍

**Comment by tofumatt** [comment]
This one was a PR, so don't close it until we merge it :wink:

**Comment by tofumatt** [comment]
r+; @muffinresearch is away on holiday so I'll merge this.

**Comment by pwalm** [comment]
Whoops! Sorry :D

**Pull request merged**
