### PR TITLE
update addon descriptions

### PR DESCRIPTION
**Pull request by atsay**
Changed descriptions from pull quotes to editorial copy.

### CODE REVIEW

**Comment by muffinresearch** [comment]
Looks like lint is unhappy with this.

Similar to https://github.com/mozilla/addons-frontend/pull/984 this will need quick updates or we'll be falling back to english for the editorial content. The server doesn't output fuzzy matches at all so we'd be very dependent on getting updates between landing this change. (Doesn't mean we shouldn't do it, but this is a case where we probably want to land it just after a tag to maximise the time localizers will have).

**Comment by diox** [comment]
Yeah, getting this in today (in the next few hours) would work if we'd extract right away and don't forget to re-extract (and most importantly, re-compile) Tuesday before the tag.

**Comment by muffinresearch** [comment]
@atsay was there a related issue to pin this to? Thinking we'd aim to land this after next week's tag. It would mean a bit of a delay to getting this out but allows us to give localizers as much time as possible.

**Comment by muffinresearch** [comment]
Relates to https://github.com/mozilla/addons/issues/179

**Comment by atsay** [comment]
Yes, totally cool to land after next week's tag to maximize translation time. In the meantime, I'll try to pass the linting...

**Comment by atsay** [comment]
I looked at the errors, and they don't seem to be mine...?

**Comment by tofumatt** [comment]
They’re related to line length, I can tidy it up this weekend :-)

**Comment by tofumatt** [comment]
Shoot, sorry, these are just CircleCI errors. This is all good.

**Comment by wagnerand** [comment]
@muffinresearch So, I guess this should land asap?

**Comment by muffinresearch** [comment]
I've going to land this so we can check it on -dev prior to the extract. All being well we'll get the extract done later today.

**Pull request merged**
