### PR TITLE
Remove blocklists code.

### PR DESCRIPTION
**Pull request by Natim**

### CODE REVIEW

**Comment by Natim** [comment]
Now that Blocklist management as moved to Kinto we can get rid of this code.

However I have a few questions:

- Should we do a migration to remove the related tables and if yes how?
- How should we handle the `waffle_switch` feature? Should we remove it? (See src/olympia/addons/urls.py)
- Anything else we should do about that?

**Comment by eviljeff** [comment]
should we redirect https://addons.mozilla.org/en-US/firefox/blocked/ to https://blocked.cdn.mozilla.net/ ?

**Comment by eviljeff** [comment]
> Should we do a migration to remove the related tables and if yes how?

our migrations are numbered files in https://github.com/mozilla/addons-server/tree/master/src/olympia/migrations so you just need some sql that does something like:
`DROP TABLE IF EXISTS ...;` for all the tables.  Plus the foreign keys.

**Comment by wagnerand** [comment]
Easy pitfall: Remember to end every statement with a `;`.

**Comment by Natim** [comment]
> we should redirect https://addons.mozilla.org/en-US/firefox/blocked/* to https://blocked.cdn.mozilla.net/* ?

This is already the case.

**Comment by jasonthomas** [comment]
> This is already the case.
No, it's not been setup for addons.mozilla.org, it has been setup for blocklist.addons.mozilla.org.

**Comment by Natim** [comment]
Yes I just realized that. Do you want me do add it in the django code?

**Comment by jasonthomas** [comment]
> Yes I just realized that. Do you want me do add it in the django code?

Let's add it as part of the nginx config. https://github.com/mozilla-services/cloudops-deployment/pull/466

**Comment by Natim** [comment]
@leplatrem and I have added the migration file, can you tell us what is the next step for this PR?

**Comment by Natim** [comment]
GitPython doesn't support commit signature so I removed signature from commits.

**Comment by EnTeQuAk** [comment]
side note, does this allow us to close https://github.com/mozilla/addons-server/issues/3776, and https://github.com/mozilla/addons-server/issues/3807?

**Comment by eviljeff** [comment]
> side note, does this allow us to close #3776, and #3807?

makes them not fixable in amo's code, at least.

**Comment by Natim** [comment]
> GitPython doesn't support commit signature so I removed signature from commits.

Should be fixed with #4732

**Comment by Natim** [comment]
> side note, does this allow us to close #3776, and #3807?

> makes them not fixable in amo's code, at least.

I would say that #3776 is probably a bug to fix in mozcentral, maybe we should create a Bugzilla ticket for it.

#3807 can be close it has been fixed in the Kinto side.

**Comment by Natim** [comment]
> Just need to bump the migration number to 925

Do you want me to do it?

**Pull request merged**
