### PR TITLE
fix missing space

### PR DESCRIPTION
**Pull request by Spidersouris**

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
Thanks for the patch, this isn't the perfect place to patch this though. It'd be better to change the string in the file where it got extracted from:

```diff
diff --git a/src/olympia/devhub/templates/devhub/addons/submit/done.html b/src/olympia/devhub/templates/devhub/addons/submit/done.html
index 7c2f7b97ef..8b506ce11b 100644
--- a/src/olympia/devhub/templates/devhub/addons/submit/done.html
+++ b/src/olympia/devhub/templates/devhub/addons/submit/done.html
@@ -34,7 +34,7 @@
 {% else %}
   <h3>{{ _("Version Signed") }}</h3>
   <p>
-    {{ _("You’re done! This version is signed and ready to for self-distribution."
+    {{ _("You’re done! This version is signed and ready to for self-distribution. "
          "You can download it by clicking the button below.") }}
   </p>
   <p>
```

if you're up for it feel free to submit an update for your PR. Once this lands we can re-run extraction to make sure it's being fixed / updated everywhere.

**Comment by Spidersouris** [comment]
Alright, thanks. Done!

**Comment by EnTeQuAk** [comment]
Wonderful, thanks! Let's wait for travis and then I'll merge it.

**Comment by caitmuenster** [comment]
Hey Spidersouris! Thanks so much for this fix. Your contribution has been added to our r[ecognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition#December_2016).

**Pull request merged**
