### PR TITLE
Upgrade mysql to v5.7

### PR DESCRIPTION
**Pull request by bqbn**
We plan to upgrade MySQL to v5.7.16. This is to make dev local env align with that.

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
We should try and switch to MySQL 5.7 for travis then asap too imho. Apparently this isn't officially supported yet, only MariaDB appears to officially support 10.1 and 10.2 (which have 5.7 features)... mhmm

**Comment by EnTeQuAk** [comment]
https://github.com/travis-ci/travis-ci/issues/5122

**Comment by bqbn** [comment]
travis-ci is really disappointing in this case.

@EnTeQuAk do you think travis-ci doesn't support MySQL 5.7 is a blocker for us to upgrade to 5.7?

Given that ticket has been more than one year old and the comments for it being disabled, I doubt it'll get any traction soon from travis-ci.

I see some people work around it by installing 5.7 themselves. Do we want to do that, or use MariaDB 10.2, or else?

**Comment by bqbn** [comment]
FWIW, it looks like MySQL v5.5 is currently used on TravisCI, even though our production db is v5.6. In this case, maybe we shouldn't let it block us from upgrading to v5.7?

```
$ mysql -V
mysql  Ver 14.14 Distrib 5.5.41, for debian-linux-gnu (x86_64) using readline 6.2

$ dpkg -l | egrep mysql

ii  libdbd-mysql-perl                   4.020-1build2                                       Perl5 database interface to the MySQL database
ii  libmysql++-dev                      3.1.0-2                                             MySQL C++ library bindings (development)
ii  libmysql++3                         3.1.0-2                                             MySQL C++ library bindings (runtime)
ii  libmysql-ruby                       2.8.2+gem2deb-1build1                               Transitional package for ruby-mysql
ii  libmysqlclient-dev                  5.5.41-0ubuntu0.12.04.1                             MySQL database development files
ii  libmysqlclient18                    5.5.41-0ubuntu0.12.04.1                             MySQL database client library
ii  libqt4-sql-mysql                    4:4.8.1-0ubuntu4.8                                  Qt 4 MySQL database driver
ii  mysql-client                        5.5.41-0ubuntu0.12.04.1                             MySQL database client (metapackage depending on the latest version)
ii  mysql-client-5.5                    5.5.41-0ubuntu0.12.04.1                             MySQL database client binaries
ii  mysql-client-core-5.5               5.5.41-0ubuntu0.12.04.1                             MySQL database core client binaries
ii  mysql-common                        5.5.41-0ubuntu0.12.04.1                             MySQL database common files, e.g. /etc/mysql/my.cnf
ii  mysql-server                        5.5.41-0ubuntu0.12.04.1                             MySQL database server (metapackage depending on the latest version)
ii  mysql-server-5.5                    5.5.41-0ubuntu0.12.04.1                             MySQL database server binaries and system database setup
ii  mysql-server-core-5.5               5.5.41-0ubuntu0.12.04.1                             MySQL database server binaries
ii  ruby-mysql                          2.8.2+gem2deb-1build1                               MySQL module for Ruby
```

**Comment by EnTeQuAk** [comment]
I doubt it's a blocker but it's definitely not good not to run our tests against a older version of MySQL. 

I opened https://github.com/mozilla/addons-server/issues/4503 so we can unblock this pull request as getting travis probably will be quite a bit of work.

**Comment by bqbn** [comment]
As a separate note, we may want to consider using Trusty distro on TravisCI. Precise (12.04) is about to eol early this year? https://www.ubuntu.com/info/release-end-of-life

**Comment by EnTeQuAk** [comment]
Yeah, but afair trusty is still in beta on travis unfortunately... 





On Mon, Jan 30, 2017, at 09:31 PM, bqbn wrote:

> As a separate note, we may want to consider using Trusty distro on
> TravisCI. Precise (12.04) is about to eol early this year?
> https://www.ubuntu.com/info/release-end-of-life
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].
> 


Links:

  1. https://github.com/mozilla/addons-server/pull/4487#issuecomment-276181385

**Pull request merged**
