### PR TITLE
No developer replies unless activity-email waffle is on

### PR DESCRIPTION
**Pull request by eviljeff**

### CODE REVIEW

**Comment by kumar303** [comment]
@EnTeQuAk @diox could one of you review this? This needs to be cherry picked for release.

**Comment by EnTeQuAk** [comment]
Can we add a test that tests some of the features e.g the template and stuff to make sure nothing happens when then flag is disabled? It should fail when it's enabled / removed.

**Comment by eviljeff** [comment]
Added some tests for when the waffle is missing/off.

**Comment by kumar303** [comment]
@EnTeQuAk thanks for reviewing

**Pull request merged**
