### PR TITLE
Fix node paths in dockerfile (fix #2701)

### LINKED ISSUE #2696: Table olympia.frozen_addon doesnt exist error
Get this issue after updating latest image after #2596 

screenshot from 2016-05-18 14 12 43

### LINKED ISSUE #2701: Node path in dockerfile are wrong
Fix incoming...

### PR DESCRIPTION
**Pull request by tofumatt**
Should fix #2696 also.

### CODE REVIEW

**Comment by muffinresearch** [comment]
Would it work if you just removed the -g for the npm install here: https://github.com/mozilla/addons-server/blob/master/Dockerfile#L68

**Comment by EnTeQuAk** [comment]
@muffinresearch npm doesn't pick up our custom configured location then though and we want to install the packages into the mounted volume to a specific path to be able to reference it later.

**Comment by muffinresearch** [comment]
@EnTeQuAk I don't think you want to install node_modules into the mounted volume. Architecture could be different.

**Comment by muffinresearch** [comment]
The old method put them out of the way on the container.

**Comment by muffinresearch** [comment]
Fwiw: This doc suggest that if you provide it via the CLI it will use it for non-global commands (which is slightly odd)

```
prefix

    Default: see npm-folders
    Type: path

The location to install global items. If set on the command line, then it forces non-global commands to run in the specified folder.
```

**Comment by muffinresearch** [comment]
So it might be worth trying the `--prefix` option and not use `-g` if that saves us the ugly paths.

**Comment by EnTeQuAk** [comment]
@muffinresearch setting `--prefix` didn't work if I didn't set `-g` as well.

from what I see in the docs:
```
       · global mode:
         npm installs packages into the install prefix at prefix/lib/node_modules and bins are installed in prefix/bin.

       · local mode:
         npm installs packages into the current project directory, which defaults to the current working directory.  Packages are installed to ./node_modules, and bins are installed to ./node_modules/.bin.
```
From this I get that the prefix is only relevant in global mode.

**Comment by muffinresearch** [comment]
I'm not sure what this is referring to then: https://docs.npmjs.com/misc/config#prefix. 

Ah but it might not work since there's no package.json in that dir if it means you're essentially running `npm install` from the dir specified as the value for the prefix CLI option and that would be a no-op with no package.json.

**Comment by muffinresearch** [comment]
Yep that appears to be the case trying that locally.

**Comment by muffinresearch** [comment]
Just be clear you need `npm install --prefix [PATH]` and the specified path must already have the `package.json` in it.

**Comment by EnTeQuAk** [comment]
ah, we''d have to copy the package.json to `/deps/` and do the install from there. We did that with pip earlier but removed that in favor of setting the environment variables.

**Comment by muffinresearch** [comment]
I can confirm it does result it cleaner paths, as before.

**Comment by EnTeQuAk** [comment]
Alrighty, so @muffinresearch and me went on vidyo to shortly clear up confusion that I had. So the probably best way to come up with cleaner paths is something like this:

 * symlink or copy (to be experimented) `package.json` to `/deps/`
 * change `ENV NPM_CONFIG_PREFIX=/deps/`
 * remove `-g` option from `npm install` in the `Dockerfile` and maybe just use `make update_deps` again (yeay! one single source of truth)
 * update paths and do a happy dance

I'll try this out once I get back from sports later, if it works, let's do that :)

**Comment by EnTeQuAk** [comment]
it's not working the way I want it to :disappointed: 

```
[root@171cc41d917c code]# env | grep NPM
NPM_CONFIG_PREFIX=/deps/
[root@171cc41d917c code]# npm config ls -l | grep prefix
prefix = "/deps"

[root@171cc41d917c code]# npm install
> dtrace-provider@0.6.0 install /code/node_modules/addons-linter/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js

[root@171cc41d917c code]# npm install -g
> dtrace-provider@0.6.0 install /deps/lib/node_modules/addons-server/node_modules/addons-linter/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js
```

Pretty much what I read in http://stackoverflow.com/a/14867050

On the other hand, doing `npm install --prefix /deps/` works perfectly without the `-g` but it's really stupid to not be able to control the prefix via an environment variable.

**Comment by EnTeQuAk** [comment]
Which would be something like

```diff
diff --git a/Dockerfile b/Dockerfile
index 857a411..5fcbaf8 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -59,13 +59,12 @@ WORKDIR /code
 ENV PIP_BUILD=/deps/build/
 ENV PIP_CACHE_DIR=/deps/cache/
 ENV PIP_SRC=/deps/src/
-ENV NPM_CONFIG_PREFIX=/deps/node_modules/

 # Install all python requires
 RUN mkdir -p /deps/{build,cache,src}/ && \
+       ln -s /code/package.json /deps/package.json && \
     pip install --upgrade pip && \
-    make install_python_dependencies && \
-    npm install -g && \
+    make update_deps && \
     rm -r /deps/build/ /deps/cache/

 # Preserve bash history across image updates.
@@ -80,8 +79,8 @@ ENV HISTIGNORE ls:exit:"cd .."
 # This prevents dupes but only in memory for the current session.
 ENV HISTCONTROL erasedups

-ENV CLEANCSS_BIN /deps/node_modules/clean-css/bin/cleancss
-ENV LESS_BIN /deps/node_modules/less/bin/lessc
-ENV STYLUS_BIN /deps/node_modules/stylus/bin/stylus
-ENV UGLIFY_BIN /deps/node_modules/uglify-js/bin/uglifyjs
-ENV ADDONS_LINTER_BIN /deps/node_modules/addons-linter/bin/addons-linter
+ENV CLEANCSS_BIN /code/node_modules/.bin/cleancss
+ENV LESS_BIN /code/node_modules/.lessc
+ENV STYLUS_BIN /code/node_modules/.stylus
+ENV UGLIFY_BIN /code/node_modules/.bin/uglifyjs
+ENV ADDONS_LINTER_BIN /code/node_modules/.bin/addons-linter
```

but I don't like the packages to be installed in `/code` since it's the mounted volume.

Maybe let's just keep it the way it is now don't care about nice paths?

**Comment by EnTeQuAk** [comment]
also it appears that node/npm only supports local installations if you're using `require()` - which we don't but global mode is only really used / supported for binary installations.

Let's stay local then?

**Comment by muffinresearch** [comment]
It's not just the paths we'd ideally not install the addons-server package globally which I think is what `npm install -g` is implicitly doing. That's not the same thing as installing all the deps listed in the package json globally individually.

**Comment by muffinresearch** [comment]
Since you're using the shell form of `RUN` is the `$NPM_CONFIG_PREFIX` not replaced with the right value if you do `npm install --prefix $NPM_CONFIG_PREFIX`?

**Comment by EnTeQuAk** [comment]
That would certainly work but if you would update the packages manually
you need to make sure to set --prefix. We could do that in the makefile
for now though which should be fine since update_deps should be the only
way to install/update dependencies anyway.
 
 
On Thu, May 19, 2016, at 10:25 AM, Stuart Colville wrote:
> Since you're using the shell form of RUN is the $NPM_CONFIG_PREFIX not
> replaced with the right value if you do npm install --prefix
> $NPM_CONFIG_PREFIX?
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub[1]
>
 

Links:

  1. https://github.com/mozilla/addons-server/pull/2702#issuecomment-220259418

**Comment by EnTeQuAk** [comment]
yeah, that seems to work. I'll close this PR and open a new one with all the changes.

**Comment by EnTeQuAk** [comment]
https://github.com/mozilla/addons-server/pull/2704

**Pull request closed without merging**
