### PR TITLE
Make sure we determine an add-on as WebExtension if there's a manifest.json

### LINKED ISSUE #2450: make sure we determine an addon as WebExtension once there's a manifest.json
Currently we check for `manifest.json` last which leads to some problems for addons that should be WebExtensions but still have the old metadata files.

See https://github.com/mozilla/addons-server/blob/master/src/olympia/files/utils.py#L93 for example.

To make sure a scenario like this never happens we have to change the `addons-linter` and `amo-validator` to properly raise an exception.

### PR DESCRIPTION
**Pull request by EnTeQuAk**
Fixes #2450

### CODE REVIEW

**Comment by andymckay** [comment]
Confused if both `install.rdf` *and* `manifest.json` exists then its not a WebExtension, or is a WebExtension?

**Comment by EnTeQuAk** [comment]
If both exist it's a WebExtension, we'll run `addons-linter` which will warn/error if both configs exist.

**Comment by diox** [comment]
"termine" ? Is that a typo for "determine" ? :)

**Comment by EnTeQuAk** [comment]
oops, yeah, `determine` is what I wanted :laughing:

**Comment by diox** [comment]
r+

**Pull request merged**
