### PR TITLE
replace tag selection in devhub with checkboxes

### LINKED ISSUE #17474: replace existing tags with new, editorial defined, tags
https://docs.google.com/document/d/1QJ5PSHJJn5ruvhITlTMongePpZggsrTYKdmmBO0Wbk4/edit# for full details on background, but tl;dr: we want to replace the existing tags that a developer can define with a fixed list of tags AMO's staff define.  

* existing tags will be reset (deleted)
* devhub edit form needs changing to allow a selection from the tags available (multi-select list?  checkboxes like categories?) rather than a free text box

(and more, but this is the main change in addons-server and probably needs to be done first and in one go)

### PR DESCRIPTION
**Pull request by eviljeff**
fixes #17474 - will need some follow-up either way depending on the outcome of #17479 but this keeps open the option of continuing to tag with the `dynamic theme` tag.

### CODE REVIEW

**Comment by diox** [comment]
While testing I noticed something weird/annoying: when you save, you get back to the edit product page, and the tags always show `None`, even if there were some before the edit. It doesn't behave like this for the other fields like homepage. It doesn't appear to be a new bug, so it doesn't block this PR, but it would be good to fix it.

**Comment by eviljeff** [comment]
> 
> 
> While testing I noticed something weird/annoying: when you save, you get back to the edit product page, and the tags always show `None`, even if there were some before the edit. It doesn't behave like this for the other fields like homepage. It doesn't appear to be a new bug, so it doesn't block this PR, but it would be good to fix it.

that's weird! I didn't notice that during development

**Comment by eviljeff** [comment]
> While testing I noticed something weird/annoying: when you save, you get back to the edit product page, and the tags always show `None`, even if there were some before the edit. It doesn't behave like this for the other fields like homepage. It doesn't appear to be a new bug, so it doesn't block this PR, but it would be good to fix it.

I can't replicate this - it always updates correctly for me.  When you say it doesn't appear to be a new bug, do you mean you can replicate this now on addons-dev?  Or just locally?  (maybe you have something weird locally?)

**Comment by diox** [comment]
I had reproduced locally (on `master`) but after investigating, it's because my add-on is unlisted. `addons_section` has a `and show_listed` condition so the XHR that does the edit will not display tags for unlisted... But the section is present, and the form is displayed, and when submitted the data is saved, it's just not displayed at submission time, which is kinda weird.

**Review by diox — APPROVED** [review]

**Comment by eviljeff** [comment]
> I had reproduced locally (on `master`) but after investigating, it's because my add-on is unlisted. `addons_section` has a `and show_listed` condition so the XHR that does the edit will not display tags for unlisted... But the section is present, and the form is displayed, and when submitted the data is saved, it's just not displayed at submission time, which is kinda weird.

Oh, good spot.  I guess we never noticed.  Tags are pretty useless for unlisted but dropping the field can be for another issue (if we can be bothered - probably isn't worth it) so I'll just drop the condition in `addons_section`

**Pull request merged**
