### PR TITLE
/api/v4/reviews/ to /api/v4/ratings/

### LINKED ISSUE #6847: "Abstract" category is returning 500 error page at Static Theme submission
Steps to reproduce:
1. Select a static theme to submit in AMO-dev
2. At details step, pick "Abstract" category
3. Finalize submission

Expected results:
Submission is finalized with succes.

Actual results:
An "Oops..." page is displayed at "Submit version" click.

Notes/Issues:
- did not try all categories

Verified on AMO-dev FF56(Win 7).
Video for this issue:

### LINKED ISSUE #6849: Change API url for reviews to ratings
After https://github.com/mozilla/addons-server/issues/6761 the `reviews` app will have been renamed to `ratings`. Let's also change the URLs for the API, exposing `/api/v3/ratings/`. Also, this may be a good time to expose the value of the rating as a `score` property instead of `rating`. Maybe accept/return both during the transition.

We'll need to keep backwards-compatibility for a little while to get addons-frontend updated.

### PR DESCRIPTION
**Pull request by eviljeff**
Fixes #6849

Apart from the `rating` to `score` property name on the serializer as that needs feature gates (#8255) and we've not done that yet.  Could have done it by checking `request.version` directly but do we want `if request.version == 'v3': .... elif request.version == 'v4': ....` in the code? It'd be a contentious implementation so left it out.

### CODE REVIEW

**Comment by diox** [comment]
Test duplication ends up being quite costly in terms of execution time, and it's just the beginning... Is that really what we want ? I'm not sure we have a better solution. Paging @EnTeQuAk for his feedback.

**Comment by eviljeff** [comment]
We could just test the default ('v4'), and then only test other versions when we know there are changes.  Doesn't account for weird edge cases where urls are used within the serializer and when we start having different changes in different APIs though.

Another option (that would be a lot of refactoring work) is to separate all the api tests from the non-api tests and run v3 and v4 as separate parallel jobs in Travis.

**Comment by eviljeff** [comment]
I suppose `ratings` was an edge case itself in that we were changing the actual url, rather than functionality.  Perhaps a check that the url resolves for both v3 and v4; is the correct url; and if it's used in the response is correct; is sufficient without testing the actual functionality of the API.

When we're making feature changes we can just test the feature gates in circumstances where the gates are used.

**Comment by diox** [comment]
Yeah, something like that would be enough I think.

**Comment by eviljeff** [comment]
https://github.com/mozilla/addons-server/pull/8303/commits/8c83e2e78c71475757b904147d586aeaf7bbf4ea removes the test duplication

**Pull request merged**
