### PR TITLE
Added extension workshop link to devhub menu

### LINKED ISSUE #10909: Add links to extension workshop from main header
UX to define placement and copy - here's a copy of the header for reference.

Manage_My_Submissions____Developer_Hub____Add-ons_for_Firefox

### PR DESCRIPTION
**Pull request by Anushka28**
Fixes #10909

### CODE REVIEW

**Comment by caitmuenster** [comment]
Thank you for the patch, @Anushka28! Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition). 🎉

Would you be interested in creating an account on mozillians.org? I'd be happy to vouch for you!

**Comment by Anushka28** [comment]
welcome @caitmuenster ! I am surely interested to be a part of mozillians.org

**Comment by Anushka28** [comment]
thank you @championshuttler . You were a big support!

**Comment by caitmuenster** [comment]
> welcome @caitmuenster ! I am surely interested to be a part of mozillians.org

Yay! If you could create an account and send me the link to it, I'll finish the vouching process. :)

**Comment by Anushka28** [comment]
> > welcome @caitmuenster ! I am surely interested to be a part of mozillians.org
> 
> Yay! If you could create an account and send me the link to it, I'll finish the vouching process. :)

here it is. https://mozillians.org/en-US/u/anushka28/

**Comment by caitmuenster** [comment]
Thanks! You are vouched. ✨

Welcome onboard! I look forward to seeing you around the project.

**Comment by Anushka28** [comment]
> Thanks! You are vouched. sparkles
> 
> Welcome onboard! I look forward to seeing you around the project.

Amazing :)

**Pull request merged**
