### PR TITLE
Implement All CircleCI tests in github actions

### PR DESCRIPTION
**Pull request by KevinMind**
Fixes: [AMOENG-599](https://mozilla-hub.atlassian.net/browse/AMOENG-599)

### Description

This is the first PR in the final phase of the gha migration. It implements parity between circle ci and github actions for tests. All tests run in circle ci are also run in github actions.

### Context

After merging this there are follow ups for finalizing the migration and for improving performance. Though we are at near parity with circle CI (while building the docker container so actually faster already).

This PR includes 2 sub PRs that could be merged before or with this one:

- https://github.com/mozilla/addons-server/pull/22280
- https://github.com/mozilla/addons-server/pull/22299

### CODE REVIEW

**Comment by KevinMind** [comment]
Follow ups after this PR would be:
- remove circle ci tests
- reorganize test division for optimal performance
- enable "auto" for core splitting in pytest

Dependency related (can be inclusive or exclusive)

- cache ./deps directory in ci runs to speed up installation
- use "development" "production" targets to speed up installation
- integrate installation of dev deps to startup process with "deps_container" in compose

**Comment by wagnerand** [comment]
`COMPOSE_FILE=docker-compose.yml:docker-compose.private.yml make up` seems to work fine, thanks!

**Review by diox — APPROVED** [review]
:rocket:

**Comment by willdurand** [comment]
> Fixes: [AMOENG-599](https://mozilla-hub.atlassian.net/browse/AMOENG-599)

Can we please reference GitHub issues here?

**Comment by KevinMind** [comment]
@willdurand this is one of the issues without a github issue.

**Pull request merged**
