### PR TITLE
Fix function declarations with mutable default arguments

### LINKED ISSUE #3553: Fix function declarations that use a mutable type default
wat

```fgrep 'def ' * -r --include="*.py" | egrep '\[\]|\{\}'```
```
src/olympia/tags/tests/test_helpers.py:def render(s, context={}):
src/olympia/tags/helpers.py:def tag_list(context, addon, tags=[]):
src/olympia/users/models.py:    def update_or_create(update={}, **kwargs):
src/olympia/users/models.py:def watch_email(old_attr={}, new_attr={}, instance=None,
src/olympia/translations/fields.py:    def adapt(cls, opts={}):
src/olympia/legacy_api/views.py:def render_xml_to_string(request, template, context={}):
src/olympia/legacy_api/views.py:def render_xml(request, template, context={}, **kwargs):
src/olympia/addons/tests/test_views.py:    def get_url(self, args=[]):
src/olympia/addons/models.py:    def valid_q(self, status=[], prefix=''):
src/olympia/addons/models.py:    def get_detail_url(self, action='detail', args=[]):
src/olympia/addons/models.py:def watch_status(old_attr={}, new_attr={}, instance=None,
src/olympia/addons/models.py:def watch_disabled(old_attr={}, new_attr={}, instance=None, sender=None, **kw):
src/olympia/addons/models.py:def watch_developer_notes(old_attr={}, new_attr={}, instance=None, sender=None,
src/olympia/addons/models.py:def track_status_change(old_attr={}, new_attr={}, **kw):
src/olympia/addons/helpers.py:def impala_addon_listing_header(context, url_base, sort_opts={}, selected=None,
src/olympia/reviews/tests/test_helpers.py:    def render(self, s, context={}):
src/olympia/paypal/tests/test_views.py:    def post(self, url, data={}, **kw):
src/olympia/activity/tests/test_serializers.py:    def serialize(self, context={}):
src/olympia/devhub/tests/test_views_edit.py:    def check_dep_ids(self, expected=[]):
src/olympia/devhub/models.py:    def arguments(self, args=[]):
src/olympia/devhub/helpers.py:def dev_addon_listing_items(context, addons, src=None, notes={}):
src/olympia/bandwagon/views.py:def render_cat(request, template, data={}, extra={}):
src/olympia/bandwagon/models.py:    def set_addons(self, addon_ids, comments={}):
src/olympia/bandwagon/helpers.py:def user_collection_list(collections=[], heading='', id='', link=None):
src/olympia/versions/models.py:def watch_source(old_attr={}, new_attr={}, instance=None, sender=None, **kw):
src/olympia/amo/tests/test_helpers.py:def render(s, context={}):
src/olympia/amo/models.py:            def watch_status(old_attr={}, new_attr={},
src/olympia/editors/tests/test_views.py:    def _test_breadcrumbs(self, expected=[]):
src/olympia/editors/tests/test_views.py:    def generate_files(self, subset=[]):
src/olympia/editors/tests/test_views.py:    def get_url(self, args=[]):
src/olympia/editors/tests/test_views.py:    def generate_files(self, subset=[]):
src/olympia/editors/tests/test_views.py:    def generate_files(self, subset=[]):
src/olympia/editors/tests/test_helpers.py:    def setup_data(self, status, delete=[], is_listed=True):
src/olympia/search/tests/test_views.py:    def search_addons(self, url, params, addons=[], types=amo.ADDON_TYPES,
src/olympia/search/tests/test_views.py:    def search_addons(self, params, addons=[]):
src/olympia/search/tests/test_views.py:    def search_addons(self, params, addons=[],
src/olympia/search/tests/test_views.py:    def search_applications(self, params, apps=[]):
src/olympia/files/models.py:def track_status_change(old_attr={}, new_attr={}, **kw):
src/olympia/compat/tests.py:    def check_table(self, data={}, good=0, bad=0, appver=None, report_pks=[]):
```

### PR DESCRIPTION
**Pull request by diox**
Hopefully fix #3553 once and for all.

### CODE REVIEW

**Comment by muffinresearch** [comment]
Can we enhance the lint setup to ensure any future occurences fail the tests?

**Comment by diox** [comment]
mmm I don't really find the one-liner easier to read with its useless re-assignation in the `else` clause.

**Comment by diox** [comment]
Looks like https://pypi.python.org/pypi/flake8-mutable could find those issues for us, I'll test it.

**Comment by EnTeQuAk** [comment]
> mmm I don't really find the one-liner easier to read with its useless re-assignation in the else clause.

that is indeed useless. Unfortunately `foo or []` gives a different result (most of the time the same though).

**Comment by EnTeQuAk** [comment]
re r+ now with flake8-mutable and more fixes :)

**Pull request merged**
