### PR TITLE
rm AbuseReport.appeallant_job

### PR DESCRIPTION
**Pull request by eviljeff**
Fixes: mozilla/addons#14984

~blocked on https://github.com/mozilla/addons-server/pull/22582 - there will be merge conflicts.~

### Description

Drops the `appellant_job` fk, as well as `reporter_appeal_date`, that was effectively unused (it was referenced in one place where `appellant_job` could have been used, and now `cinderappeal` can be instead).  DB migration to drop columns from the table can come in a later deploy.

### Testing

No particular testing, as it should be functionally the same, but to confirm you can:
- test the migration by:
  - have an abuse report with an original job and a decision that was appealed (so a new, appeal, cinder job), prior to checking out this patch (the AbuseReport would have `appellant_job` set to the appeal cinder job)
  - check out the patch so the migration runs
  - see there is now a CinderAppeal instance
- test abuse-related functionality by:
  - appealing a decision on a job as the reporter
  - checking you can't appeal the decision twice as a reporter
  - seeing that emails are sent out to reporter(s) that appeal a decision

### Checklist

- [x] Add `#ISSUENUM` at the top of your PR to an existing open issue in the mozilla/addons repository.
- [x] Successfully verified the change locally.
- [x] The change is covered by automated tests, or otherwise indicated why doing so is unnecessary/impossible.
- [ ] Add before and after screenshots (Only for changes that impact the UI).
- [ ] Add or update relevant [docs](../docs/) reflecting the changes made.

### CODE REVIEW

**Comment by KevinMind** [comment]
@eviljeff have you rebased/solved merge conflicts?

**Comment by KevinMind** [comment]
>  DB migration to drop columns from the table can come in a later deploy.

Is there a ticket for this. If not could you create and link?

**Comment by KevinMind** [comment]
Questions for QA:

> have an abuse report with an original job and a decision that was appealed (so a new, appeal, cinder job), prior to checking out this patch

Is it possible to create this state in the DB manually with dummy links to cinder? Just curious as that could save a large amount of setup time.

> see there is now a CinderAppeal instance

This is a smidge vague, how is it related to the original Abuse report? Like, how would I find the instance I'm looking for?

> appealing a decision on a job as the reporter

Could you provide some steps to reproduce this behavior?

**Comment by eviljeff** [comment]
> @eviljeff have you rebased/solved merge conflicts?

Yes, I rebased after that PR was merged.

**Comment by eviljeff** [comment]
> > DB migration to drop columns from the table can come in a later deploy.
> 
> Is there a ticket for this. If not could you create and link?

https://github.com/mozilla/addons/issues/14992

**Comment by eviljeff** [comment]
> Questions for QA:
> 
> > have an abuse report with an original job and a decision that was appealed (so a new, appeal, cinder job), prior to checking out this patch
> 
> Is it possible to create this state in the DB manually with dummy links to cinder? Just curious as that could save a large amount of setup time.

You can, but there are a few instances that need creating:
- an AbuseReport1 with `cinder_job` set to CinderJob1, and `appellant_job` set to CinderJob2.  guid set to an addon (Addon1) you have locally in Addon.unfiltered.
- CinderJob1 has `decision` set to CinderDecision1; target_addon set to Addon1
- CinderDecision has addon set to Addon1; action to any valid DECISION_ACTIONS; appeal_job set to CinderJob2.
- CinderJob2 has target_addon set to Addon1.

> > see there is now a CinderAppeal instance
> 
> This is a smidge vague, how is it related to the original Abuse report? Like, how would I find the instance I'm looking for?

It should be the latest instance, with a created date of now.  The instance's `.reporter_report` would fk to the AbuseReport, or via the back reference from AbuseReport in django shell, `,cinderappeal`

**Comment by eviljeff** [comment]
> > appealing a decision on a job as the reporter
> 
> Could you provide some steps to reproduce this behavior?

You will need cinder api integration set up.  After that:
- file an abuse report against an add-on you have locally.  Choose reason: "it violates Add-on policies" and place: inside the  Add-on.  You either need to be logged in, or provide an email address for the reporter.
- resolve the report in the reviewer tools with either the action "Resolve Reports" and the policy Approve, or the actions "Confirm Auto Approved" or "Approve", and check the checkbox for the job.
- Then look in fake mail in django admin, for the email to the reporter - it will have a link to appeal in it.
- Open that link, and fill out some justification and send the appeal.

**Comment by KevinMind** [comment]
> resolve the report in the reviewer tools with either the action "Resolve Reports" and the policy Approve, or the actions "Confirm Auto Approved" or "Approve", and check the checkbox for the job.

Was not able to see the action "Resolve Reports"... so stuck at this step.

**Review by KevinMind — APPROVED** [review]
LGTM

**Pull request merged**
