### PR TITLE
Revert "Revert "rename whitelist to allow list""

### PR DESCRIPTION
**Pull request by muffinresearch**
Reverts the revert in mozilla/addons-server#3904 now that the env var is available.

From irc: 

```
wezhou> muffinresearch: regarding https://github.com/mozilla/addons-server/pull/3904 i've 
added the EMAIL_QA_ALLOW_LIST env variable. Please try again sometime.
```

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
r+

**Comment by muffinresearch** [comment]
I'm going to leave this until after the tag so we can deal with #3895 env updates at the same time. Should make it a bit easier for Ops.

**Comment by andymckay** [comment]
I think @bqbn has to do https://bugzilla.mozilla.org/show_bug.cgi?id=1313786 or has that been done?

**Comment by muffinresearch** [comment]
> I think @bqbn has to do https://bugzilla.mozilla.org/show_bug.cgi?id=1313786 or has that been done?

That's been done - see the note from irc in the description.

**Pull request merged**
