### PR TITLE
Fixed double spaces on line 190

### LINKED ISSUE #3601: Double space in faq
Hello, 

while translating AMO on Pontoon I have found a marginal bug - in file src/olympia/pages/templates/pages/faq.html there are double spaces on line 190.

Greetings
Tomáš Zelina

### PR DESCRIPTION
**Pull request by zelitomas**
Fixes #3601

### CODE REVIEW

**Comment by tofumatt** [comment]
In the future please use "fixes #3601" instead of "bug #3601" as once the PR is merged it will automatically close the issue, thanks!

**Comment by tofumatt** [comment]
Will this change in string cause this string to be untranslated for other languages until developers get to it? That'd be a shame for an extra space when that won't even be output in the HTML.

Just something to consider.

**Comment by EnTeQuAk** [comment]
This change will render all translations fuzzy imho so we'd have to consider this. I tend more to not change it unless there's actual string changes neccessary to avoid any needless translation work for others.

**Comment by tofumatt** [comment]
Alright, let's not merge this one then. I don't want to create needless work either.

**Pull request closed without merging**
