### PR TITLE
Test: Do not merge

### PR DESCRIPTION
**Pull request by Krchrdt**
This is a test of how forked PRs run in our CI. 

This is a dummy user from @KevinMind FYI.

### CODE REVIEW

**Comment by KevinMind** [comment]
@eviljeff why did you close this? I'm still using it for testing.

**Comment by KevinMind** [comment]
Is that standard practice for PRs that come in that are missing info? Or was it the commit messages that spooked you? I'm curious what your thought process was in that decision.

**Comment by eviljeff** [comment]
> Is that standard practice for PRs that come in that are missing info? Or was it the commit messages that spooked you? I'm curious what your thought process was in that decision.

It was indistinguishable from spam - I almost flagged it as such with github but the form was long so I figured I'd do it if this random anonymous user did it again.

**Comment by KevinMind** [comment]
Okay, makes sense. Probably would have been good to note your intention in a comment to reduce any confusion, I was confused. But probably the right action to take. At minimum asking "hey, who are you and what are you doing" but idk how often we get spammed and how tired you are of dealing with it.

**Pull request closed without merging**
