### PR TITLE
Solving issue #8071

### LINKED ISSUE #8071: When signing out of /developers/addons the user should land on DevHub homepage instead of AMO
Follow up for #4562 

STR:

1. Log in to Developer Hub
2. Navigate to https://addons-dev.allizom.org/en-US/developers/addons
3. Sign out

Actual result:
User is redirected to AMO homepage when signing out of /developers/addons

Expected result:
User is redirected to DevHub homepage when signing out of /developers/addons

Notes:
reproduced on all AMO servers with FF59, Win10x64

dev hub log out

### PR DESCRIPTION
**Pull request by piyushmittal25**
Fixes #8071.
@EnTeQuAk I think its perfect now.

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
So, as you can see by looking at the travis tests this doesn't work either. Did you actually test this on your local machine? That'd help catching this error earlier.

https://travis-ci.org/mozilla/addons-server/jobs/385208189#L9952-L9991

I'll give this a more in-depth look tomorrow morning and see if I have an idea about a better way to fix this. Feel free to give this another go anytime though!

Also, no need to close and open a new pull request all the time. Please just update your existing branch and we'll see the changes you do.

**Comment by piyushmittal25** [comment]
@EnTeQuAk
   Okk i will do it.

**Comment by EnTeQuAk** [comment]
Hey @piyushmittal25, how is it going? Do you need any help finishing up this pull request?

**Comment by piyushmittal25** [comment]
@EnTeQuAk  
Sorry, For the delay and I very very sorry because this small issue is pending because of me.

**Comment by piyushmittal25** [comment]
@EnTeQuAk 
  Thank you very much for helping me and I really appreciate you and your character it's nice to work with you. I had sent you a connection request on LinkedIn if you use it then please respond on it.

**Pull request merged**
