### PR TITLE
Updates text on dev hub landing page.

### LINKED ISSUE #5887: Update text on dev hub landing page
SIGNED-IN VIEW:

In the What's New promo box at the top, please replace the text block that starts with "Migrating your legacy add-on to WebExtensions?" with the following text:
- Ready to submit an add-on? Read our step-by-step tutorial on the submission process.
- Button: [See Tutorial](https://developer.mozilla.org/en-US/Add-ons/Distribution/Submitting_an_add-on)

SIGNED-OUT VIEW:

In the big blue box under the header "Tools", change the link associated with the text "Compatibility Checker" from https://compatibility-lookup.services.mozilla.com/ to https://addons.mozilla.org/developers/addon/check-compatibility

In the "Evolution in Add-on Development" promo box, change the text to:
- Header: Update Your Legacy Extension
- Body: There is a new, cross-browser standard for developing extensions in Firefox. You'll need to update your legacy extensions to stay compatible.

### PR DESCRIPTION
**Pull request by apoorvaeternity**
Fixes #5887

### CODE REVIEW

**Comment by wagnerand** [comment]
Thank you @apoorvaeternity.

The changes look good to me, would you mind uploading a screenshot for both signed-in and signed-out view for @atsay to cross check?

**Comment by apoorvaeternity** [comment]
@atsay Is it fine?
SIGNED-IN VIEW
signed_in

SIGNED-OUT VIEW
signed_out1

signed_out2

**Comment by atsay** [comment]
This is awesome, thanks so much for fixing this @apoorvaeternity! Looking at the signed-in view, I realize we should also change the promo on the right that starts with "WebExtensions are now the standard..." with this text: "There is a new, cross-browser standard for developing extensions in Firefox. You'll need to update your legacy extensions to stay compatible."

Should I file a separate issue, or can we change it as part of this PR?

**Comment by apoorvaeternity** [comment]
You're welcome @atsay. I don't think there is any need to file another issue I can change it as a part of this PR.

**Comment by apoorvaeternity** [comment]
@atsay After previous commit---
changes

**Comment by apoorvaeternity** [comment]
This PR is ready to get merged.

**Comment by wagnerand** [comment]
Thank you @apoorvaeternity!

**Pull request merged**
