### PR TITLE
enable sitemap generation cron

### LINKED ISSUE #16906: add `write_sitemaps` to crontab
follow-up for #16508 

when we're ready and happy to have the sitemaps generated on a schedule we need to add `write_sitemaps` to `crontab.tpl`

### PR DESCRIPTION
**Pull request by eviljeff**
fixes #16906 - the timing is arbitrary, I just picked a time after the stats crons finish.  (Might be too late in the day then?)

### CODE REVIEW

**Comment by diox** [comment]
Since is this going to take a while, might want to give ops a heads up about it (and see if the time matters for them)

**Comment by eviljeff** [comment]
@bqbn to r+ the time the cron runs

**Comment by eviljeff** [comment]
We probably want the PR for #17143 to be merged before this, too (or we'll be generating a lot more sitemap than necessary)

**Comment by bqbn** [comment]
> @bqbn to r+ the time the cron runs

For my info, does it need to run during a certain time window in a day, or any time in a day works?

One comment is to put this line above  the `0 22 * * * %(z_cron)s gc` line, so these few lines are ordered by time when they run.

**Comment by eviljeff** [comment]
> > @bqbn to r+ the time the cron runs
> 
> For my info, does it need to run during a certain time window in a day, or any time in a day works?

any time of day - ideally when there's no much else going on.

**Comment by bqbn** [comment]
> any time of day - ideally when there's no much else going on.

Then I'd recommend 23:00 UTC, which is a good low traffic time.

**Review by bobsilverberg — APPROVED** [review]

**Pull request merged**
