### PR TITLE
Add test to verify comparing with deleted version works.

### LINKED ISSUE #12726: View a comparison for a deleted version in the reviewer API
### Describe the problem and steps to reproduce it:

As a reviewer, use the review tools to craft a Code Manager comparison link between a non-deleted version and a deleted version. You would have to edit the URL to craft this URL but a UI for this will be forthcoming.

Given this crafted URL: https://code.addons.mozilla.org/en-US/compare/989342/versions/3431730...3432145/

...here is the API request made by Code Manager:

```
https://addons.mozilla.org/api/v5/reviewers/addon/989342/versions/3431730/compare_to/3432145/?lang=en-US
```

### What happened?

The API returns a 404 and Code Manager cannot display anything.

### What did you expect to happen?

The API should not return a 404 so that Code Manager can display the comparison.

### Anything else we should know?

The old File Viewer would display a comparison like this.

See https://github.com/mozilla/addons-code-manager/issues/1159

### PR DESCRIPTION
**Pull request by EnTeQuAk**
Fixes #12726

The issue from #12726 is kinda a "worksforme" - you need the `Addons:ViewDeleted` permission to do such comparisons.

Maybe that'll make #12725 clearer too but I'll add another test to verify it's working as expected too.

pinging @bobsilverberg and @wagnerand to make sure that's the expected behavior and works for everyone.

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
Thanks @wagnerand, I investigated further and in that specific add-on, the versions in the original report simply don't exist anymore (they seem to be hard-deleted).

Testing this further, in this specific addon…

Screenshot_2020-02-03 New Query

And running a compare between these two versions…

https://code.addons.mozilla.org/en-US/compare/989342/versions/4894835...4894865/

works perfectly with the correct permissions.

Am I missing something?

**Comment by wagnerand** [comment]
@EnTeQuAk I'm not sure I can confirm that. The file seems soft-deleted. I can still download it from the reviewer tools and the old file viewer displays the file just fine.

**Comment by EnTeQuAk** [comment]
So, thanks to @wagnerand we figured out that the ids used in the reported URL are the file-ids, not the version ids.

https://www.irccloud.com/pastebin/dvLkS99V/

That's the reason why we were seeing a 404.

**Comment by bobsilverberg** [comment]
Thanks for taking care of this @EnTeQuAk and @wagnerand!

**Pull request merged**
