### PR TITLE
use modern syntax in gen-cron.py; format consistently

### LINKED ISSUE #18666: gen-cron.py script isn't python3
When adding a crontab entry, and double checking how the template was parsed I noted that `gen-cron.py`, that's used by ops deployment scripts to generate the cron file, is using syntax that was removed in python 3.  That should be updated.

### PR DESCRIPTION
**Pull request by eviljeff**
fixes #18666

### CODE REVIEW

**Comment by eviljeff** [comment]
@bqbn one thing that occurs to me, https://github.com/mozilla-services/cloudops-deployment/blob/master/projects/addons-server/ansible/playbooks/tasks/deploy_commands_admin.yml#L44 runs this script and it's (presumably) not been failing despite using syntax that fails in modern python.  So what version of python is being used to run that?

(if the answer is python2.7, and we can't/don't want to change that, I need to drop the `f'...'` strings because they don't exist in python2.7)

**Comment by diox** [comment]
The ansible playbook always explicitly passes the `-p` argument when generating the cron, so we avoiding the issue.

**Comment by eviljeff** [comment]
> The ansible playbook always explicitly passes the `-p` argument when generating the cron, so we avoiding the issue.

the invalid in python3 syntax is when `-u` is passed

**Comment by diox** [comment]
Oh right, there were 2 issues here, I thought you meant the `python2.7` binary used by default would not exist...

**Review by diox — APPROVED** [review]
A simple test proving that the script can be run (the way we do it right now, at least) would be nice.

Need @bqbn to weigh in on the python executable question, but IMHO we should ensure everything uses Python 3.

**Comment by bqbn** [comment]
> So what version of python is being used to run that?
> 

Python v2.7. 

The `gen-cron.py` script is executed on the admin instance not in a container thus it uses the Python that comes with the OS. And the reason for running `gen-cron.py` on the instance not in a container is because we need to put those cron jobs on the instance's cron table and run them in containers.

We aren't upgrading Python before moving to GCP so please drop the f-string usage.

**Pull request merged**
