### PR TITLE
Increase sleep in CircleCI to see if it improves the intermittent failures

### PR DESCRIPTION
**Pull request by davehunt**
@EnTeQuAk care to review? I'll retrigger the CircleCI build that this pull causes a few times to see if we have some improved consistency in the results.

### CODE REVIEW

**Comment by davehunt** [comment]
Failed on the very first run. I suspect the issue might not be timing related. 😞

**Comment by davehunt** [comment]
Here's the full traceback, which appears to be fairly consistent. Any thoughts on why this might be happening? @EnTeQuAk, @muffinresearch? All the logs can be found [here](https://circleci.com/gh/mozilla/addons-server/280#artifacts).

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/deps/src/django-mobility/mobility/decorators.py", line 49, in wrapper
    return normal_fn(request, *args, **kw)
  File "/code/src/olympia/addons/views.py", line 359, in home
    'src': 'homepage', 'collections': collections})
  File "/usr/lib/python2.7/site-packages/django/shortcuts.py", line 50, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/usr/lib/python2.7/site-packages/django/template/loader.py", line 178, in render_to_string
    return t.render(context_instance)
  File "/usr/lib/python2.7/site-packages/jingo/__init__.py", line 99, in render
    return super(Template, self).render(context_dict)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/code/src/olympia/addons/templates/addons/home.html", line 8, in top-level template code
    {% set view_all = {
  File "/code/src/olympia/../../src/olympia/templates/impala/base_shared.html", line 1, in top-level template code
    {% extends 'impala/base.html' %}
  File "/code/src/olympia/../../src/olympia/templates/impala/base.html", line 63, in top-level template code
    {% block site_header %}
  File "/code/src/olympia/../../src/olympia/templates/impala/base.html", line 98, in block "site_header"
    {% block site_header_title %}
  File "/code/src/olympia/../../src/olympia/templates/impala/base.html", line 99, in block "site_header_title"
    {% include "impala/header_title.html" %}
  File "/code/src/olympia/../../src/olympia/templates/impala/header_title.html", line 13, in top-level template code
    {{ heading('Firefox', _('Add-ons'), 'firefox') }}
  File "/code/src/olympia/../../src/olympia/templates/impala/header_title.html", line 4, in template
    {% if waffle.flag ('restyle') and request.APP == amo.FIREFOX %}
  File "/usr/lib/python2.7/site-packages/waffle/jinja.py", line 10, in flag_helper
    return flag_is_active(context['request'], flag_name)
  File "/usr/lib/python2.7/site-packages/waffle/__init__.py", line 32, in flag_is_active
    flag = Flag.objects.get(name=flag_name)
  File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 351, in get
    num = len(clone)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/usr/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 701, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 787, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 129, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1146, "Table 'olympia.waffle_flag' doesn't exist")
```

**Comment by davehunt** [comment]
Adding @andymckay for help too.

**Comment by EnTeQuAk** [comment]
Sorry, I'm at EuroPython currently. I'll have a more in-depth look at it tomorrow morning CEST

**Comment by EnTeQuAk** [comment]
hmm, looking at the logs and configuration doesn't show anything obvious to me. I'm trying to run / reproduce this locally, did you somehow manage to reproduce / test this on your machine or is it only failing on circle-ci?

**Comment by davehunt** [comment]
I've not replicated this locally, however it seems pretty frequent on Circle CI. Is there additional debug we could add to this pull to help diagnose?

**Comment by EnTeQuAk** [comment]
Hmm, I would try to add as many `echo` and prints everywhere. Some more places that might give us some insight:

* put `set -x` to the beginning of https://github.com/mozilla/addons-server/blob/master/scripts/setup-docker.sh so we can see what get's executed on setup and if this script get's executed even properly
* Try to pipe the output of the setup scripts (I'm honestly not sure, are they visible in circle ci logs somewhere already?) somewhere and check if they error out for some reasons

I feel like, if it's not a timing error (not waiting long enough) it could be something like an ordering problem that we're running the setup before mysql get's started or something like that. Log all the things! :laughing:

**Comment by muffinresearch** [comment]
As @EnTeQuAk says, it's probably something not ready, `docker-compose up -d` will likely return prior to everything being actually ready. 

You could try moving the sleep up before the setup script to see if that helps?

**Comment by davehunt** [comment]
I've activated debugging for the setup-docker.sh script, though any issues running this should have been highlighted in CircleCI anyway. I've also added a 2 minute sleep after calling `docker-compose up` to see if this helps.

**Comment by davehunt** [comment]
Okay, https://circleci.com/gh/mozilla/addons-server/437 passed. I'm going to retrigger it a few times though.

**Comment by davehunt** [comment]
- [x] https://circleci.com/gh/mozilla/addons-server/437
- [ ] https://circleci.com/gh/mozilla/addons-server/438
- [ ] https://circleci.com/gh/mozilla/addons-server/439
- [ ] https://circleci.com/gh/mozilla/addons-server/440
- [ ] https://circleci.com/gh/mozilla/addons-server/441

**Comment by davehunt** [comment]
Awesome, 5/5 after adding the extra sleep. I'll try removing the second sleep and reducing the first one to 1 minute. Hopefully that will still be enough.

**Comment by davehunt** [comment]
- [ ] https://circleci.com/gh/mozilla/addons-server/445
- [ ] https://circleci.com/gh/mozilla/addons-server/446
- [ ] https://circleci.com/gh/mozilla/addons-server/447
- [ ] https://circleci.com/gh/mozilla/addons-server/448
- [ ] https://circleci.com/gh/mozilla/addons-server/449

**Comment by davehunt** [comment]
Could be I've just been lucky, but 5/5 seems pretty good to me. @EnTeQuAk could we merge this and deal with any failures as/when they occur? Thanks @muffinresearch for the tip on moving the sleep!

**Comment by EnTeQuAk** [comment]
oh my, that's wonderful and so easy. Thanks @muffinresearch!

@davedash lgtm! :smiley:

**Pull request merged**
