### PR TITLE
Another go at fixing translations with wrong whitespaces and run extraction.

### PR DESCRIPTION
**Pull request by EnTeQuAk**
this time I did the following:

* normalize all message ids, strip whitespaces at all cost
* restore known missing translations
* run extraction again to ensure we have the latest strings
* tried to make sure we're not deleting anything
* run translation restoration again, just to make sure we're not missing anything
* run extraction again to make sure we finally format and extract everything again and have everythning formatted the way it's supposed to be.

From my tests it appears this finally resolves any wrong message ids, restores old translations where possible but doesn't touch recently translated messages.

Please let me know what you think.

### CODE REVIEW

**Comment by muffinresearch** [comment]
There's some slightly weird lines in the diff of `locale/af/LC_MESSAGES/django.po` e.g:

```diff
 #: src/olympia/devhub/templates/devhub/addons/forms_shared/media.html:16
 msgid ""
-"Upload an icon for your add-on or choose from one of ours. The\n"
-"                      icon is displayed nearly everywhere your add-on is. Uploaded images\n"
-"                      must be one of the following image types: .png, .jpg.\n"
-"                      It is only relevant for listed add-ons."
+"Upload an icon for your add-on or choose from one of ours. The icon is displayed nearly everywhere your add-on is. Uploaded images must be one of the following image types: .pn
g, .jpg. It is only "
+"relevant for listed add-ons."
```

Are those ok. I seems like it might be better to split them up a bit more on more lines or just relying on wrapping since the first of the two lines is really long already.

**Comment by muffinresearch** [comment]
Can you re-base + fix the conflicts.

**Comment by muffinresearch** [comment]
Based the on the current PR diff it's really hard to sanely review a +120k / -177k line patch. 

If we need to land this today to ship on Thursday we'll need to provide as much information to QA as possible about what to test to validate this patch is OK e.g. examples of what was broken before and what to look for.

If it's not as urgent as that then we should take a bit more time to look through this. Also if there's specific things we should be looking out for as examples of what's being fixed that might help focus the reviews a bit.

**Comment by EnTeQuAk** [comment]
re https://github.com/mozilla/addons-server/pull/2427#issuecomment-211791962 - this is an example of this this PR actually fixes, we have weird whitespaces still in the `.po` files that don't belong there.

I don't have specific examples, afair this isn't anything QA can verify easily but we kinda rely on feedback from translators. I'm not compiling anything but just fixing up missing translations / whitespace issues so that translators can keep on translating again and we can compile / ship those next week probably.

**Comment by muffinresearch** [comment]
> @muffinresearch re https://github.com/mozilla/addons-server/pull/2427#issuecomment-211791962 - this is an example of this this PR actually fixes, we have weird whitespaces still in the `.po` files that don't belong there. The output is what the tools generate so I would not mess with that tbh.

Ok - that's a good reason to leave it as is then :+1: 

> I don't have specific examples, afair this isn't anything QA can verify easily but we kinda rely on feedback from translators. I'm not compiling anything but just fixing up missing translations / whitespace issues so that translators can keep on translating again and we can compile / ship those next week probably.

OK

> Does that sound reasonable?

It does.

**Comment by muffinresearch** [comment]
Sounds like squashing this and landing it is the next step and check with the l10n'ers that everything is looking ok.

r+wc

**Comment by muffinresearch** [comment]
On reflection Re: squashing it might not be a good idea - just in-case we need to access the specific whitespace change commit in isolation - I'll leave that up to you.

**Pull request merged**
