### PR TITLE
add heartbeat urls

### LINKED ISSUE #18510: Please add healthcheck URLs
### Describe the problem and steps to reproduce it:

Per https://mana.mozilla.org/wiki/display/SVCOPS/New+Service+Guide#NewServiceGuide-StandardEndpoints, all applications running in containers should support a few standard endpoints.

Although the addons-server supports the `__version__` endpoint, it does not support the following health check URLs,

* `/__heartbeat__`
* `/__lbheartbeat__`

Can we add them please?

### What happened?

The addons-frontend recently had an incident that has to do with using TCP port to monitor app health. We filed https://github.com/mozilla/addons-frontend/issues/11059 for it, and would like the addons-server to support the above two health check endpoints as well, so that we can start to using them.

### What did you expect to happen?

The addons-server should support the above said two health check URLs (per Mozilla standard).

### Anything else we should know?
n/a

### PR DESCRIPTION
**Pull request by eviljeff**
fixes #18510 
- repurposes `/services/monitor.json` as `/__heartbeat__` (but leaves the url alone as an alias for now)
- adds `/__lbheartbeat__`
- adds a database check for replica and primary databases.

### CODE REVIEW

**Comment by eviljeff** [comment]
Note for these urls to work locally they either need adding to https://github.com/mozilla/addons-frontend/blob/master/config/default.js or https://github.com/mozilla/addons-nginx/blob/master/addons.conf (I did the latter locally).  That's probably not necessary in general (they're useless locally) and if we keep services/monitor.json around, redundant.

**Comment by bqbn** [comment]
> fixes #18510
> 
> * repurposes `/services/monitor.json` as `/__heartbeat__` (but leaves the url alone as an alias for now)

I like the "alias" idea too. It provides flexibility while we transition monitoring to the other endpoint. We can remove it later.

**Comment by bqbn** [comment]
The load balancer is not able to send custom headers to the application, in particular, for value of the `HOST` header, it'll use the instance's internal IP. I'm not sure if you can make the the application recognize that.

Here is an example of the headers the ELB will send,

```
GET /__version__ HTTP/1.1
host: 172.31.14.247:4000
User-Agent: ELB-HealthChecker/1.0
Accept: */*
Connection: keep-alive
```

The above example currently works well with addons-frontend, but Django may be different.

**Comment by eviljeff** [comment]
> The load balancer is not able to send custom headers to the application, in particular, for value of the `HOST` header, it'll use the instance's internal IP. I'm not sure if you can make the the application recognize that.
> 
> Here is an example of the headers the ELB will send,
> 
> ```
> GET /__version__ HTTP/1.1
> host: 172.31.14.247:4000
> User-Agent: ELB-HealthChecker/1.0
> Accept: */*
> Connection: keep-alive
> ```

I'm not sure what you're asking/saying here @bqbn - you _want_ `/__heartbeat__` to take the host/headers into account?  Or you think (or know) that the checks taking place will fail or be inaccurate because of the host will be internal IP?

**Comment by bqbn** [comment]
> I'm not sure what you're asking/saying here @bqbn - you _want_ `/__heartbeat__` to take the host/headers into account? Or you think (or know) that the checks taking place will fail or be inaccurate because of the host will be internal IP?

I see the following error when mimicking the ELB checking the health check endpoint (I used `/services/monito.json` in this case).

```
Dec 16 17:04:31 ip-172-31-26-77.ec2.internal docker-addons[15414]: {"Timestamp": 1639674271885841152, "Type": "django.security.DisallowedHost", "Logger": "http_app_addons_dev", "Hostname": "ip-172-31-26-77.ec2.internal", "EnvVersion": "2.0", "Severity": 3, "Pid": 9, "Fields": {"status_code": 400, "request": "<WSGIRequest: HEAD '/services/monitor.json'>", "uid": "", "remoteAddressChain": "", "msg": "Invalid HTTP_HOST header: '172.31.26.77'. You may need to add '172.31.26.77' to ALLOWED_HOSTS."}, "severity": 500}
```

**Review by bobsilverberg — APPROVED** [review]
LGTM

**Comment by eviljeff** [comment]
> > I'm not sure what you're asking/saying here @bqbn - you _want_ `/__heartbeat__` to take the host/headers into account? Or you think (or know) that the checks taking place will fail or be inaccurate because of the host will be internal IP?
> 
> I see the following error when mimicking the ELB checking the health check endpoint (I used `/services/monito.json` in this case).
> 
> ```
> Dec 16 17:04:31 ip-172-31-26-77.ec2.internal docker-addons[15414]: {"Timestamp": 1639674271885841152, "Type": "django.security.DisallowedHost", "Logger": "http_app_addons_dev", "Hostname": "ip-172-31-26-77.ec2.internal", "EnvVersion": "2.0", "Severity": 3, "Pid": 9, "Fields": {"status_code": 400, "request": "<WSGIRequest: HEAD '/services/monitor.json'>", "uid": "", "remoteAddressChain": "", "msg": "Invalid HTTP_HOST header: '172.31.26.77'. You may need to add '172.31.26.77' to ALLOWED_HOSTS."}, "severity": 500}
> ```

Ah, I feared it might be something like that.  [`settings.ALLOWED_HOSTS`](https://docs.djangoproject.com/en/3.2/ref/settings/#allowed-hosts) is what hosts are allowed to make a request and it's checked in the base `HttpRequest` class, then enforced in django middleware (`CommonMiddleware` makes a `request.get_host()` call, which [triggers](https://github.com/django/django/blob/3.2.10/django/middleware/common.py#L48) the check).  

I.e. we can't simply add an `if ...` in our code - we either need to:
- override the `ALLOWED_HOSTS` setting for certain defined paths (hacky, and no support for temporarily overriding settings, outside of tests)
- monkey-patch `HttpRequest.get_host()` (or `django.http.request.validate_host`) to not raise for certain defined paths (even more hacky)
- drop `ALLOWED_HOSTS` setting  (set it to `['*']`); define our own `ALLOWED_HOSTS_ISH` setting; then create our own middleware that enforces that hosts are in `ALLOWED_HOSTS_ISH`, apart from certain defined paths.

**Comment by bqbn** [comment]
For the `__lbheartbeat__` endpoint only, can we add a health check middleware early in the middleware chain? What's suggested in https://stackoverflow.com/a/64623669 seems to be a reasonable solution IMHO.

For the `__heartbeat__` endpoint, it can be treated as any other endpoints because ELB won't need to access it.

**Comment by eviljeff** [comment]
@diox I implemented @bqbn's suggestion - does this seem ... okay to you?  (we don't listen for random paths in other middleware and return a response, to my knowledge)

**Comment by diox** [comment]
Not ideal, but that works. It's worth noting though, that python-dockerflow already provides that functionality through its `DockerflowMiddleware`. We should look into what it would take to use it instead, but it can be a separate issue - maybe even a good first bug. (Among other things it also implements `__version__`, so we would need to customize `DOCKERFLOW_VERSION_CALLBACK`, since our implementation is a little custom)

**Comment by eviljeff** [comment]
> Not ideal, but that works. It's worth noting though, that python-dockerflow already provides that functionality through its `DockerflowMiddleware`. We should look into what it would take to use it instead, but it can be a separate issue

agreed

> maybe even a good first bug.

Hah, hacking around in middleware wouldn't be my idea of a good first bug 

> (Among other things it also implements `__version__`, so we would need to customize `DOCKERFLOW_VERSION_CALLBACK`, since our implementation is a little custom)

Also our __heartbeat__ does different things and we may want to keep some of that.

**Pull request merged**
