### PR TITLE
Inconsistency removed

### PR DESCRIPTION
**Pull request by Divya063**
Fixes [mozilla/addons#447](https://github.com/mozilla/addons/issues/447)

### CODE REVIEW

**Comment by wagnerand** [comment]
This looks good, thank you. Could you please update your commit message to describe the actual change? Thanks!

**Comment by Divya063** [comment]
@wagnerand commit message updated

**Comment by wagnerand** [comment]
Thank you!

**Comment by caitmuenster** [comment]
Awesome! Thanks, @Divya063, and welcome onboard! Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition#August_2017).

If you'd like to create a profile on [mozillians.org](https://mozillians.org/en-US/), I'd be happy to vouch for you. :)

**Pull request merged**
