### PR TITLE
Remove support for overwriting `raise_on_failure` for XPI extraction.

### LINKED ISSUE #8505: Always let IOErrors be raised in zip file handling
In https://github.com/mozilla/addons-server/pull/8328 and others we let more exceptions be raised by the file viewer instead of hiding them. There is one more laying around:

https://github.com/mozilla/addons-server/blob/8e17250cf42c275799b3dc331102242c9f9a3544/src/olympia/files/utils.py#L602-L606

`BadZipFile` is probably fine catching but `IOError` is not. It turns out that the only (?) place where we set `raise_on_failure` to `False` is in the file viewer. We should try to remove that entirely and let those exceptions be raised.

### PR DESCRIPTION
**Pull request by EnTeQuAk**
This ´removes us catching random IOErrors during XPI extraction. We want
to see them, they should never happen.

Also, as we only do XPI extraction on the file-viewer this is low-risk
and doesn't affect regular uploads.

Fixes #8505

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
Can't properly see the test failures. Going to run the test-suite this afternoon locally or block on https://github.com/mozilla/addons-server/pull/8528

**Comment by eviljeff** [comment]
Yeah.... this broke the tests on master.  IMO it needs to be reverted if it can't be fixed on Monday morning.

**Comment by EnTeQuAk** [comment]
Travis ist currently just suuuuper flaky :/

**Comment by diox** [comment]
Test failures:

```
=================================== FAILURES ===================================
_____________________ TestFileViewer.test_recurse_contents _____________________
[gw0] linux2 -- Python 2.7.14 /home/travis/build/mozilla/addons-server/.tox/main/bin/python2.7
src/olympia/files/tests/test_file_viewer.py:69: in test_recurse_contents
    self.viewer.extract()
src/olympia/files/file_viewer.py:143: in extract
    self.src, self.dest, expand=True)
src/olympia/files/utils.py:804: in extract_xpi
    dest = extract_zip(src, remove=True)
src/olympia/files/utils.py:718: in extract_zip
    zip_file = SafeZip(source)
src/olympia/files/utils.py:595: in __init__
    self._is_valid = self.is_valid()
src/olympia/files/utils.py:605: in is_valid
    zip_file = zipfile.ZipFile(self.source, self.mode)
/opt/python/2.7.14/lib/python2.7/zipfile.py:770: in __init__
    self._RealGetContents()
/opt/python/2.7.14/lib/python2.7/zipfile.py:811: in _RealGetContents
    raise BadZipfile, "File is not a zip file"
E   BadZipfile: File is not a zip file
_________________ TestFileViewer.test_recurse_contents_of_zip __________________
[gw0] linux2 -- Python 2.7.14 /home/travis/build/mozilla/addons-server/.tox/main/bin/python2.7
src/olympia/files/tests/test_file_viewer.py:81: in test_recurse_contents_of_zip
    self.viewer.extract()
src/olympia/files/file_viewer.py:143: in extract
    self.src, self.dest, expand=True)
src/olympia/files/utils.py:804: in extract_xpi
    dest = extract_zip(src, remove=True)
src/olympia/files/utils.py:718: in extract_zip
    zip_file = SafeZip(source)
src/olympia/files/utils.py:595: in __init__
    self._is_valid = self.is_valid()
src/olympia/files/utils.py:605: in is_valid
    zip_file = zipfile.ZipFile(self.source, self.mode)
/opt/python/2.7.14/lib/python2.7/zipfile.py:770: in __init__
    self._RealGetContents()
/opt/python/2.7.14/lib/python2.7/zipfile.py:811: in _RealGetContents
    raise BadZipfile, "File is not a zip file"
E   BadZipfile: File is not a zip file
_____________________ TestFileViewer.test_recurse_extract ______________________
[gw0] linux2 -- Python 2.7.14 /home/travis/build/mozilla/addons-server/.tox/main/bin/python2.7
src/olympia/files/tests/test_file_viewer.py:64: in test_recurse_extract
    self.viewer.extract()
src/olympia/files/file_viewer.py:143: in extract
    self.src, self.dest, expand=True)
src/olympia/files/utils.py:804: in extract_xpi
    dest = extract_zip(src, remove=True)
src/olympia/files/utils.py:718: in extract_zip
    zip_file = SafeZip(source)
src/olympia/files/utils.py:595: in __init__
    self._is_valid = self.is_valid()
src/olympia/files/utils.py:605: in is_valid
    zip_file = zipfile.ZipFile(self.source, self.mode)
/opt/python/2.7.14/lib/python2.7/zipfile.py:770: in __init__
    self._RealGetContents()
/opt/python/2.7.14/lib/python2.7/zipfile.py:811: in _RealGetContents
    raise BadZipfile, "File is not a zip file"
E   BadZipfile: File is not a zip file
============== 3 failed, 2005 passed, 2 xfailed in 434.74 seconds ==============
```

**Pull request merged**
