### PR TITLE
Fix ERROR: Unexpected token: keyword (const) in devhub-all.js

### LINKED ISSUE #9322: Developer Hub pages do not have JS functionality (devhub-min.js is not getting generated)
### Describe the problem and steps to reproduce it:

- Open the Developer Console and go to the Network tab
- Load any developer hub page such as https://addons-dev.allizom.org/en-US/developers/addon/validate

### What happened?

The `devhub-min.js` bundle is a 404. Example: https://addons-dev-cdn.allizom.org/static/js/zamboni/devhub-min.js?build=4f4a94c0-5b8965d9

### What did you expect to happen?

It should not be a 404. This file defines JS functionality that the page relies on.

### Anything else we should know?

This is not a deploy issue. It started happening today and kept happening for each build. The `devhub-min.js` file is copied from the Docker container. When inspected, the file was not there https://irccloud.mozilla.com/pastebin/KCaMT0y8/

### PR DESCRIPTION
**Pull request by diox**
Fix #9322

### CODE REVIEW

**Comment by kumar303** [comment]
Did that syntax error actually cause the asset build to fail? I can't tell because of the `IOError`. It would be nice if you could also make the asset build fail in case someone adds another `const` in the future.

**Comment by diox** [comment]
It did not. The asset build script is an horrible legacy mess, I am leaving that exercise to someone else :)

**Comment by kumar303** [comment]
Fair enough 🤣  It will probably happen again so just in case anyone has the courage for diving in, it's here: https://github.com/mozilla/addons-server/issues/9326

**Comment by eviljeff** [comment]
`const` isn't valid now?  🙄

**Comment by diox** [comment]
We're using `uglify-js` and it's meant for ES5, so no `const`. For ES6 there is `uglify-es` but addons-server code is so ancient that switching is probably a bit risky...

**Pull request merged**
