### PR TITLE
bug 1385059: update to final text

### PR DESCRIPTION
**Pull request by groovecoder**
Final shield study consent page copy. Is this in time for Thursdays tag & release?

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
> Final shield study consent page copy. Is this in time for Thursdays tag & release?

It's not unfortunately, does this have to go out on Thursday?

**Comment by groovecoder** [comment]
If at all possible, please. ... We wanted to launch this Containers study a few weeks ago and it keeps slipping over seemingly minor things. 😢

**Comment by groovecoder** [comment]
Note: not minor things in this repo - just a bunch of minor things among various bugzilla bugs and formalities.

You all have been great and responsive to PRs! :clinking_glasses:

**Comment by EnTeQuAk** [comment]
Heh no worries, I do think we can cherry pick this PR, there are a few
others too. I'll talk to QA

On Wed, Aug 2, 2017, at 05:07 PM, luke crouch wrote:
> Note: not minor things in this repo - just a bunch of minor things
>       among various bugzilla bugs and formalities.> You all have been great and responsive to PRs! 🥂


> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].> 

Links:

  1. https://github.com/mozilla/addons-server/pull/6089#issuecomment-319701423

**Comment by groovecoder** [comment]
Thanks for the merge. Was this able to be cherry-picked?

**Comment by EnTeQuAk** [comment]
Yes, it's been cherry picked and once our deployment succeeded (which
might take a while because of reindexing cause we upgraded our search
engine) it'll be online

On Thu, Aug 3, 2017, at 08:15 PM, luke crouch wrote:
> Thanks for the merge. Was this able to be cherry-picked?


> — You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 

Links:

  1. https://github.com/mozilla/addons-server/pull/6089#issuecomment-320048817

**Comment by groovecoder** [comment]
Did the deployment succeed? I don't see the update copy (i.e., "Containers will NOT send information ...") at https://addons.mozilla.org/en-US/firefox/shield_study_15.

**Comment by EnTeQuAk** [comment]
Not yet, I'll update the ticket once it did. 


On Fri, Aug 4, 2017, at 04:38 PM, luke crouch wrote:
> Did the deployment succeed? I don't see the update copy (i.e.,
> "Containers will NOT send information ...") at
> https://addons.mozilla.org/en-US/firefox/shield_study_15.> — You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 

Links:

  1. https://github.com/mozilla/addons-server/pull/6089#issuecomment-320265942

**Comment by EnTeQuAk** [comment]
The new environment just got promoted so your changes are now live.

**Pull request merged**
