### PR TITLE
Limit AclPermissions that are available in production AMO

### LINKED ISSUE #5785: Prevent ACL permission checks on publicly accessible AMO instances
Our ACL permissions give us great power, that is only kept from being unleashed on the world by an Firefox Accounts cookie check.  We can limit who has those permissions, and make them as fine-grained as possible, but we're still exposing dangerous functionality on the web.  

It would be best to move that functionality behind a VPN, and making such permission checks fail is an easy way of securing the entire site with minimal changes.

### PR DESCRIPTION
**Pull request by eviljeff**
Fixes #5785

### CODE REVIEW

**Comment by diox** [comment]
> I should probably file an issue for this.

you should!

**Comment by eviljeff** [comment]
> >   I should probably file an issue for this.

> you should!

I did

**Comment by eviljeff** [comment]
merging is blocked on clarification of the VPN group - we either need to:
- drop the requirement for all users to be added to a special VPN group for dev, stage, prod, or 
- add everyone in Staff (at least) to the relevant groups.  

If we _do_ need to have special VPN groups we could arguably simplify our ACL handling - being added to that VPN group could take the place of being added to the staff group.  I prefer just dropping the VPN group.

**Comment by eviljeff** [comment]
blocked on #5909

**Comment by EnTeQuAk** [comment]
So, #5909 is a "cantfix" and our admin pages are now behind a VPN, is there anything else blocking this?

**Comment by eviljeff** [comment]
I'm going to close this for now.  It would still work but I'm not sure its worth the pain.  Problems include:
* any API requests with extra permissions are going to be blocked entirely without some way of frontend using the internal site.
* ideally we don't want to have to both add users to a VPN group via an ops request and also add users to our ACL groups via pestering Jorge/Stuart/Andreas.
* If a user has now a) got access to Mozilla VPN, with 2fa and b) been added by ops to a special vpn group, then our additional ACL checks are somewhat redundant.  (We could simplify).

I think post addons-frontend rollout when we understand what (if any) privileged API requests are needed; and people are more comfortable with using the admin via the VPN; would be a good time to revisit.

**Pull request closed without merging**
