### PR TITLE
pseudocode to give a clue about token generation

### PR DESCRIPTION
**Pull request by Alien426**
Using a library is overkill here.

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
I'm :-1: on this, the libraries does quite a bit more and does a lot of security checks for people to not mess things up. I don't like us to recommend a method that works around those checks since we can't assume people to know every aspect of JWT.

**Comment by Alien426** [comment]
Reasons against libraries:
- only for specific languages (people using a different language can only wonder what happens between input and output)
- another (unnecessary) abstraction layer that adds dependency
- pseudocode: 6 lines of code that any programmer can understand and adapt to their language
- library: 8 files with code (index.js, decode.js, sign.js, verify.js, JsonWebTokenError.js, NotBeforeError.js, timespan.js, TokenExpiredError.js)

What security check do you need for generating a token? You generate the string, it works. If it doesn't, whose security is compromised?!

One does not need "people to know every aspect of JWT". But in my mind it's preferable to have people who handle things on their own instead of handing it off to a library and getting "something" back.

**Comment by tofumatt** [comment]
> pseudocode: 6 lines of code that any programmer can understand and adapt to their language

I disagree. A lot of programmers don't fully grasp how security or things like token generation works, and even if they could they don't care. They just want something that works.

I believe that you find a library unneeded, but most developers (including myself) wouldn't. I don't understand that pseudocode and can make more sense of what's happening with the real code example.

Developers who already understand JWT will figure this out themselves, but the pseudocode just crowds the space. I'm also r- on this.

**Comment by EnTeQuAk** [comment]
I agree that the example does not take other languages into account but writing pseudocode here is the wrong way in my opinion. We should rather link to other libraries or the official JWT documentation in case someone want's to implement it on it's own.

I'm not neccessarily talking about security checks but rather validity-checks, take a look at https://github.com/auth0/node-jsonwebtoken/blob/master/sign.js - it's doing quite a bit before actually generating the signature and that's required to avoid people to mess things up.

**Pull request closed without merging**
