### PR TITLE
Remove fxa-auth waffle

### LINKED ISSUE #3081: Remove FxA waffle
Just remove the waffle but leave it working as-is.

### PR DESCRIPTION
**Pull request by mstriemer**
This removes the waffle and waffled off code. The removal of the migration flow will come later.

I'm not totally sure the tests will all pass.

Fixes #3081.

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
So much red, lovely :hamster: 

r+

**Comment by andymckay** [comment]
Does anything need to change in the documentation about how you run AMO locally or set up of AMO? I'm assuming also that the reliance on FxA means we should document that really AMO is no longer runnable by 3rd parties who might not have access to FxA (as far as I know no-one does this).

**Comment by mstriemer** [comment]
I filed https://github.com/mozilla/addons-server/issues/3093 to make sure the documentation gets updated.

As far as the effect this will have on running locally right now this shouldn't require any changes. You'll just have to migrate to FxA on first login.

Once we remove the migration it will cause some issues. I made a note in https://github.com/mozilla/addons-server/issues/3049 to modify the initialize script and look for things that depend on passwords.

Once the migration is gone this will indeed prevent 3rd parties from running AMO. Unless they can also run their own FxA which may be possible but I'm not sure.

**Comment by EnTeQuAk** [comment]
Which is actually really really bad imho. We have quite a few contributors and get more every now and then so we have to figure out a way to either mock that stuff away for local development (how complicated do you think is that @mstriemer, how much does FxA do for us currently API wise) or figure out how to run a FxA server on our docker config.

**Comment by andymckay** [comment]
As I understand it you should be able run Docker locally and use FxA as long as you use the correct hostname, see #2792).

But if you wanted to stand up a production copy of AMO called say cgrebs-cool-addons-store.com and start serving add-ons ofg it and connect to a production copy of FxA... then you'd be in trouble.

**Comment by mstriemer** [comment]
> As I understand it you should be able run Docker locally and use FxA as long as you use the correct hostname, see #2792).

This should indeed be the case. There's nothing special about how we run addons-server locally compared to contributors.

> But if you wanted to stand up a production copy of AMO called say cgrebs-cool-addons-store.com and start serving add-ons ofg it and connect to a production copy of FxA... then you'd be in trouble.

This is also right. We are "special" in the production case since you need to get the FxA team to manually add credentials to the DB or have an @mozilla.com email address to get dev credentials.

**Comment by EnTeQuAk** [comment]
ah okay, then I missed that it already works properly for local development. Nothing to worry then.

**Comment by muffinresearch** [comment]
more-red-than-green-award-sm

**Pull request merged**
