### PR TITLE
Remove old node 4 repo

### PR DESCRIPTION
**Pull request by wagnerand**
https://bugzilla.mozilla.org/show_bug.cgi?id=1323994#c4

How do we update existing Docker users to node6?

### CODE REVIEW

**Comment by bqbn** [comment]
@wagnerand what do you mean by updating existing Docker users?

**Comment by wagnerand** [comment]
@bqbn Ignore that question. Stuart explained it to me during the standup.

**Comment by muffinresearch** [comment]
@wagnerand I think this will require using the epel repo to get the same node version as prod e.g: https://github.com/mozilla/addons-server/blob/master/Dockerfile.deploy#L12,L14 - though one thing to watch for that might alter other deps.

In any case getting closer to the prod dockerfile is a good thing. To test this you could build it locally, see http://addons-server.readthedocs.io/en/latest/topics/install/docker.html#hacking-on-the-docker-image - or alternatively modify the Dockerfile to build from here instead of using the image https://github.com/mozilla/addons-server/blob/master/docker-compose.yml#L2 (change `image` to `build: .` temporarily)

**Comment by muffinresearch** [comment]
As discussed on irc, the EPEL repo is there implicitly so this is good to go, we'll need to validate having pulled down the newly built image.

**Comment by wagnerand** [comment]
VERIFIED after fixing #5380 that had broken Dockerhub for quite some time.

```
$ make shell
docker exec -t -i "addonsserver_web_1" bash
[root@2f5c1cce2f5f code]# node --version
v6.10.1
[root@2f5c1cce2f5f code]#
```

**Pull request merged**
