### PR TITLE
Fix featured add-on hover state (fix #2042)

### LINKED ISSUE #2042: Flickering issue when hovering over the last extension from "Featured" section of any add-on category
Steps to reproduce:
1. Load any add-on category on AMO-stage https://addons.allizom.org/en-US/firefox/extensions/download-management/
2. Hover over the last extension from the "Featured" section

Expected results:
There are no display or layout issues.

Actual results:
There is an intermittent flickering. 

Notes/Issues:
Verified on FF45(WIn 7). Issue is reproducing on AMO-stage and AMO-dev.
Screencast for this issue: http://screencast.com/t/eKNqIjMB

### PR DESCRIPTION
**Pull request by tofumatt**
Screenshot:

screenshot 2016-03-30 16 46 12

### CODE REVIEW

**Comment by muffinresearch** [comment]
Does this push content down on :hover?

**Comment by tofumatt** [comment]
Nope, it brings content up with a negative margin similar to the other hover cards, so everything stays in place.

**Comment by muffinresearch** [comment]
Looks like there's a lot of whitespace beneath the items to the left of the hovered one. Or is that just because the heading still has epic padding?

**Comment by tofumatt** [comment]
All the headings have epic padding here, there isn't a positive margin added here. On hover we just do a negative margin the size of the hovered cards (300px I think?).

Yeah those margins are big, but they're separate.

**Comment by muffinresearch** [comment]
Ok r+wc

**Comment by muffinresearch** [comment]
The big margins were already dealt with I think so it should be good in context with what's on master.

**Pull request merged**
