### PR TITLE
Fix not available and "Works with" buttons (fix #2062)

### LINKED ISSUE #2062: "Not available for Firefox" text is not corectly aligned inside a collection
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1.Find a collection containing incompatible addons(https://addons.allizom.org/en-US/firefox/collections/enkei/enkei/)
2.Observe the "Not available for Firexfox X" text

Expected results:
Text is correctly aligned

Actual results:
Text overlaps the addon frame

Please see screencast for this bug: http://screencast.com/t/T7JcTrQyRC
Reproducible on Stage and -dev

### PR DESCRIPTION
**Pull request by tofumatt**
Screenshots, compared to #2062:

screenshot 2016-03-30 15 51 26
screenshot 2016-03-30 15 44 38

### CODE REVIEW

**Comment by muffinresearch** [comment]
IMHO the `works with` bit is weird - it looks like a button when it doesn't do anything. That's a UX issue though. 

Should there be space between the buttons too?

r+wc

**Comment by tofumatt** [comment]
Agreed, but yeah we can sort the UX out a bit later.

Good point, I'll add space between the buttons in the header.

**Comment by tofumatt** [comment]
Updated header buttons with margin:
screenshot 2016-03-30 16 19 20

**Comment by muffinresearch** [comment]
r+

**Pull request merged**
