### PR TITLE
Update amo-validator to 1.10.41

### PR DESCRIPTION
**Pull request by EnTeQuAk**

### CODE REVIEW

**Comment by tofumatt** [comment]
r+

**Comment by EnTeQuAk** [comment]
yeah, circleci hates me now I guess, gonna ignore this in this PR

**Comment by wagnerand** [comment]
This is part of https://github.com/mozilla/addons-server/pull/3435.

**Comment by wagnerand** [comment]
Nevermind, the initial title deceived me.

**Pull request merged**
