### PR TITLE
Update links and contribution information

### PR DESCRIPTION
**Pull request by wagnerand**
r?

### CODE REVIEW

**Comment by muffinresearch** [comment]
See also https://github.com/mozilla/amo-validator/pull/406#issuecomment-194822909 which is also relevant to this.

**Comment by tofumatt** [comment]
r+

**Comment by muffinresearch** [comment]
There's another reference to olympia issues in src/olympia/devhub/templates/devhub/docs/policies-contact.html

**Comment by wagnerand** [comment]
Ah, thanks. I didn't look specifically for "olympia". It was mostly about the migration form bugzilla to github. While looking at that, I was doing some `s/olympia/addons-server/g` along the way.

**Comment by wagnerand** [comment]
@muffinresearch So, should this PR be blocked until we reach a decision about https://github.com/mozilla/amo-validator/pull/406#issuecomment-194822909 ?

**Comment by muffinresearch** [comment]
@wagnerand yep I'll run it past Andy and report back in this issue since if we're going to do it we might as well do it as part of this. If we go ahead I'll file some issues to make mozilla/addons readme more inviting.

**Comment by muffinresearch** [comment]
@wagnerand OK let's go for pointing to mozilla/addons for issues. I'll sort out something for the readme there.

**Comment by wagnerand** [comment]
Done.

**Pull request merged**
