### PR TITLE
Extract locales.

### PR DESCRIPTION
**Pull request by EnTeQuAk**
Mostly removes some strings from recent helpers removal, adds new addons-linter info message and refs #2796

### CODE REVIEW

**Comment by muffinresearch** [comment]
Separate issue but I wonder if the linter message should link to github so it's easier for people to file new issues?

**Comment by muffinresearch** [comment]
I see some of this is just wrapping changes. Is that configurable? The lines are quite wide which makes viewing the diffs harder.

**Comment by muffinresearch** [comment]
r+wc and assuming travis is happy.

more-red-than-green-award-sm

**Comment by EnTeQuAk** [comment]
> I see some of this is just wrapping changes. Is that configurable? The lines are quite wide which makes viewing the diffs harder.

yeah, I'll see if I can fix that somehow. It's us syncing styles with Pontoon, e.g whenever pontoon pushes changes it applies it's styles and we have to sync them. Hard to figure out all the configs one need to change since you don't see them directly.

**Comment by EnTeQuAk** [comment]
> Separate issue but I wonder if the linter message should link to github so it's easier for people to file new issues?

It actually does, the whole message is a link for simplicity reasons.

**Comment by muffinresearch** [comment]
> It actually does, the whole message is a link for simplicity reasons.

Ah perfect.

**Comment by milupo** [comment]
String is still untranslated.

**Comment by muffinresearch** [comment]
> String is still untranslated.
 
Yes because a translation hasn't been added yet: https://github.com/mozilla/addons-server/blob/master/locale/hsb/LC_MESSAGES/django.po#L4152

**Comment by milupo** [comment]
Thanks. I hope it will be added soon. I opened issue 2794 for my languages and now my languages are those ones where the string is still untranslated.

**Comment by milupo** [comment]
I don't understand that. Somebody had set this string to Suggested on Pontoon, both for hsb and dsb. Maybe this blocks resolving the problem.

**Comment by milupo** [comment]
Yes, I've just seen: dsb works because I set the string some hours ago from suggested to translated. But hsb has just been on Selected. I set it back and hope that we will be successful now.

**Comment by muffinresearch** [comment]
@milupo thanks - sounds like we should get the update in the not too distant.

**Comment by milupo** [comment]
Well, now, after a hard birth "nach schwerer Geburt" as we say in German :-), it finally works fine for both languages. Thank you all very much for your help - up to the next issue! :-)

**Comment by EnTeQuAk** [comment]
Sweet, glad it works now. Thanks for following up on this @milupo :)

**Pull request merged**
