### PR TITLE
Update sha256sum values for a few packages

### PR DESCRIPTION
**Pull request by bqbn**
pypi uses different packaging format for a few packages which results in
different sha256sum values.

@jasonthomas r?

### CODE REVIEW

**Comment by diox** [comment]
We should probably fix the packages we're hosting instead ? Also, you're not supposed to use pypi directly but rather pyrepo, which should be the default if you are using the `Makefile`

**Comment by EnTeQuAk** [comment]
Or is this PR about seamlessly switching away from pyrepo?

**Comment by bqbn** [comment]
@jasonthomas and I talked about moving away from pyrepo so we can maintain one less infrastructure piece, and thus this PR.

To @EnTeQuAk's question, yes, there is a PR in ops project to go with this one.

**Comment by EnTeQuAk** [comment]
Looks good to me. This only adds pypi related hashes so that we can switch and remove pyrepo related hashes later on. I also opened #2885 to remove pyrepo from our docker build and makefile if we're going to remove it from our infrastructure.

r+

**Comment by bqbn** [comment]
@EnTeQuAk r? again please?

The new commits, once merged, should address https://github.com/mozilla/addons-server/issues/2885 as well.

**Comment by EnTeQuAk** [comment]
Awesome, looks good to me and seems to be working. lgtm

r+

Can you squash your commits before merging please?

**Comment by bqbn** [comment]
Thanks @EnTeQuAk! Commits squashed and merged.

**Pull request merged**
