### PR TITLE
Wrap string in gettext (Fix #2795)

### LINKED ISSUE #2795: Section of DevHub page is not localised
https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/templates/devhub/index.html#L133 is missing a `{% trans %}` tag, as reported in #2794.

I'll fix this in like five minutes.

### PR DESCRIPTION
**Pull request by tofumatt**
Easy fix for #2795.

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
r+

**Comment by milupo** [comment]
Hi, I hope this is the right issue from 2794, 2795 and 2796. The string "There's no better way to distribute your add-on than by hosting it on Mozilla Add-ons." is not show translated for hsb and dsb though translated since yesterday. There are still translations into Indonesian, Slovenian, Ukrainian, German, Swedish, Russian. The fix works for theses languages? Why not for hsb and dsb? For me this issue is not fixed yet.

**Comment by muffinresearch** [comment]
@milupo that string isn't in the po file for hsb yet. That should get fixed with a fresh extraction.

**Comment by milupo** [comment]
Thanks. It's somewhat surprising. I am sure that I was the first one who translated this string before it was translated into other languages.

**Comment by EnTeQuAk** [comment]
it could have been me messing up a merge on yesterdays extract, sorry about that.

**Comment by milupo** [comment]
No problem. Thanks.

**Pull request merged**
