### PR TITLE
ADDSRV-735-github-pages

### PR DESCRIPTION
**Pull request by KevinMind**
Fixes: #21932

### Description

Adds a github action workflow for deploying our docs site to github pages. Effectively replacing readthedocs as a hosting provider.

### Context

This PR introduces a composite action setup-local to enable running CI commands in a github runner without needing to use the docker container. This can be faster and is more lightweight for actions that dont' explicitly need the full container running

In order for this change to work we have to enable redirects on readthedocs to maintain the domain name we currently have. These are already implemented and seem to be working.

### Testing

You can deploy this action by pushing to the branch or triggering the workflow via the gh cli.

### CODE REVIEW

**Comment by KevinMind** [comment]
Deploy works: https://github.com/mozilla/addons-server/actions/runs/8065272083/job/22030794977?pr=21937

**Comment by KevinMind** [comment]
> Can we see what the docs on github pages look like?
> 
> > In order for this change to work we have to enable redirects on readthedocs to maintain the domain name we currently have. These are already implemented and seem to be working.
> 
> Is this is a separate issue?

It's live right now https://mozilla.github.io/addons-server/

**Comment by eviljeff** [comment]
> > Can we see what the docs on github pages look like?
> > > In order for this change to work we have to enable redirects on readthedocs to maintain the domain name we currently have. These are already implemented and seem to be working.
> > 
> > 
> > Is this is a separate issue?
> 
> It's live right now https://mozilla.github.io/addons-server/

I meant is there a separate issue to enable redirects on readthedocs?  Or is it all set up already?

**Review by eviljeff — APPROVED** [review]
:shipit:

**Comment by diox** [comment]
Could you rename the title of this PR to be more descriptive before merging ?

**Pull request merged**
