### PR TITLE
Allow reviewers/authors to see deleted/unlisted add-ons in detail API

### PR DESCRIPTION
**Pull request by diox**

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
r+

**Comment by wagnerand** [comment]
Access to unlisted add-ons should only be allowed to users with `Addons:ReviewUnlisted` role.

I am not sure whether regular reviewers should have access to deleted add-ons, adding @jvillalobos.

**Comment by diox** [comment]
Ok, adjusting...

**Comment by diox** [comment]
@EnTeQuAk re-r ? I adjusted following @wagnerand's comment.

**Comment by EnTeQuAk** [comment]
re r+

I'd really prefer not squashing until we actually merge the PR, seeing the actual changes would make the review easier imho.

**Comment by diox** [comment]
Yeah I'm avoiding all squashs now, unless it really makes things more messy.

**Comment by jvillalobos** [comment]
I think regular reviewers shouldn't have access to deleted add-ons, more as a precaution than an actual concern.

**Pull request merged**
