### PR TITLE
Add e10s status to compatibility reports

### LINKED ISSUE #3122: Expand ACR endpoint to accept e10s statuses
There's a couple of possible statuses regarding e10s:
* Firefox has e10s turned on.
* The add-on has the multiprocessCompatible flag on/off or is unset.

We'll need to be sure we can recieve those, see mozilla/ACR for the issues to add that into the API.

It looks like this API is in src/olympia/devhub/views.py.

Supports: mozilla/addons#163

### PR DESCRIPTION
**Pull request by wagnerand**
Fixes #3122

### CODE REVIEW

**Comment by tofumatt** [comment]
This should output their status in an API response, right? Can you write a test (or extend an existing one) to make sure they appear?

**Comment by wagnerand** [comment]
I need to look into that. I am merely extending the model.

**Comment by tofumatt** [comment]
Right, but it makes sense to have the test for what you’re looking to
achieve in the same PR. :-)

**Comment by wagnerand** [comment]
Sure! (That last comment meant to say, 'will add a test'.)

**Comment by wagnerand** [comment]
✓ Tests added.

**Comment by tofumatt** [comment]
Looks good, but I stole `886` as the number for my migration, so can you change yours to `887`?

After that, r+wc

**Comment by wagnerand** [comment]
Done. Will merge when travis did its thing.

**Pull request merged**
