### PR TITLE
don't clear email and fxa on delete; reuse existing record on reregister

### LINKED ISSUE #14613: Don't clear email and fxa_id from UserProfile on delete
We currently clear the email address and fxa_id from a UserProfile instance on delete, and rely on logging to keep track of them.  It will make querying easier if we just retain the email address and fxa_id, and only clear them later in line with our data retention policies.

### PR DESCRIPTION
**Pull request by eviljeff**
fixes #14613 

Needs to land at the same time as the fix for #14549 or the "new" account registered by the user will contain content from the "old" account.

### CODE REVIEW

**Comment by diox** [comment]
> Needs to land at the same time as the fix for #14549 or the "new" account registered by the user will contain content from the "old" account.

There is no PR yet for that issue right ?

**Comment by eviljeff** [comment]
> 
> 
> > Needs to land at the same time as the fix for #14549 or the "new" account registered by the user will contain content from the "old" account.
> 
> There is no PR yet for that issue right ?

no

**Comment by diox** [comment]
So do we really want to merge this now, knowing we aren't deleting the content yet ?

**Comment by eviljeff** [comment]
> So do we really want to merge this now, knowing we aren't deleting the content yet ?

We don't.

**Comment by eviljeff** [comment]
should be merged with #14678 and mozilla/addons-frontend#9477

**Pull request merged**
