### PR TITLE
Only display reasons select when needed

### LINKED ISSUE #18288: Only display the reason select where is it needed
This is a follow-up from https://github.com/mozilla/addons-server/issues/18233.

A reason is only required (and relevant) for the following actions:
* `public`
* `reject`
* `reject_multiple_versions`
* `reply`

However, the comment field is also displayed for:
* `super`
* `comment`

The implementation from #18233 displays the reason select on all forms which include a comment field, but we need to update it so it only displays for the actions in the top list above.

### PR DESCRIPTION
**Pull request by bobsilverberg**
~~Depends on #18244~~
Fixes #18288

### CODE REVIEW

**Comment by bobsilverberg** [comment]
This PR build on top of https://github.com/mozilla/addons-server/pull/18244, so it probably makes sense to hold off reviewing it until that is merged and I rebase it. All I've added here is the code to hide the `reasons` select for actions for which it is not applicable. It's just a few lines of code, but I'm not sure how to test it. I tried to find tests for similar code, but wasn't successful. I tried to see if I could do something with the `content = str(form); doc = pq(content)` pattern, but it seemed that the element to which I added the `data-value` attribute doesn't appear in that content.

Any suggestions for what I can to do test this new code would be appreciated.

**Comment by bobsilverberg** [comment]
This is ready for review, and should ideally land this week as it complements #18233. Please see the comment above about being unsure how to add a test for this.

**Comment by diox** [comment]
You can't use `str(form)` because the template is separate, and completely unrelated to the `Form` instance (sadly: it's something we could/should fix, but it's a lot of work).

We do have a few tests in `src/olympia/reviewers/tests/test_views.py` that test similar things by rendering the full review page, and looking for the right element in there.

**Comment by bobsilverberg** [comment]
> You can't use `str(form)` because the template is separate, and completely unrelated to the `Form` instance (sadly: it's something we could/should fix, but it's a lot of work).
> 
> We do have a few tests in `src/olympia/reviewers/tests/test_views.py` that test similar things by rendering the full review page, and looking for the right element in there.

Thanks @diox. I actually found a place where similar things are already being tested, and it makes sense to just update those tests. I'm not sure why I didn't find them the first time around.

**Review by diox — APPROVED** [review]

**Comment by bobsilverberg** [comment]
Thanks @diox. I think I'm going to cherry-pick this so that the form doesn't appear for actions where it is not valid.

**Pull request merged**
