### PR TITLE
Remove storage related dependencies

### PR DESCRIPTION
**Pull request by diox**
Are we using those though ? @jasonthomas @EnTeQuAk do you know ?

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
We are not using it in any of our code or configuration and we don't seem to use S3 currently so maybe we want to remove it for now until we really need it. But I guess @jasonthomas can say more here.

**Comment by jasonthomas** [comment]
We are not using it right now and we can remove it until we need it.

**Comment by diox** [comment]
Added commit to remove those deps. r?

**Comment by EnTeQuAk** [comment]
r+

**Pull request merged**
