### PR TITLE
Fixes broken layout for collections.

### LINKED ISSUE #6342: Broken layout in theme details page
Steps to reproduce:
1. Load any theme details page i.e. https://addons.allizom.org/en-US/firefox/addon/horse-on-the-beach-jen/

Expected results:
There are no display or layout issues.

Actual results:
There is a layout issue in the upper side of theme details page.

Notes/Issues:
- issue is seen better for themes with no summary.
Verified in FF55(Win 7). Issue is reproducing on AMO-dev and stage.
Screenshot for this issue:
theme

### LINKED ISSUE #6356: Broken layout for Collections
https://addons.mozilla.org/en-US/firefox/collections/DavidHedlund/

screenshot from 2017-09-07 19 28 28

As you can see there's to much space between the rows.

### PR DESCRIPTION
**Pull request by apoorvaeternity**
Fixes #6356 
Before-
image 2
After-
image 3

### CODE REVIEW

**Comment by diox** [comment]
Hi, 

We're planning to fix this in a different way, since lots more pages are affected.

**Comment by apoorvaeternity** [comment]
Okay. Tell me how you want to fix these issues. I will be happy to fix it.

**Comment by diox** [comment]
I already pushed a fix for these myself in https://github.com/mozilla/addons-server/commit/2bb1a67d0956794674ed0700fe761c41f0d544ed

**Comment by apoorvaeternity** [comment]
Oh cool then :).

**Pull request closed without merging**
