### PR TITLE
Add Access-Control-Allow-Origin: * to v3 API (fix #1741)

### LINKED ISSUE #1741: CORS the API
We aren't sure where the admin API is going to be living. We do know that the disco pane is going to be on services.addons.mozilla.org, let's ensure the API is CORS'd so that's not going to be a problem.

In the marketplace we started off setting this explicitly on each API. I think CORS by default might be the way to go.

### PR DESCRIPTION
**Pull request by diox**
cc @mstriemer @kumar303 : since you guys played with API endpoints for signing and such, does this approach seem ok to you ?

### CODE REVIEW

**Comment by mstriemer** [comment]
The signing views require a JWT in the `Authentication` header so I think that's fine.

We have the `accounts` URLs there too. The profile and super create user views require a JWT, and the register, login and authenticate views require the `state` parameter to match your cookie which should prevent any CSRF for both of those. The account source view is anonymous and read-only, can't think of a benefit someone might find hitting that from the browser.

Stats views take JWTs as well.

Seems good to me.

**Comment by muffinresearch** [comment]
Should there be a test to ensure Access-Control-Allow-Origin * isn't sent in conjunction with Access-Control-Allow-Credentials - because that would potentially open us up to CSRF attacks?

**Comment by diox** [comment]
Yeah, good idea. It's disabled by default, but having the test should keep us on our toes :)

**Comment by diox** [comment]
(Which reminds me, I need to investigate whether our API currently support cookied-based auth, and if it does, prevent it)

**Comment by kumar303** [comment]
I feel like we will need cookies. We could add `Access-Control-Allow-Credentials` later I guess since we don't have any immediate instances of browser authentication to the v2 API.

**Comment by kumar303** [comment]
The patch looks good to me.

**Pull request merged**
