### PR TITLE
makes agreement button more readable and fixes link to docker commands in the installation instructions

### LINKED ISSUE #6549: Link to Docker commands in docs is broken
The link to "Docker commands" in https://addons-server.readthedocs.io/en/latest/topics/install/docker.html#hacking-on-the-docker-image is broken.

What did you expect to happen?
I think it should be changed to https://docs.docker.com/engine/reference/commandline/docker/

### PR DESCRIPTION
**Pull request by ilmanzo**
Fixes #6549
Fixex #6400

### CODE REVIEW

**Comment by muffinresearch** [comment]
@ilmanzo Thanks for the patch.  To help us understand what's what in a list of PRS please use a meaningful PR title e.g.  `Update link to docker commands` as  opposed to the issue number - it makes it easier for us to see what each PR represents at a glance.

As you've already done putting the `Fixes #ISSUE` in the description provides the link to the issue, which is perfect 👍

**Comment by ilmanzo** [comment]
Hi, sorry for the wrong title; I updated it now, hope it's more clear

**Comment by eviljeff** [comment]
Can you make these two fixes as two separate pull requests - they seem unrelated.  Also, don't include the .gitkeep files.

**Comment by ilmanzo** [comment]
ok I'll close this PR and make two distinct other, one for each issue.

**Pull request closed without merging**
