### PR TITLE
fix migration by changing version_id to be unsigned

### PR DESCRIPTION
**Pull request by eviljeff**

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
r+ once travis agrees

**Comment by muffinresearch** [comment]
I just ran into an issue with this where I needed to essentially revert this change locally to get this migration to run because the foreign key creation failed otherwise.

**Comment by eviljeff** [comment]
Is your Version.id locally a signed int?

**Comment by diox** [comment]
It will be for anyone that built their local db from scratch (using django syncdb/migrate) ...

**Pull request merged**
