### PR TITLE
limit characters in make contribution comment, fixes #3648

### LINKED ISSUE #3648: Maximum-length comment from "Make a Contribution" window is not parsed correctly
STR:
1. Load details page for an add-on with contributions available i.e. https://addons.mozilla.org/en-US/firefox/addon/firebug/?src=hp-dl-mostpopular
2. Click on "Contribute" button and leave a comment over 255 chars (on multiple rows)
3. Click "Make contribution" button

ER:
User is not let to type more than 255 chars.

AR:
"Invalid data" message is displayed.

Notes/Issues:
Verified on FF49(Win 7). Issue is reproducing on all AMO servers.
Screenshot for this issue:
contrib

### PR DESCRIPTION
**Pull request by Prashant-Surya**
Added limit of 255 characters in the comment text area in make contribution light-box.

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
Thanks for the patch!

There are two things we might consider in this patch:

 * Add a proper test that checks that the maxlength is really exposed in the textbox. You can have a look at `TestContributeEmbedded` in `olympia/addons/tests/test_views.py` and add a test there.
 * `contribute` in `olympia/addons/vews.py` (around line 456) also contains `commentlimit = 255` - we should move that into a constant, maybe into `olympia/constants/payments.py` as `PAYPAL_MAX_COMMENT_LENGTH` or so since this is a limit enforced by paypal, not really by us.

Let me know if you have any questions!

**Comment by Prashant-Surya** [comment]
I'll make those changes and update it.

**Comment by Prashant-Surya** [comment]
@EnTeQuAk I added the constant, but I'm confused about writing test case to check text in the text box.

**Comment by EnTeQuAk** [comment]
@Prashant-Surya great, feel free to push your (partial) changes to this pull request so I can already review and comment on them.

Regarding the test, what's blocking / confusing you here? Have a look at `TestContributeEmbedded` in `olympia/addons/tests/test_views.py` and maybe use existing tests as an inspiration for writing a new test. Let me know if you have any questions!

**Comment by Prashant-Surya** [comment]
I mean I've to check whether the text length is limited to 255 or not at the front end side right? I couldn't write a test case for that. For testing comment length for the during form submission there is already a test case for it.

**Comment by EnTeQuAk** [comment]
ah, I see. Thanks for the update, I think that'll do it. I'm going to merge this.

Thanks a lot for your contribution!

**Pull request merged**
