### PR TITLE
Only consider betas for the downgrade to legacy error if uploading beta

### LINKED ISSUE #6236: uBlock origin can't upload their extension
Mostly in https://github.com/gorhill/uBlock/releases/tag/1.13.10, I'm filing on their behalf.

My guess is that uBlock already has a WebExtension in the Beta channel and the check to see if a WebExtension version already exists does not take that into account. That's a guess though, someone should check that's the case.

Would like to give this a bit of priority if we can please.

### PR DESCRIPTION
**Pull request by diox**
Previously, we would always consider beta versions (at least when dealing with a file upload, which is the main use case), so we would raise the downgrade error when uploading a new legacy if the latest
beta was a webextension.

Fix #6236

### CODE REVIEW

**Comment by eviljeff** [comment]
There's a fair amount of (sensible) rewriting in this patch, but I missed the part that actually does the fix.

**Comment by diox** [comment]
See the commit message / PR description: the main thing that fixes it ias that we now detect betas when dealing with `FileUpload`s. Previously we didn't, always included them, which caused the issue.

**Comment by eviljeff** [comment]
> See the commit message / PR description: the main thing that fixes it ias that we now detect betas when dealing with FileUploads. Previously we didn't, always included them, which caused the issue

yep, I read them, but I was asking which part of the _patch_ does the change.  Most of the change seems to be changing `files` to `qs`.

**Comment by diox** [comment]
Previously:
```
        files = files.filter(Q(status=amo.STATUS_PUBLIC) |
                             Q(status=amo.STATUS_BETA, is_signed=True))
```

Now (when not uploading a beta, `is_version_beta` is `False`):

```
statuses = [amo.STATUS_PUBLIC]
if is_version_beta:
    # Only include beta versions if the version string passed corresponds
    # to a beta version. This is not perfect because even if the version
    # string *looks* like a beta, the developer might want to use it as a
    # regular listed upload, and in that case including previous betas in
    # the list is wrong, but it's the best we can do when we're dealing
    # with a FileUpload, since it's too early to know what the developer
    # intends to do.
    statuses.append(amo.STATUS_BETA)
# Find all previous files of this add-on with the correct status and in
# the right channel.
qs = File.objects.filter(
    version__addon=addon, version__channel=channel, status__in=statuses)
```

So now, we don't include files with `STATUS_BETA`. Previously we would.

**Pull request merged**
