### PR TITLE
Fix Complete Themes link display issues in RTL

### PR DESCRIPTION
**Pull request by atiqueahmedziad**
Fixes issue #2393
## Before
sad

## After
happy

### CODE REVIEW

**Comment by atiqueahmedziad** [comment]
@tofumatt r?

**Comment by tofumatt** [comment]
Looks good, but could we fix the menu arrow while we're at it? fix

**Comment by atiqueahmedziad** [comment]
sure :) 
I will the pr very soon.

**Comment by ValentinaPC** [comment]
@atiqueahmedziad : there is a separate issue about @tofumatt tofumatt comment.
( #2397  )

**Pull request closed without merging**
