### PR TITLE
Move addons-server to use beacon for Google Analytics requests

### LINKED ISSUE #14427: Move addons-server to use beacon for Google Analytics requests
We should move to using beacon for GA requests to ensure better reliability and tighten our CSP.

To do this we need to check if we need to update from the legacy GA implementation first (we probably do since I can only find docs about configuring the transport mechanism in the newer implementation).

Doing this requires the following changes:

- Update the GA implementation on addons-server (if required)
- Configure GA to use beacon as a transport.
- Remove the GA host entry from `img-src` in the CSP
- Add an entry for a GA host to `connect-src` in the CSP.
- Test analytics are still working.

This was done for addons-frontend a few months ago in https://github.com/mozilla/addons-frontend/commit/e82335d1a6c7e5338d275531124c9fd639de7f82

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #14427 

I was able to test a page view in devhub and see that analytics are still working, and using the `beacon` transport, but I'm not sure where the changes in  `static/js/lib/jquery.pjax.js`, in `static/js/shield_study/main.js` or in `static/js/zamboni/buttons.js` are manifested. Can anyone provide some guidance on those?

### CODE REVIEW

**Comment by eviljeff** [comment]
> I'm not sure where the changes in static/js/lib/jquery.pjax.js,

I don't think we use that file, so it can be deleted  Though we do use the file with the same name (and similar content? But maybe doesn't touch GA?) in static/js/node-lib/jquery.pjax.js.

> in static/js/shield_study/main.js 

not used any more - the shield studies got removed in #10003 

> in static/js/zamboni/buttons.js

this file is included throughout the site, but it's not clear the buttons (that reference GA) are used anymore - they seem to be concerned with install buttons which is now a frontend thing.

**Comment by bobsilverberg** [comment]
> > I'm not sure where the changes in static/js/lib/jquery.pjax.js,
> 
> I don't think we use that file, so it can be deleted Though we do use the file with the same name (and similar content? But maybe doesn't touch GA?) in static/js/node-lib/jquery.pjax.js.
> 
> > in static/js/shield_study/main.js
> 
> not used any more - the shield studies got removed in #10003
> 

I think that's the wrong link. Do you have the correct one handy so I can double check that this file can be removed?

> > in static/js/zamboni/buttons.js
> 
> this file is included throughout the site, but it's not clear the buttons (that reference GA) are used anymore - they seem to be concerned with install buttons which is now a frontend thing.

**Comment by bobsilverberg** [comment]
> cleaning up the obsolete js files could be a followup

Thanks. I think it makes sense to do at least the simple cleanup for now, so I'll look at removing `static/js/lib/jquery.pjax.js` and `static/js/shield_study/main.js`.

**Comment by eviljeff** [comment]
> 
> 
> > > I'm not sure where the changes in static/js/lib/jquery.pjax.js,
> > 
> > 
> > I don't think we use that file, so it can be deleted Though we do use the file with the same name (and similar content? But maybe doesn't touch GA?) in static/js/node-lib/jquery.pjax.js.
> > > in static/js/shield_study/main.js
> > 
> > 
> > not used any more - the shield studies got removed in #10003
> 
> I think that's the wrong link. Do you have the correct one handy so I can double check that this file can be removed?

#10448 though you can see for yourself by searching for "shield" in the code - the only references are the redirects we left in place.

**Pull request merged**
