### PR TITLE
Update links on autogenerated submission email.

### LINKED ISSUE #13543: Update links on autogenerated submission email
A few links on the autogenerated add-on submission email (found in the file`https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/templates/devhub/email/submission.txt`) should be updated to point to Extension Workshop. 

* `https://developer.mozilla.org/Add-ons/AMO/Policy/Reviews` should be changed to `https://extensionworkshop.com/documentation/publish/add-on-policies/`

*  `https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Distribution/Resources_for_publishers` should be changed to `https://extensionworkshop.com/documentation/manage/resources-for-publishers/`

### PR DESCRIPTION
**Pull request by victorphoenix3**
Fixes #13543

### CODE REVIEW

**Comment by caitmuenster** [comment]
Thanks, @victorphoenix3! This looks good to me. 

@eviljeff or @diox, could you officially review and merge? ;)

**Comment by caitmuenster** [comment]
@victorphoenix3 We've added your patch to our [contribution wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition#February_2020). Thanks for helping update the email text! 🙌🏼

Would you like to create an account on mozillians.org? I'd be happy to vouch for you!

**Comment by victorphoenix3** [comment]
Thanks a lot @caitmuenster . Looking forward to contributing more to the codebase. 
Just created [my account](https://mozillians.org/en-GB/u/Jayati/) on mozillians.org :)

**Comment by caitmuenster** [comment]
Woohoo, you're vouched! ✨ Welcome onboard and we'll see you around!

**Pull request merged**
