### PR TITLE
Remove nuggets dependency, we are not using it anymore.

### PR DESCRIPTION
**Pull request by diox**

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
We are using `redisutils`

```
[git:feature/upgrade-lxml (olympia)] ~/Projects/olympia> acka redisuti
src/olympia/amo/monitors.py
166:        import redisutils
171:        for alias, redis in redisutils.connections.iteritems():

src/olympia/amo/tests/test_monitor.py
1:import redisutils
64:    @patch.object(redisutils.MockRedis, 'info', create=True)

src/olympia/amo/tests/__init__.py
32:from redisutils import mock_redis, reset_redis
```

**Comment by EnTeQuAk** [comment]
r-

**Comment by diox** [comment]
ahah hate the weird import paths. I'll find a way to replace this.

**Comment by diox** [comment]
Also used: `json_field`. grr

**Comment by diox** [comment]
re-r ?

**Comment by EnTeQuAk** [comment]
r+

**Pull request merged**
