### PR TITLE
Add file signed status to scanner query result page

### LINKED ISSUE #16554: Expose file signed status on scanner query result page
For quicker triage, it would be helpful if the scanner query result page showed whether the file that matched was signed or not.

### PR DESCRIPTION
**Pull request by wagnerand**
Fix #16554.

### CODE REVIEW

**Review by bobsilverberg — APPROVED** [review]
Looks good to me. I would think we'd want to add a test for this, especially as it is a custom field.

r+wc

**Comment by wagnerand** [comment]
> Looks good to me. I would think we'd want to add a test for this, especially as it is a custom field.
> 
> r+wc

@diox I couldn't find tests for the scanner query result page. Do we have any?

**Comment by diox** [comment]
`TestScannerQueryResultAdmin` ?

**Comment by wagnerand** [comment]
Oh weird, I somehow missed that when searching. Thanks!

**Pull request merged**
