### PR TITLE
Update Remote Settings URLs after GCP migration

### PR DESCRIPTION
**Pull request by leplatrem**
Follow-up of #20593

### CODE REVIEW

**Comment by leplatrem** [comment]
@bqbn up?

**Comment by leplatrem** [comment]
@diox up?

**Review by diox — APPROVED** [review]

**Comment by diox** [comment]
@leplatrem is this needed in prod right away ? This missed this week's push window, so unless we do an out of schedule push it would be deployed in 2 weeks.

**Comment by leplatrem** [comment]
No that's ok, we'll maintain the domains for a while.

**Pull request merged**
