### PR TITLE
Configure max_result_window during reindex.

### LINKED ISSUE #6703: Investigate setting important index metadata during reindex
Refs https://github.com/mozilla/addons-server/issues/6053#issuecomment-336293808

`max_result_window` got lost during reindex, we should either add a new management command that is setting these or the reindex command should take care of that.

### PR DESCRIPTION
**Pull request by EnTeQuAk**
Fixes #6703

### CODE REVIEW

**Comment by diox** [comment]
@EnTeQuAk do you have time to also:
- Document that in the search API docs
- Avoid returning the url of the `next` page in the ES paginator if that page goes over the limit (return `None` instead)

If you don't have time to do this right now let's merge this as-is, I've asked willdurand to file an issue about this.

**Comment by EnTeQuAk** [comment]
Sure, I'll do that


On Mon, Nov 13, 2017, at 02:52 PM, Mathieu Pillard wrote:
> @EnTeQuAk[1] do you have time to also:


>  * Document that in the search API docs
>  * Avoid returning the url of the next page in the ES paginator if
>    that page goes over the limit (return None instead)> If you don't have time to do this right now let's merge this as-is,
> I've asked willdurand to file an issue about this.> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].> 

Links:

  1. https://github.com/entequak
  2. https://github.com/mozilla/addons-server/pull/6893#issuecomment-343924754

**Comment by diox** [comment]
The other issue is filed as https://github.com/mozilla/addons-server/issues/6902

**Comment by EnTeQuAk** [comment]
@diox this should be ready now

**Pull request merged**
