### PR TITLE
Remove the (seemingly) unused packages: psutil, sqlparse

### PR DESCRIPTION
**Pull request by eviljeff**
Nothing obviously fails... but I don't know what they were used for anyway :grimacing:

### CODE REVIEW

**Comment by diox** [comment]
I don't know about psutil but sqlparse is used by django-debug-toolbar...

**Comment by diox** [comment]
psutil is apparently used by celery debug utils.

**Comment by eviljeff** [comment]
Ah, I don't use django debug toolbar, but I guess others do.

**Comment by eviljeff** [comment]
we could do with documenting in comments why/where some of these dependencies are used if there isn't an obvious `import` really.

**Comment by eviljeff** [comment]
Seems like there isn't anything to do here then, if they're both actually used.

**Comment by diox** [comment]
Some time ago I wrote a script to do that for zamboni : https://github.com/mozilla/zamboni/blob/master/scripts/find_revdeps.py

**Pull request closed without merging**
