### PR TITLE
Expose page_size in paginated API response

### LINKED ISSUE #4837: Expose page_size in paginated API response
If the `page_size` is exposed in the response it will be possible to derive all of the pagination configuration from the response since the page count needs both the count and number of results per page.

Doing it this way means there's no need to keep the request page size in sync with anything else as changing the request will change the `page_size` in the response and then the pagination in addons-frontend (once updated to use it) will adapt on the fly.

### PR DESCRIPTION
**Pull request by diox**
Fix #4837

### CODE REVIEW

**Comment by kumar303** [comment]
I saw this on IRC:

> actually, just realised the API supports a `page_size` param anyway.  frontend can just send whatever page size it wants

If that's true, can you document it here? http://addons-server.readthedocs.io/en/latest/topics/api/overview.html#pagination

**Comment by kumar303** [comment]
Also, I'm not sure what this means in the docs: "Unless specified, endpoints returning a list of results will be paginated." Unless what is specified? Can you provide an example?

**Comment by diox** [comment]
`page_size` is already documented on some APIs that support it, e.g. add-on search: http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#search. I'll add it to the overview page and check the other endpoints.

That "unless specified" bit refers to the fact that endpoints are paginated by default, but some specific endpoints could be "unpaginated", in which case it's specified as such in the corresponding documentation. At the moment I don't think we have such endpoints though.

**Comment by diox** [comment]
Closing this to document `page_size` better instead.

**Comment by diox** [comment]
Actually we can do both!

**Pull request merged**
