### PR TITLE
Remove amo.tests.test_locales

### PR DESCRIPTION
**Pull request by EnTeQuAk**
One less file that imports `tower` and django does this correctly these days imho.

### CODE REVIEW

**Comment by magopian** [comment]
I think the point of the docstring was to say that the test should be changed to some other non-existent locale when we have a `mn` locale :)

Maybe use a locale code that doesn't exist?

**Comment by EnTeQuAk** [comment]
Correct if I'm wrong but it also mentions `z-messages.po` which doesn't exist anywhere? And django officially loads everything in `LOCALE_PATHS` first and doesn't appear to return `en-US` as a fallback anywhere.

**Comment by magopian** [comment]
Not sure, but those "particularities" might be related to our specific implementation (using `tower` and such)?

**Comment by EnTeQuAk** [comment]
With the django 1.7 branch tower will be gone and the particular code that is referenced on introduction of the test - https://github.com/clouserw/tower/commit/c2690bb8 - is gone. Since marketplace and others are not using tower anymore it appears django is doing this correct. I mean, I'm pretty sure it does, there are a few patches to django that might relate to this but fix this in different ways.

**Comment by magopian** [comment]
if you're sure, then ok ;)

r+

**Pull request closed without merging**
