### PR TITLE
Fix review count

### LINKED ISSUE #7540: Reviews count from DevHub is not consistent with reviews count in new frontend
Follow up of [#7111](https://github.com/mozilla/addons-server/issues/7111)
Prerequisites: you need to have at least one add-on submitted; add-on contains empty user reviews

STR:

1. Log in to Developer Hub and go to Manage my submissions
2. Look at an add-on that has been rated and also includes some empty user reviews - make a note of the number of reviews displayed in dev-hub
3. Click on the "<#  reviews>" link to read all the available reviews on the frontend

Actual result:
The number of reviews displayed in DevHub is not the same as the actual number of reviews (empty+written) listed on the frontend

Expected result:
Number of reviews displayed in DevHub matches the actual number of reviews (empty+written) listed on the new frontend

Notes:
Reproduced on all AMO servers

[dev-hub]
image

[frontend]
image

### PR DESCRIPTION
**Pull request by yatinmaan**
Fixes #7540

### CODE REVIEW

**Comment by yatinmaan** [comment]
Should I also add a testcase where `total_ratings` != `text_ratings_count` ?

**Comment by caitmuenster** [comment]
Thanks so much for the patch, @yatinmaan! Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition). ✨

Would you be interested in creating an account on mozillians.org? I'd be happy to vouch for you!

**Comment by yatinmaan** [comment]
> Would you be interested in creating an account on mozillians.org? I'd be happy to vouch for you!

@caitmuenster Sure, https://mozillians.org/en-US/u/yatinmaan/

**Comment by caitmuenster** [comment]
Awesome! You're vouched. 😎

Welcome onboard! I look forward to seeing you around.

**Pull request merged**
