### PR TITLE
Avoid 500s when changing the group of a promoted add-on

### PR DESCRIPTION
**Pull request by willdurand**
Fixes https://github.com/mozilla/addons-server/issues/15795

---

Not sure if this is the right way :tm: but it works and given that we don't
allow subscription data updates on this admin page, it should be fine.

This issue linked above should be fixed before this week's push.

### CODE REVIEW

**Comment by eviljeff** [comment]
what's the actual error this is trying to "fix"?  I'm concerned we're hacking around a genuine bug rather than addressing it.

**Comment by willdurand** [comment]
> what's the actual error this is trying to "fix"? I'm concerned we're hacking around a genuine bug rather than addressing it.

The error says:

```
django.core.exceptions.ValidationError: ['ManagementForm data is missing or has been tampered with']
```

It's captured by the test case added in this patch.

**Comment by eviljeff** [comment]
For reference (because this doesn't seem to be spelled out in the issue either), the failure is because the inline form is only shown for sponsored addons but if the request changes the addon _to_ sponsored the inline form isn't shown when page was submitted but its now needed to be a complete submission.

Like you said, it only works when there's nothing to change on the inline form.  Once the subscription can be changed at all on the form it'll fail again.  It's the right way... but it's not a bad workaround in the interim.

**Review by eviljeff — APPROVED** [review]
acceptable fix 😬

**Pull request merged**
