### PR TITLE
Fixes #8455 : Removed FAQ from footer

### LINKED ISSUE #8455: Remove link to FAQ from Developer Hub landing page
The [Developer Hub](https://addons.mozilla.org/developers/) landing page has links to various useful resources for developers. There's a link in the Support column pointing to an [FAQ](https://addons.mozilla.org/faq) that is in the old front-end and won't be migrated to the new one. It should be removed.

### PR DESCRIPTION
**Pull request by gabru-md**
Fixes #8455 

* [X] This PR relates to an existing open issue and there are no existing
      PRs open for the same issue.
* [X] Add `Fixes #ISSUENUM` at the top of your PR.
* [X] Add a description of the the changes introduced in this PR.

This Pull Request removes the FAQ link from the Developer Hub Landing Page.

Cheers!

### CODE REVIEW

**Comment by gabru-md** [comment]
Thank you!
I would like to take up more issues and learn to solve them for this community :sparkles:

**Comment by caitmuenster** [comment]
Thank you so much for your patch, @gabru-md! Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition). 

Would you be interested in creating an account on [mozillians.org](https://mozillians.org)? I'd be happy to vouch for you!

**Comment by gabru-md** [comment]
Yes! I surely would love to create an account there. 
Thanks a lot!

**Comment by caitmuenster** [comment]
Yay! You are vouched. :) Welcome onboard! I look forward to seeing you around the project!

**Pull request merged**
