### PR TITLE
handle deleted and ex-editors when sending editor subscriptions

### LINKED ISSUE #5544: Developer notification returns 500 in case user email is null.
Sentry: https://sentry.prod.mozaws.net/operations/olympia-prod/issues/379893/

So apparently the `UserProfile.email` is None and that's why the notification fails. I don't know yet why it's None, "It's a very old account from ~2012 I've started reusing recently if that helps." (quote).

### PR DESCRIPTION
**Pull request by eviljeff**
Fixes #5544

### CODE REVIEW

**Comment by wagnerand** [comment]
Don't we need to check whether `user.email` is set?

**Comment by diox** [comment]
> Don't we need to check whether user.email is set as well?

Yeah, I think checking for `deleted` and reviewer permissions is good enough, but I think being paranoid about it and checking `email` as well would be a good thing.

**Comment by wagnerand** [comment]
Also, maybe we want to manually run the following migration to clean out the superfluous entries from the db:

```
DELETE
FROM editor_subscriptions
WHERE user_id NOT IN
    (SELECT u.id
     FROM users u
     JOIN groups_users gu ON gu.user_id = u.id
     JOIN groups g ON g.id = gu.group_id
     WHERE g.id IN (50000,
                    500002))
  OR
    (SELECT id
     FROM users
     WHERE email IS NULL);
```

**Comment by eviljeff** [comment]
I'm not going to add that SQL as a migration as it won't be necessary when the code lands.
If you still want to do it then you should open an issue (or co-opt #5544)

**Comment by eviljeff** [comment]
https://github.com/mozilla/addons-server/pull/5624/commits/46c2f7c2946f544fc45b394e17a20afac466dac0 adds user.email checking.

**Pull request merged**
