### PR TITLE
Don't cache .tox folder, we recreate the environment every time.

### PR DESCRIPTION
**Pull request by EnTeQuAk**
This is a bit experimental, let's see if this will speed things up.

### CODE REVIEW

**Comment by diox** [comment]
I'm worried about this though : https://github.com/travis-ci/travis-ci/issues/4472 

travis caches directories even on build failures, so I fear we could end up with a non-working tox env. Am I being paranoid ?

**Comment by EnTeQuAk** [comment]
Could be a problem but we do call `update_deps` before running our tests anyway so this will very probably fix things up.

Only thing where this could get dangerous is some wheel package that is linked against something weird, get's installed and not re-installed but I guess that won't happen that often and if, we can purge the cache.

**Comment by EnTeQuAk** [comment]
At least if we're going to use `--recreate` then we don't have to cache `.tox`

**Comment by EnTeQuAk** [comment]
Seeing https://travis-ci.org/mozilla/addons-server/builds/129709654 which leads me to reversing this and removing `.tox` from the cache completely (useless if we recreate it anyway).

We could potentially fix this but the cache appears to cache symlinks and others which will most definetely lead to superweird errors.

**Comment by diox** [comment]
r+

**Pull request merged**
