### PR TITLE
Rewrite /app/version.json with correct CIRCLE_BUILD_URL

### PR DESCRIPTION
**Pull request by bqbn**
This tries to address the issue described in https://github.com/mozilla/addons-server/commit/89554ebbe0dcdef6fa105372d3b2d8e4401b8628#commitcomment-24791274

### CODE REVIEW

**Comment by bqbn** [comment]
Alternatively, I guess we can combine build and deploy, and build and release separately to form 2 jobs, e.g.: build-deploy and build-release, then in the workflow section we filter by branches accordingly. Benefit of doing that is we don't have to touch the image again once it's built.

**Comment by EnTeQuAk** [comment]
Thanks a lot for the fix, indeed the version.json bit got left out in the refactor unfortunately.

> Alternatively, I guess we can combine build and deploy, and build and release separately to form 2 jobs, e.g.: build-deploy and build-release, then in the workflow section we filter by branches accordingly. Benefit of doing that is we don't have to touch the image again once it's built.

That sounds like a good idea to me and might make things a bit more streamlined. Do you have time to do that? Otherwise I can look into that later today.

**Comment by EnTeQuAk** [comment]
Looked great, thanks for the update! Let's see how it behaves on master.

**Comment by jrbenny35** [comment]
@bqbn thanks!

**Pull request merged**
