### PR TITLE
Removed double redirect Search Bar link on the AMO servers

### PR DESCRIPTION
**Pull request by bkzhang**
Refers to issue #4757 

The "search bar" linked on https://addons.allizom.org/en-US/firefox/search-tools/ redirects to another redirect. Removed the middle man and redirect directly to the correct "search bar" link.

One thing I am pretty confused about, the jétpack.xpi file always says that its modified so I'm abit unsure of what to do with it. Tried to checkout the file to an early version and many other things but it's always considered modified Does it have anything to do with the encoding? 😢 

image

### CODE REVIEW

**Comment by bkzhang** [comment]
How to reproduce the encoding problem (macOS): 
1. `git clone https://github.com/mozilla/addons-server.git`
2. `cd addons-server`
3. `git status`

From the `git status` you can see an untracked file.

**Comment by EnTeQuAk** [comment]
Thanks a lot for the pull request! Can we maybe change the link to be `https://support.mozilla.org/kb/use-search-bar-firefox` - without the `en-US` so that we keep the user-language intact?

Also, you don't have to update all `.po` files by hand, we're regularly extracting the strings automatically from our python html code and to the appropriate `.po` files.

**Comment by EnTeQuAk** [comment]
I restarted the travis build, it seemed to be some kind of travis issue. Let's see, should be green though.

**Comment by bkzhang** [comment]
Oh man, I'm derping so hard sorry guys. Changed the `.html` and django template file's *search bar* link to keep user-language. I am never `git add .`'ing again.

**Comment by EnTeQuAk** [comment]
Can you maybe remove the changed .po files as well? That'd make it easier to merge and extract later, especially since the information there is wrong once merged for a short period of time.

**Comment by bkzhang** [comment]
@EnTeQuAk ...this was unpleasantly chaotic. Should be good now.

**Comment by EnTeQuAk** [comment]
Thanks a lot! Just merged the patch.

**Comment by kumar303** [comment]
I had to revert this because the duplicated binary file was blocking me from updating my git repository. Sorry for the inconvenience. Some details: https://github.com/mozilla/addons-server/issues/4757#issuecomment-293063372

**Pull request merged**
