### PR TITLE
Makes review date column sortable

### LINKED ISSUE #2474: Add sorting by Last Review to All Unlisted view

### PR DESCRIPTION
**Pull request by eviljeff**
Fixes #2474

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
This works great though a test verifying that `sortable` is indeed `True` or checking the respective HTML somehow would be nice. But since this is dragon land I can totally live without it tbh.

**Comment by eviljeff** [comment]
I looked into adding one but we don't test if columns are sortable anywhere else.

**Comment by eviljeff** [comment]
extra trivia: [django-tables](https://github.com/miracle2k/django-tables) was last developed 6 years ago and has long been deprecated in favour of [django-tables2](https://github.com/bradleyayers/django-tables2) (not a clean drop-in replacement alas - there are syntax changes)

**Comment by EnTeQuAk** [comment]
maybe open an extra bug? Not sure if an update is worth it though but it might not be the worst idea either.

**Pull request merged**
