### PR TITLE
fixed log in to login, issue #5051

### LINKED ISSUE #5051: Change "log in attempt" to "login attempt"
Currently, there's an occurrence of "log in" (verb) where "login" (noun) is intended [1],[2], which could be a typo. There might be more, I just spotted it during l10n.

"Your log in attempt could not be parsed. Please try again."

[1] https://pontoon.mozilla.org/en-GB/amo/LC_MESSAGES/django.po/?search=log+in+&string=148869
[2] https://github.com/mozilla/addons-server/blob/master/src/olympia/accounts/views.py#L52

### PR DESCRIPTION
**Pull request by bkzhang**
Fixes #5051

Very minor grammar fix.

### CODE REVIEW

**Comment by muffinresearch** [comment]
Thanks @bkzhang

**Comment by caitmuenster** [comment]
Thanks so much, @bkzhang, and welcome onboard! Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition#March_2017). 

I'd also love to help you set up a profile on [mozillians.org](https://mozillians.org/en-US/)! If you could ping me when you've set it up, I'd be happy to vouch for your contribution.

**Comment by bkzhang** [comment]
Hi @caitmuenster, here's my new profile https://mozillians.org/en-US/u/bkzhang/ thanks for this! Your help is greatly appreciated 😄 and I will be sure to help out a lot more in the future.

**Comment by caitmuenster** [comment]
Awesome! Just completed the vouch. I look forward to seeing you around the web! :)

**Pull request merged**
