### PR TITLE
Normalise xpi_info['guid'] before equality check

### LINKED ISSUE #11174: Add-on ID comparison is case-sensitive when new version, case-insensitive when new add-on
### Describe the problem and steps to reproduce it:
Critical error when uploading new version: "The add-on ID in your manifest.json or install.rdf (NoticeCase@xxx) does not match the ID of your add-on on AMO (noticecase@xxx)"

Critical error when uploading new add-on: "Duplicate add-on ID found."

### What happened?
Signing of the add-on was prevented in both cases.

### What did you expect to happen?
Either allow a new version of existing add-on or allow a new add-on.

### PR DESCRIPTION
**Pull request by dbxnr**
Fixes #11174 - normalises xpi_info['guid'] before equality check, performs iexact match on database query to ignore case.

### CODE REVIEW

**Comment by wagnerand** [comment]
According to @rpl, Firefox treats add-on ids as case-sensitive. Could you update your PR to make all checks case-sensitive?

**Comment by EnTeQuAk** [comment]
> According to @rpl, Firefox treats add-on ids as case-sensitive. Could you update your PR to make all checks case-sensitive?

The checks are currently case-sensitive, so this seems to be needless to be changed.

I'm going to close the PR for now, and the related issue as the current behavior seems to represent what Firefox does and expects.

Correct me if I'm mistaken though

**Comment by EnTeQuAk** [comment]
re-opening, see reasoning in my comment in the linked issue.

If you have the time, we'd appreciate you update your PR to make all the checks indeed case sensitive and add a few tests to test that new behavior.

**Comment by dbxnr** [comment]
I've updated the PR to perform case-sensitive SQL queries ([__regex](https://docs.djangoproject.com/en/2.2/ref/models/querysets/#regex)).  The CI failures unfortunately seem unrelated to my changes, unless I'm missing something

**Comment by EnTeQuAk** [comment]
I'm closing the PR, last time we discussed this we ended up deciding that the current behavior is perfectly fine for now.

**Pull request closed without merging**
