### PR TITLE
provide a reason option to sign file

### PR DESCRIPTION
**Pull request by andymckay**
* fixes mozilla/addons#100
* provides a --reason argument to the sign_addons command to send a particular email

r? @EnTeQuAk for the python @jvillalobos for the message

### CODE REVIEW

**Comment by jvillalobos** [comment]
Here's my take: https://public.etherpad-mozilla.org/p/re-re-re-sign
Ping @atsay for grammar and stuff.

**Comment by jvillalobos** [comment]
I reworded some things because this includes unlisted add-on devs (right?) and some of the wording only makes sense on AMO.

**Comment by atsay** [comment]
Made edits.

**Comment by EnTeQuAk** [comment]
r+ for the python parts.

**Comment by brampitoyo** [comment]
Just making sure that we’ve addressed @wagnerand’s comment on mozilla/addons#100 about not using the term “signed” on the email.

Instead, he suggested using something like “re-sign”.

**Pull request merged**
