### PR TITLE
delete the right profile picture

### LINKED ISSUE #2225: Wrong user profile photo deletion
Steps to reproduce:
1. Log in to AMO-stage with an admin account https://addons.allizom.org/en-US/firefox/
2. Access any user details page (i.e. https://addons.allizom.org/en-US/firefox/user/LouCypher/)
3. Click "Manage User" button
4. Delete its photo

Expected results:
User's photo is deleted.

Actual results:
Admin's photo is deleted.

Notes/Issue:
Verified on FF45(Win 7). Issue is reproducing in AMO-stage and AMO-dev.
Screencast for this issue: http://screencast.com/t/N4Gxf9iQxsQ

### PR DESCRIPTION
**Pull request by andymckay**
* I really regret getting into fixing up something that's going to be around for so little time but it I thought it would be simple and in the end it appears to be completely untested, eek.
* There's the fixing of permissions and accessing the correct users
* A bit of code clean up
* Some actual y'know tests.
* Fixing up the redirect at the end so it goes to the right place and not, into say the Django admin (yes really)
* This is all still terrible and I know @ValentinaPC will find more issues, for example: it says "Delete my user picture" when you delete someone else's - but I know I can won't fix those as unimportant :smile: 
* fixes #2225

### CODE REVIEW

**Comment by diox** [comment]
I was super happy when I read the title of this PR initially, thinking you had removed the profile avatars from the site entirely, deleting a pile of code. Then I re-read it properly. Emotional :roller_coaster: :(

**Comment by EnTeQuAk** [comment]
> This is all still terrible ... for example: it says "Delete my user picture" when you delete someone else's - but I know I can won't fix those as unimportant :smile: 

Hmm, that's probably going to be confusing imho.

**Comment by andymckay** [comment]
I still can't believe I worked on this, because when FxA comes along who knows if this remains. Plus why do we even do admin this way?

**Comment by EnTeQuAk** [comment]
More tests are always worth it :)

**Pull request merged**
