### PR TITLE
Long themes names appear cut at hover

### PR DESCRIPTION
**Pull request by tsl143**
This can be one possible solution

### CODE REVIEW

**Comment by tofumatt** [comment]
Could you add a screen shot for this fix? Thanks 😀

**Comment by tsl143** [comment]
d46a1a60-1463-11e6-9104-c2e6ef39f3ec
d1176a34-1463-11e6-91d8-93ffc4158d33

**Comment by muffinresearch** [comment]
I think it would be more ideal if the hover card accomodated more text as opposed to truncating in this case. We lose quite a bit of data this way. 

@tofumatt you're familiar with this code - do you think making the hovercard more flexible is viable?

**Comment by tofumatt** [comment]
Sadly, all the hovercards are of fixed heigh so we can make sure they don't move the content below it (on `:hover` we apply a negative `margin-bottom`). So it's not the easiest thing.

@tsl143 Can you try to make the content only trail off with an ellipsis if it would overlap the entire box?

Alternatively you could see about putting the "Add" button below the text and cutting the text off after two lines with an ellipsis. That should fit most titles.

**Comment by muffinresearch** [comment]
> Alternatively you could see about putting the "Add" button below the text and cutting the text off after two lines with an ellipsis. That should fit most titles.

Sounds like this suggestion will be best. Iirc I don't think text-overflow will work unless wrapping is prevented e.g. it won't work multi-line.

**Comment by tsl143** [comment]
after
screenshot from 2016-05-10 19 20 00

**Comment by tofumatt** [comment]
Looks good, thanks.

@tsl143 In the future can you please label your screenshots so we know which is "before" and which is "after"? We usually put the "before" screenshot first. Thanks 👍

**Pull request merged**
