### PR TITLE
Show e10s status to developer (fix #3123)

### LINKED ISSUE #3123: Show e10s status in reports to the developer
Let's add a couple of columns to the report to show e10s status to the user in the reports.

Currently it looks like this:

screenshot 2016-07-19 09 17 28

Let's add a couple more columns.

Supports mozilla/addons#163

### PR DESCRIPTION
**Pull request by tofumatt**
### Before
screenshot 2016-07-19 09 17 28

### After
screenshot 2016-08-09 14 28 14

### CODE REVIEW

**Comment by andymckay** [comment]
No tests on this ACR stuff eh?

**Comment by tofumatt** [comment]
There are tests for it accepting the ACR data I think but I can add some
HTML tests too, sure. :-)

- tofumatt

**Comment by diox** [comment]
Isn't it going to take too much horizontal space ? It might make long compatibility report descriptions (like the one you have in your first screenshot) very hard to read...

**Comment by tofumatt** [comment]
I could put it below the comments if you think that would work better.

It looks like this with a long comment, fwiw:

screenshot

**Comment by diox** [comment]
I guess that's good enough.

r+

**Pull request merged**
