### PR TITLE
differentiate search shelves for themes

### LINKED ISSUE #16312: Add `themes` property to homepage shelf data
When the homepage starts consuming the [API for homepage shelves](https://addons-server.readthedocs.io/en/latest/topics/api/shelves.html#homepage-shelves), it will need to know whether the shelf is for themes or extensions. This is required because theme shelves are handled differently (e.g., we show 3 themes, but for extensions we show 4 extensions).

This means that we need a property added to the model to indicate if the shelf is for themes, we need the admin updated to allow this property to be specified, and we need the API updated to expose this property.

We did discuss a possible hack which would use the `criteria` returned from the API and inspect it to guess whether it is returning themes or not, but this feels like a hack and probably not the best way to go to solve this.

@eviljeff @diox What do you think about the hack idea, and do you agree it's not a good solution?

### PR DESCRIPTION
**Pull request by eviljeff**
fixes #16312

### CODE REVIEW

**Comment by eviljeff** [comment]
note: whichever one of this or #16321 is merged first is going to cause a merge conflict in the other.

**Review by bobsilverberg — APPROVED** [review]
Thanks for this @eviljeff. The code looks good, but I'm not 100% on adding another value to `endpoint` for this. Sure, it works, and it's a pretty simple way to solve it, but it feels like it's not accurate. The shelf isn't actually using a different endpoint, it's still using the `search` endpoint, but with different criteria. I was thinking more of a checkbox for "contains themes", but I realize that's more complex as it's a new property.

I'm fine with it the way it is, if you think it's best, but I wanted to at least raise this as something to think about.

r+wc

**Comment by eviljeff** [comment]
> I'm not 100% on adding another value to `endpoint` for this. Sure, it works, and it's a pretty simple way to solve it, but it feels like it's not accurate. The shelf isn't actually using a different endpoint, it's still using the `search` endpoint, but with different criteria. I was thinking more of a checkbox for "contains themes", but I realize that's more complex as it's a new property.
> 
> I'm fine with it the way it is, if you think it's best, but I wanted to at least raise this as something to think about.

Yeah, I saw you called that approach a hack in the issue but `endpoint` is really more of a "shelf type" in the implementation (that have to be handled differently), so it didn't seem too bad to expand the types from 2 to 3. And yes it was easier to change the possible values of an existing property than add a new property to the model, admin, form,and serializer (& test each of those parts) 😄 

We can revisit if this simple fix turns out to be a hassle to handle.

**Comment by xlisachan** [comment]
@eviljeff, @bobsilverberg -`shelves/serializers.py` would need to be updated (line 33 and 51) to include the new `search-themes` endpoint, should I make this revision?
Also, I am unable to save homepage shelves in admin - an error is raised (`No data found - check criteria parameters.`), which is from the NoReverseMatch exception in `shelves/forms.py`. It states `addon-search` and `collection-addon-list` are no longer valid view function or pattern names. I'm not sure how to resolve this.

**Comment by eviljeff** [comment]
😐  I'll fix it.  I shouldn't trust the tests passing meaning everything is okay.

**Comment by eviljeff** [comment]
regression should be fixed by #16347

**Pull request merged**
