### PR TITLE
Fix CSS nitpicks (close #1815)

### LINKED ISSUE #1815: Clean up restyle.less
`static/css/restyle.less` has inconsistent whitespace, newline usage, and style. It's worth one commit to just fix all these style nits.

### PR DESCRIPTION
**Pull request by tofumatt**
This fixes a tonne of CSS nitpicks. I think I need to rebase this, so maybe hold off on review for now :smile:

### CODE REVIEW

**Comment by muffinresearch** [comment]
Nice! Give me a shout when you want me to take a look.

**Comment by tofumatt** [comment]
Okay, I resolved all the merge conflicts with a rebase on top of master, but it means there are enough changes that GitHub doesn't like showing it. Sadface!

Ready for r? though, @muffinresearch

**Comment by muffinresearch** [comment]
```css
&:focus, &:hover{
  color: @link-on-color-bg;
  text-shadow: none;
 }
```

could be:

```css
&:focus, 
&:hover {
  color: @link-on-color-bg;
  text-shadow: none;
 }
```

**Comment by muffinresearch** [comment]
```diff
-#aux-nav > ul > li {
-    > ul:after {
-        right: 10px;
+    > a, &:hover > a {
+      background: none;
+      border: 0;
+      box-shadow: none;
     }

     &:hover:after {
-        top: 32px;
-        right: 1px;
-        height: 10px;
+      background: none;
+      background-color: #fff;

```

Is the `background: none` needed or could that be `background: #fff;` ?

**Comment by muffinresearch** [comment]
lgtm r+wc

**Pull request merged**
