### PR TITLE
Return fake diff when entire file has whitespace changes only

### PR DESCRIPTION
**Pull request by willdurand**
fixes https://github.com/mozilla/addons-server/issues/15966

### CODE REVIEW

**Comment by willdurand** [comment]
@diox here is an alternative solution

**Comment by diox** [comment]
I haven't tried it yet but that looks promising!

**Comment by willdurand** [comment]
I just tried this patch fully by re-uploading an add-on and two version from -dev locally and that does what it is supposed to do.

**Review by bobsilverberg — APPROVED** [review]
Looks good. Thanks for taking care of this, @willdurand!

**Pull request merged**
