### PR TITLE
move our custom db backend to .sql so reset_db can identify it

### PR DESCRIPTION
**Pull request by eviljeff**
https://github.com/django-extensions/django-extensions/blob/2.1.2/django_extensions/management/commands/reset_db.py#L72 uses the end of the `DB.ENGINE` setting to work out which db backend it is.  So ours is going to have to be `....xxx.sql` too.

### CODE REVIEW

**Comment by jrbenny35** [comment]
If you look at the Integration-tests job on circleci and open the step, ```Start container, verify it's running and start tests``` you will see an error. IDK why it is being treated as a skip.

**Comment by diox** [comment]
I'm still getting `CommandError: Unknown database engine sql` when running `reset_db` with this patch, not sure why.

**Comment by eviljeff** [comment]
@jrbenny35 is it normal now?  I see a few skips but I don't know if those are normal skips.

**Comment by jrbenny35** [comment]
@eviljeff yup looks good. The normal build time is around 15 minutes now.

**Pull request merged**
