### PR TITLE
change import settings of include()

### LINKED ISSUE #15616: Import include() function from django.urls
Import include() function from new django.urls instead of old django.conf.urls in all the required urls.py files

This will remove one extra line from all the files(more consistent code) and also use the new way to import the include() function in Django-2.x
https://docs.djangoproject.com/en/3.1/ref/urls/#include

### PR DESCRIPTION
**Pull request by Sparsh-Bansal**
Fixes #15616 

I have imported `include()` function from new `django.urls` instead of old `django.conf.urls` in all the required `urls.py` files.

* [x] This PR relates to an existing open issue and there are no existing
      PRs open for the same issue.
* [x] Add `Fixes #ISSUENUM` at the top of your PR.
* [x] Add a description of the changes introduced in this PR.
* [x] The change has been successfully run locally.

### CODE REVIEW

**Comment by Sparsh-Bansal** [comment]
@eviljeff Please review it.

**Comment by Sparsh-Bansal** [comment]
@eviljeff Kindly have a look at this one.

**Review by bobsilverberg — CHANGES_REQUESTED** [review]
Thanks for the patch, @Sparsh-Bansal. It looks good, but we tend to try to put the items imported in alphabetical order. Can you change these so they say `from django.urls import include, re_path`?

**Comment by Sparsh-Bansal** [comment]
Changes are done.

**Review by bobsilverberg — APPROVED** [review]
Looks good, thanks @Sparsh-Bansal!

**Pull request merged**
