### PR TITLE
Fix bug 1188529 to avoid text being selected on click.

### PR DESCRIPTION
**Pull request by EnTeQuAk**
Bug in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1188529

### CODE REVIEW

**Comment by muffinresearch** [comment]
r- on the basis this is just papering over the issue and possibly when the text selection stuff comes in (as mentioned in the bug) it will show the selection carets just with a transparent selection. 

Here's an isolated test-case [1] which highlights the triggers along with some suggested alternative solutions.

[1] http://jsbin.com/pegisayici/edit?html,css,js,output

**Comment by muffinresearch** [comment]
FWIW here's the docs for user-select https://developer.mozilla.org/en-US/docs/Web/CSS/user-select

**Comment by EnTeQuAk** [comment]
@muffinresearch yeah, thanks for the `display: table` hint, I removed that and tried to center the text as good as possible, this seems to work pretty good.

What do you think?

**Comment by mcapella** [comment]
Wouldn't simply pre-setting the text as not-selectable in the mobile/general.js |previewing()| function work? Perhaps like :
https://pastebin.mozilla.org/8859309

**Comment by EnTeQuAk** [comment]
But then I won't be able to select the text even if I explicitly wanted to?

**Comment by mcapella** [comment]
Is that important?  :-P

**Comment by EnTeQuAk** [comment]
I don't know any other consequences but that doesn't mean there aren't any.

I generally dislike disabling well-known features (which I think we all can agree 'seleting text' kinda is) if I don't have to.

**Comment by mcapella** [comment]
You're only blocking selectability of that 'p' element and the text in it, for that page. fwiw, B2G used the approach generally to avoid similar problems with internally generated pages.

**Comment by EnTeQuAk** [comment]
Sure enough, I just don't see the reasoning behind disabling functionality when there's another solution to the problem. Both aren't really elegant solutions though.

**Comment by muffinresearch** [comment]
This the current version:

my_awesome_theme____add-ons_for_firefox

With this PR it looks like:

my_awesome_theme____add-ons_for_firefox

If you add this patch it should look like the first screenshot:

```diff
diff --git a/static/css/zamboni/mobile.css b/static/css/zamboni/mobile.css
index 9be6d70..5669572 100644
--- a/static/css/zamboni/mobile.css
+++ b/static/css/zamboni/mobile.css
@@ -594,15 +594,16 @@ ul.license li.copyr { background-position: 0 -260px; }
     color: #fff;
     display: none;
     font: 18px Georgia, serif;
+    line-height: 64px;
+    margin: 0 !important;
     pointer-events: none;
+    position: absolute;
     text-align: center;
     text-shadow: 0 1px 0 rgba(0, 0, 0, 0.5);
-    position: absolute;
-    top: 50%;
-    left: 50%;
-    width: 60%;
-    margin: 0 !important;
-    transform: translate(-50%, -50%);
+    top: 0;
+    right: 0;
+    bottom: 0;
+    left: 0;
 }
```

The top/right/bottom/left set to 0 makes the p stretch to the parent and line-height matching the height (64px) vertically centers the text. The !important is needed to nuke the margin coming from `#content p`. Whilst using !important is usually best avoided I think it's a better fit here than increasing the specificity of the selector.

**Comment by EnTeQuAk** [comment]
Interesting, I didn't know about `line-height` matching the height results in perfectly centered text. Yeah, `!important` is needed unfortunately, otherwise we'd need to restructure / change some css which I'd rather not.

**Comment by muffinresearch** [comment]
@EnTeQuAk had a chance to update this? Would be good to get it landed.

**Comment by EnTeQuAk** [comment]
@muffinresearch Thanks again, I updated the PR with you proposed patch, this looks a lot better.

**Comment by EnTeQuAk** [comment]
yeah I did, just updated now.

**Pull request merged**
