### PR TITLE
Display file sizes using binary prefixes

### PR DESCRIPTION
**Pull request by replaceafill**
Fixes [#1962](https://github.com/mozilla/addons-server/issues/1962)

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
Thanks a lot for the pull request! If you're up for it, it'd be nice to have some unittests verifying the new behavior :)

**Comment by EnTeQuAk** [comment]
You can find relevant tests in

 * `src/olympia/browse/tests.py` -> `TestLanguageTools` and you can take a look at the various tests in `TestListing` that do test contents in the response (for ``src/olympia/browse/templates/browse/language_tools.html``)
 * `src/olympia/devhub/tests/test_views.py` -> `TestVersionAddFile` for ` src/olympia/devhub/templates/devhub/includes/version_file.html` 
 * `TestFileViewer` in `src/olympia/files/test_views.py` should be relevant for `src/olympia/files/templates/files/file.html `
 * `TestDetailPage` (I think) for the `versions/version.html` which is used in the addons detail page and in the reviewer tools as far as I can see (via `versions.helpers.version_detail`)
 
Well and the hera template is unused 😆 

I hope I found the relevant tests. Usually it should be just fine to test that the binary code is being used in the `response.content` instead of the regular one, e.g `assert 'KiB' in response.content` and to make sure they fail without the relevant patch.

Let me know if you have any questions :)

**Comment by replaceafill** [comment]
Thanks. I've added unit tests for the changes. Let me know if they're ok.

**Comment by EnTeQuAk** [comment]
Looks awesome, thanks a ton for the pull request and change!

I'll merge this right away.

**Comment by caitmuenster** [comment]
Woohoo! Thanks so much, Douglas. The [contribution page](https://wiki.mozilla.org/Add-ons/Contribute/Recognition#November_2016) has just been updated with your bug fix. :)

**Pull request merged**
