### PR TITLE
WIP re #1880, add a static page.

### PR DESCRIPTION
**Pull request by gregglind**
I obviously don't know where to put this :)

Thus, WIP.

Design from gregglind/shield-template with our values.

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
Copying from IRC conversation:

I was thinking about putting the routing into https://github.com/mozilla/addons-server/blob/master/src/olympia/pages/urls.py (e.g take /faq/ as an example) and templates to https://github.com/mozilla/addons-server/tree/master/src/olympia/pages/templates/pages

similar to the sunbird one I'd say.

**Comment by EnTeQuAk** [comment]
Icons and Images should live in https://github.com/mozilla/addons-server/tree/master/static/img

**Comment by gregglind** [comment]
new commit.  I think this fulfills all the pieces.

```sh

#!/bin/bash

## goal, take a DIST  gregglind/shield-template, land it into amo.


set -x
set -o nounset
set -e
shopt -s expand_aliases

# templates -> https://github.com/mozilla/addons-server/tree/master/src/olympia/pages/templates/pages
#
# 8:02 <cgrebs> images -> https://github.com/mozilla/addons-server/tree/master/static/img
# 08:02 <cgrebs> best with a subfolder
#
# 08:02 <cgrebs> and the css to https://github.com/mozilla/addons-server/tree/master/static/css
# 08:02 <cgrebs> also into a subfolder
# 08:02 <cgrebs> and let me quickly figure out regarding how to link them in the html properly

# run a
# 08:17 <cgrebs> the html-file will be in pages/shield-stufy-1.h

D=$1
N=$2

## per cgrebs.

# main page, will need preprocessing
cp -f "$D"/index.html  ./src/olympia/pages/templates/pages/"$N".html

# styles / css
mkdir -p ./static/css/"$N"
cp -rf "$D"/styles/main.css  ./static/css/"$N"/


# images
mkdir -p ./static/img/"$N"
cp -rf "$D"/images  ./static/img/"$N"/
cp -rf "$D"/media  ./static/img/"$N"/

## all the re-pathing
AMOCSS=https://addons.cdn.mozilla.net/static/css/"$N"/
AMOIMG=https://addons.cdn.mozilla.net/static/img/"$N"/

perl -pi -e 's|styles/main.css|'$AMOCSS'main.css|g' ./src/olympia/pages/templates/pages/"$N".html
perl -pi -e 's|\.\./|'$AMOIMG'|g'   ./static/css/"$N"/main.css
```

**Comment by EnTeQuAk** [comment]
Superseeded by https://github.com/mozilla/addons-server/pull/1968 which we'll use for merging.

**Pull request closed without merging**
