### PR TITLE
Fix dockerfile deploy.

### PR DESCRIPTION
**Pull request by EnTeQuAk**
Fixes the Dockerfile.deploy to include the correct apt-get sources.list
file.

### CODE REVIEW

**Comment by muffinresearch** [comment]
Are we safe to use test apt sources in production? Presumably this means if a newer version of any package that we use is in the test repo it will be installed.

**Comment by EnTeQuAk** [comment]
> Are we safe to use test apt sources in production? Presumably this means if a newer version of any package that we use is in the test repo it will be installed.

We are only doing this explicitly for `file`, `libmagic` and libgit2-dev. We'll see failures on -dev long before we do on prod in case something happens but we're pretty safe in that regard imo.

**Comment by muffinresearch** [comment]
> > Are we safe to use test apt sources in production? Presumably this means if a newer version of any package that we use is in the test repo it will be installed.
> 
> We are only doing this explicitly for `file`, `libmagic` and `libgit2-dev`. We'll see failures on -dev long before we do on prod in case something happens but we're pretty safe in that regard imo.

I see, so this is limited to specific packages by the `-t` option to `apt-get`. Despite Still makes me a little bit nervous trusting a potentially unstable dist source.

**Comment by EnTeQuAk** [comment]
Closing for now to work on this a bit more

**Pull request closed without merging**
