### PR TITLE
Fixed #3683 and #3651

### LINKED ISSUE #3683: "Delete current photo" causing layout issues
### Steps to reproduce
Go to https://addons.mozilla.org/en-US/firefox/users/edit and scroll down till you get the profile picture

### AR
"Delete current photo" link is NOT aligned with the photo and other fields

### ER
There should be no blank space after "Choose Photo..". Basically, "Delete current photo" should be there

### Screen shot
bug

### PR DESCRIPTION
**Pull request by vijeth-aradhya**
Please have a look at the screen shots in the commit.

I have resolved two issues simultaneously in the same commit - #3683 and #3651 I hope that won't be a problem :)

I have reduced the margin to 0 (previously 137px)

### CODE REVIEW

**Comment by vijeth-aradhya** [comment]
@tofumatt Could you please get back to me as to what the update is?

**Comment by muffinresearch** [comment]
Hi @vijeth-aradhya - thanks for your PR.

For future reference please could put `Fixes #ISSUENUM` in the description and change the title to something that refers to what is being fixed? It makes it a bit easier for us to tell different issues apart and also github will link an issue reference in a description whereas it doesn't in the PR heading.

You can add `Fixes #ISSUENUM` multiple times if you are fixing more than one issue at a time, though in general one PR per issue is preferred. Don't worry about it for this PR, since the fixes are closely related to each other.

**Comment by atsay** [comment]
Thanks for the fix, Vijeth! We've added your contribution [here](https://wiki.mozilla.org/Add-ons/Contribute/Recognition#October_2016).

**Comment by vijeth-aradhya** [comment]
@atsay Thank you so much! I'm new to open source and I'm very happy that my little contribution was added!
Hope to contribute more!

**Pull request merged**
