### PR TITLE
Extract messages

### PR DESCRIPTION
**Pull request by EnTeQuAk**

### CODE REVIEW

**Comment by muffinresearch** [comment]
@EnTeQuAk Is this based on just the tag + the content update commit? 

I think that's what we'll need to be able to land translations related to the content changes, so there's nothing related to any other commits since the tag.

**Comment by EnTeQuAk** [comment]
hmm, it's actually based on the master. Let me re-do the extract real quick to make sure we have the proper ones.

**Comment by EnTeQuAk** [comment]
```
[git:extract-2016-11-16 (olympia)] ~/Projects/olympia> git log 2016.11.17..
commit d48faffd1eee26d0d5ea151ee1099542fd74a9ac
Author: Christopher Grebs <cg@webshox.org>
Date:   Wed Nov 16 11:21:09 2016 +0100

    Extract messages
```

should be fine now.

**Comment by muffinresearch** [comment]
> should be fine now. Problem with that is, we cannot simply merge this :(

@EnTeQuAk Would it be possible to start over, extract to the pot template, and then interactively remove everything but the translation we care about extracting (iirc you can use `git checkout -p`). That way when the msgmerge part is run it's only merging that minimal change? That should have less chance of conflicting and allow us to land the translations for the content changes more easily.

**Comment by diox** [comment]
Does github knows how to make a pull request from a tag ? That'd be easier to merge in it...

**Comment by muffinresearch** [comment]
This appears to be replaying the content update - was that expected?

**Comment by EnTeQuAk** [comment]
@muffinresearch I fixed this, my local master wasn't up-to-date on rebasing.

I also added the new translations that we got from Scott. I skipped Japanese and Polish since we didn't have any translations for those and never had so it would have looked even weirder (but let me know if I should add them nonetheless) and we don't have "Spanish Latin America", so I integrated "Spanish (Spain)" as `es`

**Comment by muffinresearch** [comment]
@EnTeQuAk the added translations look good. I restarted circle since it seemed to time out but travis is green. 

@mat what's the best plan for getting this onto stage? Presumably, since there's no conflicts it's easiest just to land this and cherry-pick it onto the tag, and push it to stage?

Once it's on stage, let me know and I'll spin-up the changed locales on the stage disco pane via nightly.

**Pull request merged**
