### PR TITLE
Team: Manuel, Rishi, Sammy: Fixed bug

### LINKED ISSUE #3939: Version notes should flow under the "add to firefox" button
### Describe the problem and steps to reproduce it:

Originally filed here: https://bugzilla.mozilla.org/show_bug.cgi?id=976220

> See https://addons.mozilla.org/en-US/firefox/addon/flagfox/versions/

> The "Add to Firefox" button on each version listing takes up the full right-side space of the entry. This causes the version notes to be cramped. Please widen things a little bit so the version notes can flow underneath the space where the button is. I can't fit in the full width of my version notes as-is. :/

### What happened?

There's a large margin on the right-hand side of the version notes block. 

### What did you expect to happen?

Text should be able to fill the full width of the block.
Currently text stops at the red line, it should continue to the green line.

wrapping-bug

Thanks @wagnerand for the screenshot

### PR DESCRIPTION
**Pull request by vazdeazm**
Fixes #3939

Hi Andreas

We believe we fixed the bug, can you please review and give us some feedback?

Best regards

Manuel Fernandes

### CODE REVIEW

**Comment by wagnerand** [comment]
Thank you for this patch. Can you include a 'before' and 'after' screenshot here?

**Comment by wagnerand** [comment]
For reference, I think this is about: https://bugzilla.mozilla.org/show_bug.cgi?id=976220

**Comment by Rishiahya** [comment]
image

**Comment by Rishiahya** [comment]
image

**Comment by Rishiahya** [comment]
Hello Andreas, I am a team member of Manuel, this is the before and after screenshot of the code Manuel had edited, to increase the width from 720px to 900px, which fixes the issue of there not being enough room for the version notes being cramped. Does this meet the requirement of fixing the bug?

Regards,
Rishi

**Comment by wagnerand** [comment]
Those screenshot do not show the release notes text overflowing. Also, could you please upload a screenshot in Firefox as well and using a higher resolution.

Thank you.

**Comment by Rishiahya** [comment]
What do you mean by the first point? "Those screenshot do not show the release notes text overflowing", the second screenshot shows the version notes on one line, is that what you mean? should it stay on two lines, because that's not what was asked within the bug?

**Comment by wagnerand** [comment]
The bug asks to increase the width of the release notes so they could take the full width of the box, see #3939. Of course, this is only noticeable if the release notes are actually long enough.

**Comment by Rishiahya** [comment]
image

**Comment by Rishiahya** [comment]
I am unable to make the screenshot any clearer atm, however this is on firefox and we managed to change the code so that the width of the release notes now expands to the 'green line'. I will also include a before screenshot in the next comment, is this what you require for the bug to be fixed?

**Comment by Rishiahya** [comment]
at the moment* is 'atm'

**Comment by Rishiahya** [comment]
image

**Comment by Rishiahya** [comment]
This is the before screenshot of the text being restricted, I hope this is what we needed to do, if not can you give us some guidance

**Comment by wagnerand** [comment]
I'm sorry but while your patch kind of resolves the issue, it is not what the bug is asking for. I'm not entirely comfortable accepting this patch.

What the bug asks for is described in #3939.
What this patch does is increasing the width of the whole content.

Adding some folks for feedback: @tofumatt @muffinresearch @designakt

**Comment by designakt** [comment]
The width of the version notes look fine to me as they are. [Longer lines will impact legibility.](http://baymard.com/blog/line-length-readability) No matter how we implement them.
We are already on the wider side with about 80 characters we can fit in one line. Optimum is 50-70 characters.
I would leave things as they are now. If add-on devs are concerned about the appearance of there version notes, there might be other things we can to to help that. (e.g. support lists in version notes.)

**Comment by Rishiahya** [comment]
So does that mean you'd like us to continue working on the bug, or shall we leave it as is, as  suggested by designakt?

**Comment by muffinresearch** [comment]
@Rishiahya based on the comments above I think it makes sense to close this one and mark the bug as wontfix.

Thanks for taking the time to work on this patch, I'm sorry that this bug ended up being a non-starter.

If you're still keen to contribute please take a look at other good first bugs listed on github here: https://github.com/mozilla/addons-server/labels/good%20first%20bug (Before starting work if you express an interest on an issue that will help us to qualify that the bug you're intending to work on is still relevant). 

If you're interested to work on the upcoming new front-end for AMO there's also good first bugs here: https://github.com/mozilla/addons-frontend/labels/good%20first%20bug . We'll look to create more good first bugs on the last repo in due course.

**Comment by designakt** [comment]
Hi @Rishiahya sorry that I got in the way of your contribution. I love that you teamed up to help, unfortunately we did not check the UX implication of the bug before you started. Sorry about that.
As @muffinresearch mentioned, you could help out on the new front-end for AMO. There is a lot going on currently, and you would help build the future of AMO. :-)

**Pull request closed without merging**
