### PR TITLE
Skip addons-linter waffle-flag creation if it already exists.

### PR DESCRIPTION
**Pull request by EnTeQuAk**

### CODE REVIEW

**Comment by eviljeff** [comment]
why not `INSERT INTO ...  ON DUPLICATE KEY UPDATE ...;` or  `UPDATE ...;`?

**Comment by EnTeQuAk** [comment]
a simple update doesn't work if the flag doesn't exist and `ON DUPLICATE KEY UPDATE` would require some messing with the description and I didn't check if `name` is actually unique. Plus I always forget it exists :laughing:

**Comment by eviljeff** [comment]
I think I meant `REPLACE` rather than `UPDATE`.  
E.g. (totally untested!):
`REPLACE INTO waffle_switch (name, active, note, created, modified)
    VALUES (
        'addons-linter', 0,
        'Waffle switch to enable addons-linter integration for WebExtensions.',
        NOW(), NOW());`

Aware we're bike shedding on a simple migration so r+wc and commit what you like :)

**Comment by diox** [comment]
It's a bit ugly but I'm going to merge it so that it goes into the tag.

**Comment by EnTeQuAk** [comment]
Thanks for merging! @eviljeff I think I might have never used `REPLACE` before. I'll take that into account for future migrations :)

**Comment by eviljeff** [comment]
so... we broke the waffle-switch page on stage and prod - the migration didn't set `modified` or `created` :(

**Comment by EnTeQuAk** [comment]
damn, I'll update the migration. I guess we'll have to fix stage and prod manually though?

**Comment by eviljeff** [comment]
It was fixed manually on prod and stage on Friday.

**Pull request merged**
