### PR TITLE
Restored install button for unsupported add-on (fix #2288)

### LINKED ISSUE #2288: Incompatible addon versions are inaccessible / can't be downloaded
Incompatible addon versions can't be downloaded because there is only a popup 'Not available for Firefox <int>.0'. This works neither from lists like search results, the details page summary, the version details near the bottom or the page listing all versions.
Example: [MinimizeToTray for FF 3.5](https://addons.mozilla.org/en-us/firefox/addon/minimizetotray-for-ff-35/versions/)
Use case: To look into the code of these extensions.

### PR DESCRIPTION
**Pull request by tofumatt**
### Before

screenshot 2016-04-13 19 43 38
screenshot 2016-04-13 19 44 19

### After

screenshot 2016-04-13 19 33 03
screenshot 2016-04-13 19 45 40

### CODE REVIEW

**Comment by muffinresearch** [comment]
This was the old behaviour. This seems fine - assuming UX are good with it.

minimizetotray_for_ff_3_5____versions____add-ons_for_firefox

**Comment by tofumatt** [comment]
Cool, I'll go with a more muted/disabled style :+1:

**Comment by muffinresearch** [comment]
> Cool, I'll go with a more muted/disabled style :+1:

I meant your change is cool if UX are happy. Not make it like that ^ :)

**Comment by tofumatt** [comment]
Oh, haha! Okay, pinging @pwalm, is the new less opaque install button okay over the greyed out one?

**Comment by muffinresearch** [comment]
/me casts the spell to invoke UX

**Comment by pwalm** [comment]
💥  Grey it out! 💥

**Comment by tofumatt** [comment]
New, greyed-out versions:

screenshot 2016-04-13 21 56 03
screenshot 2016-04-13 21 55 56
screenshot 2016-04-13 21 55 49

**Comment by tofumatt** [comment]
UX-approved on IRC!

**Pull request merged**
