### PR TITLE
Allow setting the recursion limit with RECURSION_LIMIT

### LINKED ISSUE #1911: Increase the recursion limit
There are some add-ons that are failing validation and we think it might be due to the python recursion limit being reached. We should increase it to at least `10000`, it can be increased using `sys.setrecursionlimit()`. I'm not sure if there's any other way of setting it.

Related to https://github.com/mozilla/addons-server/issues/1885 and https://github.com/mozilla/addons/issues/41.

### PR DESCRIPTION
**Pull request by mstriemer**
Fixes #1911

### CODE REVIEW

**Comment by jasonthomas** [comment]
r+

**Comment by diox** [comment]
the recurion ? :)

**Comment by mstriemer** [comment]
I seem to have trouble spelling that word. I also typod it as `recurtion` a few times for some reason.

**Pull request merged**
