### PR TITLE
Upgrade Node to v14

### LINKED ISSUE #17331: Node 14
With Node 16 already available, we can switch from Node 12 to Node 14 in the coming weeks. This issue is about doing it.

### PR DESCRIPTION
**Pull request by bqbn**
Fix #17331

* [X] This PR relates to an existing open issue and there are no existing
      PRs open for the same issue.
* [X] Add `Fixes #ISSUENUM` at the top of your PR.
* [X] The change has been successfully run locally.

### CODE REVIEW

**Comment by willdurand** [comment]
@diox any idea why circle ci didn't get triggered?

**Comment by diox** [comment]
No, that's weird... There is this bug if CircleCI is set up on your own fork it will run first there and then not re-trigger on the PR, but that doesn't seem to be what happened here - I don't think CircleCI is set up on @bqbn's fork.

**Comment by willdurand** [comment]
Force-pushing to the same branch didn't do anything but pushing this same commit into a different branch on this repo started a Circle build and... apparently CI checks are shown here? Amazing! (no)

**Comment by diox** [comment]
Weird...

**Comment by willdurand** [comment]
So that looks quite good, let's merge this patch.

**Pull request merged**
