### PR TITLE
Consent page for Shield study 7 - Activity Stream

### PR DESCRIPTION
**Pull request by tspurway**
See tracking bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1301166

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
This looks great, and thanks for the tests!

I'm simply going to merge this and post the URL where it's accessible once it lands on `-dev`. We will tag later today so it'll be on stage and deployed to production on Thursday.

**Comment by tspurway** [comment]
@EnTeQuAk - are you going to post both the updateLink and updateURL?  (https://github.com/mozilla/activity-stream/blob/master/package.json#L260-L261) 

Will you post it in this PR?

**Comment by EnTeQuAk** [comment]
Not sure what you mean with `updateLink` and `updateURL` - you can see how the page you landed looks like in our development environment: https://addons-dev.allizom.org/en-US/firefox/shield_study_7

This will go live on Thursday.

**Comment by muffinresearch** [comment]
It's now on stage here: https://addons.allizom.org/en-US/firefox/shield_study_7

**Pull request merged**
