### PR TITLE
Extract and compile l10n

### PR DESCRIPTION
**Pull request by EnTeQuAk**

### CODE REVIEW

**Comment by muffinresearch** [comment]
If you split commits for extraction, merge and compile (or just merge and compile) does that help being able to view the diff?

**Comment by EnTeQuAk** [comment]
@muffinresearch reduced to only extraction, github's limit is way too low though to be able to view it now too but maybe that helps. Still working on proper automation so that's how it is currently :(

**Comment by muffinresearch** [comment]
I've just finished scanning through the whole original diff offline. Not fun - and it would be incredibly easy to have missed something - it would take hours to properly scrutinise such a diff properly.

Automating this so we have more frequent smaller diffs will be brilliant. 👍

r+wc for 63c2070 (wc being "with caveats" 😄 )

**Comment by EnTeQuAk** [comment]
I totally agree. On the other hand, afair we only "extract, compile, push" (not much review) in the past anyway so we're slowly improving the state of things. Hopefully with automation during the next few weeks.

Thanks for the review!

**Pull request merged**
