### PR TITLE
Update addons-linter

### PR DESCRIPTION
**Pull request by wagnerand**

### CODE REVIEW

**Comment by wagnerand** [comment]
@tofumatt `TestRunAddonsLinter.test_run_linter_use_temporary_file_large_output` fails, is this because of https://github.com/mozilla/addons-linter/commit/23748e4a5e84a2cd707f1f96c5d687a13a070cdc?

**Comment by wagnerand** [comment]
No, the linter does not set `success` at all. This test did not fail in the past because the test used to throw an error:
`src/olympia/devhub/tests/test_tasks.py::TestRunAddonsLinter::test_run_linter_use_temporary_file_large_output 20:01:53 z.devhub.task:ERROR Failed to run validation on addon id: 3615,  :/home/travis/build/mozilla/addons-server/src/olympia/devhub/tasks.py:504`
https://travis-ci.org/mozilla/addons-server/jobs/151321026#L984

Is it safe to remove the `assert result['success']` since we already `assert not result['errors']` two lines down?

**Comment by EnTeQuAk** [comment]
I generally would love to have an add-on there that passes validation so if we could fix the json files in our test-file that'd be awesome. Otherwise we should do at least something like

```python
ipdb> set(itertools.chain.from_iterable([msg['id'] for msg in result['messages'] if msg['type'] == 'error'])) == {u'JSON_DUPLICATE_KEY'}
True
``
to make sure things are not failing in a different manner than we expect. You may change the success result check if you add a check for the specific errors.

**Comment by EnTeQuAk** [comment]
Superseeded by https://github.com/mozilla/addons-server/pull/3317 since I'm taking over quickly

**Pull request closed without merging**
