### PR TITLE
some trivial spelling fixes

### PR DESCRIPTION
**Pull request by ka7**
( travis might fail at the flake8-test, but i cant find a good reason in my changes )

### CODE REVIEW

**Comment by wagnerand** [comment]
The travis logfile (https://travis-ci.org/mozilla/addons-server/jobs/145238681) shows the issues:

```
src/olympia/addons/tests/test_views.py:808:80: E501 line too long (80 > 79 characters)
src/olympia/files/tasks.py:108:80: E501 line too long (80 > 79 characters)
src/olympia/lib/es/utils.py:64:80: E501 line too long (80 > 79 characters)
```

**Comment by ka7** [comment]
Yes, but my patch even shorten them. Other build-logs dont show this...
But i will Fix this...

.ka

Am 16. Juli 2016 19:30:10 MESZ, schrieb Andreas Wagner <notifications@github.com>:
>The travis logfile
>(https://travis-ci.org/mozilla/addons-server/jobs/145238681) shows the
>issues:
>
>```
>src/olympia/addons/tests/test_views.py:808:80: E501 line too long (80 >
>79 characters)
>src/olympia/files/tasks.py:108:80: E501 line too long (80 > 79
>characters)
>src/olympia/lib/es/utils.py:64:80: E501 line too long (80 > 79
>characters)
>```
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mozilla/addons-server/pull/3107#issuecomment-233141453

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by wagnerand** [comment]
Great, thanks!

**Comment by wagnerand** [comment]
r+

**Pull request merged**
