### PR TITLE
fixes #9028

### LINKED ISSUE #9028: [Reviewer Tools] Layout of reviewers-score-bar
Recently, due to changes the layout has been affected:
ref: `<div id="reviewers-score-bar" class="c">`
The + 140 is wrapped.

TBH, I think the text is too long and changing "Post-Approval Add-on Review" to "Post-Approval Review" would be fine. Otherwise, a change to `<td class="number">+140</td>` would be needed.

https://screenshots.firefox.com/KSaHRSXP3WxvvseU/reviewers.addons.mozilla.org
Screenshot

### PR DESCRIPTION
**Pull request by shiri1248**
Instead of "Post-Approval Add-on Review" replace with "Post-Approval Review" 
#9028

### CODE REVIEW

**Comment by wagnerand** [comment]
We should probably prefix reviews of legacy with "Legacy", so we can drop "Post-Approval" instead. We should not drop "Add-on", since there are other kinds of reviews, besides "Add-on Review".

**Comment by shiri1248** [comment]
ok  @wagnerand  I understood the complexity, so the word should be "Add-on  Review Legacy" am I right ?

**Comment by wagnerand** [comment]
Line 63 should be "New Legacy Add-on Review"
Line 65 should be "Updated Legacy Add-on Review"
Lines 84-90 should have "Post Approval" removed.

**Comment by caitmuenster** [comment]
Thanks for the patch, @shiri1248! Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition) and your mozillians.org profile has been vouched. 

I look forward to seeing you around the project! ✨

**Comment by shiri1248** [comment]
@wagnerand @caitmuenster  Thanks for supporting me. This is my first  patch for open source project.

**Pull request merged**
