### PR TITLE
fix: Remove "www." of "buymeacoffee.com"

### LINKED ISSUE #22204: Update `buymeacoffee.com` contribution domain to remove the `www.` prefix
### Describe the problem and steps to reproduce it:
- Create an add-on
- Add a contribution URL for your `buymeacoffee.com` URL without the `www.`, i.e. `https://buymeacoffee.com/lol`

### What happened?
- You get an error (`URL domain must be one of [www.buymeacoffee.com, donate.mozilla.org, flattr.com, github.com, ko-fi.com, liberapay.com, www.micropayment.de, opencollective.com, www.patreon.com, www.paypal.com, paypal.me].`) because the `www.` prefix is required for that domain.

### What did you expect to happen?
- The contribution URL is recorded with no errors.

### Anything else we should know?
In https://github.com/mozilla/addons-server/pull/22183, @regseb noted:
> https://www.buymeacoffee.com/regseb (with www. prefix) links are redirected to https://buymeacoffee.com/regseb (without www. prefix).

We should stop requiring the `www.` prefix for that domain in contribution URLs, and migrate any existing links to remove it.

### PR DESCRIPTION
**Pull request by regseb**
Fix #22204

* [x] Add a description of the changes introduced in this PR.
* [ ] The change has been successfully run locally.
* [ ] Add tests to cover the changes added in this PR.
* [ ] Add before and after screenshots (Only for changes that impact the UI).

<https://www.buymeacoffee.com/regseb> (**with** `www.` prefix) links are redirected to <https://buymeacoffee.com/regseb> (**without** `www.` prefix). So I removed `www.` in `VALID_CONTRIBUTION_DOMAINS`.

### CODE REVIEW

**Comment by diox** [comment]
Hi,

I filed https://github.com/mozilla/addons-server/issues/22204 on your behalf. One thing we will need to do as part of this is a data migration to update existing links in our database, otherwise validation would fail for any add-on which already had a `buymeacoffee` link with the `www.`, next time they try to edit it.

**Comment by regseb** [comment]
I've updated the [`src/olympia/addons/migrations/__init__.py`](https://github.com/mozilla/addons-server/pull/22183/files#diff-1ee88d1e2a0a807c48552c5f6db02db50209f144cd67c334a3ffd8325e04cb0e) file to replace `'www.buymeacoffee.com'` with `'buymeacoffee.com'`.

This file must not be modified. Instead, I need to create a new file `src/olympia/addons/migrations/0050_remove_www_of_buymeacoffee.py`?

```python
from urllib.parse import urlsplit, urlunsplit

from django.db import migrations
from django.db.models import Q

from olympia.addons.tasks import index_addons


CONTRIBUTION_CHANGES = {
    'www.buymeacoffee.com': 'buymeacoffee.com',
}


def fix_contributions_url(url):
    try:
        split_url = urlsplit(url)
        if (hostname := split_url.hostname) in CONTRIBUTION_CHANGES:
            split_url = split_url._replace(
                netloc=split_url.netloc.replace(
                    hostname, CONTRIBUTION_CHANGES[hostname]
                )
            )
    except ValueError:
        return url
    return urlunsplit(split_url)


def contributions_url_remove_www(apps, schema_editor):
    Addon = apps.get_model('addons', 'Addon')
    to_index = []

    for addon in Addon.unfiltered.filter(~Q(contributions=''), contributions__isnull=False):
        try:
            new_url = fix_contributions_url(addon.contributions)
            if new_url != addon.contributions:
                addon.contributions = new_url
                addon.save()
                to_index.append(addon.id)
        except ValueError:
            pass
    if to_index:
        index_addons.delay(to_index)


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(contributions_url_remove_www)]
```

**Comment by diox** [comment]
Yes. You can also simplify this migration because at this point, contributions URLs should all starts with `https://` anyway. So you don't need to do any parsing, you can to a straight replace, and you also can directly filter the queryset. So it would look something like this (untested): ` Addon.unfiltered.filter(contributions__startswith='https://www.buymeacoffee.com').update(contributions=Replace('contributions', Value('www.buymeacoffee.com'), Value('buymeacoffee.com')))`

**Comment by regseb** [comment]
I've added a migration script. However, I know neither Python nor Django. I wrote the code with copy-paste.

**Pull request merged**
