### PR TITLE
localizable download links #6476

### LINKED ISSUE #6476: Firefox download links are not localizable
The text inside the links should be wrapped in the relevant gettext calls so they can be updated.

https://github.com/mozilla/addons-server/blob/00c3711a1a7a23921fa81cc62683c9d627ef9234/src/olympia/templates/footer.html#L13-L19

### PR DESCRIPTION
**Pull request by ilmanzo**
[Fixes #6476](https://github.com/mozilla/addons-server/issues/6476)

### CODE REVIEW

**Comment by EnTeQuAk** [comment]
Looks great to me, thanks a lot for that contribution!

**Comment by ilmanzo** [comment]
Thanks to you, it's my first Mozilla PR :)

**Comment by Mte90** [comment]
Italians start to conquer the addons-server :-D

**Comment by EnTeQuAk** [comment]
> Italians start to conquer the addons-server :-D

🇮🇹 🍋 🍸

**Comment by caitmuenster** [comment]
\o/ Welcome onboard, @ilmanzo! Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition#September_2017). 

If you would like to set up a profile on [mozillians.org](https://mozillians.org/en-US/), I would be happy to vouch for you!

**Pull request merged**
